// AUTO-GENERATED by scripts/generate-resources.ts — do not edit directly.
// Re-run `npm run generate` after updating the specs submodule.
import type { HttpTransport } from '../../http/transport.js';
import type * as T from './generated/types.gen.js';

export class WorkflowsResource {
  constructor(private readonly transport: HttpTransport) {}

  /** Get Workflow */
  async getWorkflow(params: T.GetWorkflowData['query']): Promise<T.GetWorkflowResponses[keyof T.GetWorkflowResponses]> {
    return this.transport.request<T.GetWorkflowResponses[keyof T.GetWorkflowResponses]>({
      method: "GET",
      path: "/workflows/",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
      },
    });
  }
}
