// AUTO-GENERATED by scripts/generate-resources.ts — do not edit directly.
// Re-run `npm run generate` after updating the specs submodule.
import type { HttpTransport } from '../../http/transport.js';
import type * as T from './generated/types.gen.js';

export class EmailIsvResource {
  constructor(private readonly transport: HttpTransport) {}

  /** Email Verification */
  async verifyEmail(params: T.VerifyEmailData['query'] & T.VerifyEmailData['body']): Promise<T.VerifyEmailResponses[keyof T.VerifyEmailResponses]> {
    return this.transport.request<T.VerifyEmailResponses[keyof T.VerifyEmailResponses]>({
      method: "POST",
      path: "/email/verify",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
      },
      body: params,
    });
  }
}
