// AUTO-GENERATED by scripts/generate-resources.ts — do not edit directly.
// Re-run `npm run generate` after updating the specs submodule.
import type { HttpTransport } from '../../http/transport.js';
import { buildPath } from '../shared/build-path.js';
import type * as T from './generated/types.gen.js';

export class MediasResource {
  constructor(private readonly transport: HttpTransport) {}

  /** Get List of Files/ Folders */
  async fetchMediaContent(params: T.FetchMediaContentData['query']): Promise<T.FetchMediaContentResponses[keyof T.FetchMediaContentResponses]> {
    return this.transport.request<T.FetchMediaContentResponses[keyof T.FetchMediaContentResponses]>({
      method: "GET",
      path: "/medias/files",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "offset": (params as unknown as Record<string, any>)["offset"],
        "limit": (params as unknown as Record<string, any>)["limit"],
        "sortBy": (params as unknown as Record<string, any>)["sortBy"],
        "sortOrder": (params as unknown as Record<string, any>)["sortOrder"],
        "type": (params as unknown as Record<string, any>)["type"],
        "query": (params as unknown as Record<string, any>)["query"],
        "altType": (params as unknown as Record<string, any>)["altType"],
        "altId": (params as unknown as Record<string, any>)["altId"],
        "parentId": (params as unknown as Record<string, any>)["parentId"],
        "fetchAll": (params as unknown as Record<string, any>)["fetchAll"],
      },
    });
  }

  /** Upload File into Media Storage */
  async uploadMediaContent(): Promise<T.UploadMediaContentResponses[keyof T.UploadMediaContentResponses]> {
    return this.transport.request<T.UploadMediaContentResponses[keyof T.UploadMediaContentResponses]>({
      method: "POST",
      path: "/medias/upload-file",
      securityScheme: "Location-Access",
      locationId: undefined,
      companyId: undefined,
    });
  }

  /** Update File/ Folder */
  async updateMediaObject(params: T.UpdateMediaObjectData['path'] & T.UpdateMediaObjectData['body']): Promise<T.UpdateMediaObjectResponses[keyof T.UpdateMediaObjectResponses]> {
    return this.transport.request<T.UpdateMediaObjectResponses[keyof T.UpdateMediaObjectResponses]>({
      method: "POST",
      path: buildPath("/medias/{id}", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Delete File or Folder */
  async deleteMediaContent(params: T.DeleteMediaContentData['path'] & T.DeleteMediaContentData['query']): Promise<void> {
    return this.transport.request<void>({
      method: "DELETE",
      path: buildPath("/medias/{id}", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "altType": (params as unknown as Record<string, any>)["altType"],
        "altId": (params as unknown as Record<string, any>)["altId"],
      },
    });
  }

  /** Create Folder */
  async createMediaFolder(params: T.CreateMediaFolderData['body']): Promise<T.CreateMediaFolderResponses[keyof T.CreateMediaFolderResponses]> {
    return this.transport.request<T.CreateMediaFolderResponses[keyof T.CreateMediaFolderResponses]>({
      method: "POST",
      path: "/medias/folder",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Bulk Update Files/ Folders */
  async bulkUpdateMediaObjects(params: T.BulkUpdateMediaObjectsData['body']): Promise<T.BulkUpdateMediaObjectsResponses[keyof T.BulkUpdateMediaObjectsResponses]> {
    return this.transport.request<T.BulkUpdateMediaObjectsResponses[keyof T.BulkUpdateMediaObjectsResponses]>({
      method: "PUT",
      path: "/medias/update-files",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Bulk Delete / Trash Files or Folders */
  async bulkDeleteMediaObjects(params: T.BulkDeleteMediaObjectsData['body']): Promise<T.BulkDeleteMediaObjectsResponses[keyof T.BulkDeleteMediaObjectsResponses]> {
    return this.transport.request<T.BulkDeleteMediaObjectsResponses[keyof T.BulkDeleteMediaObjectsResponses]>({
      method: "PUT",
      path: "/medias/delete-files",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }
}
