// AUTO-GENERATED by scripts/generate-resources.ts — do not edit directly.
// Re-run `npm run generate` after updating the specs submodule.
import type { HttpTransport } from '../../http/transport.js';
import type * as T from './generated/types.gen.js';

export class CoursesResource {
  constructor(private readonly transport: HttpTransport) {}

  /** Import Courses */
  async importCourses(params: T.ImportCoursesData['body']): Promise<void> {
    return this.transport.request<void>({
      method: "POST",
      path: "/courses/courses-exporter/public/import",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }
}
