// AUTO-GENERATED by scripts/generate-resources.ts — do not edit directly.
// Re-run `npm run generate` after updating the specs submodule.
import type { HttpTransport } from '../../http/transport.js';
import { buildPath } from '../shared/build-path.js';
import type * as T from './generated/types.gen.js';

export class CalendarsResource {
  constructor(private readonly transport: HttpTransport) {}

  /** Get Groups */
  async getGroups(params: T.GetGroupsData['query']): Promise<T.GetGroupsResponses[keyof T.GetGroupsResponses]> {
    return this.transport.request<T.GetGroupsResponses[keyof T.GetGroupsResponses]>({
      method: "GET",
      path: "/calendars/groups",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
      },
    });
  }

  /** Create Calendar Group */
  async createCalendarGroup(params: T.CreateCalendarGroupData['body']): Promise<T.CreateCalendarGroupResponses[keyof T.CreateCalendarGroupResponses]> {
    return this.transport.request<T.CreateCalendarGroupResponses[keyof T.CreateCalendarGroupResponses]>({
      method: "POST",
      path: "/calendars/groups",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Validate group slug */
  async validateGroupsSlug(params: T.ValidateGroupsSlugData['body']): Promise<T.ValidateGroupsSlugResponses[keyof T.ValidateGroupsSlugResponses]> {
    return this.transport.request<T.ValidateGroupsSlugResponses[keyof T.ValidateGroupsSlugResponses]>({
      method: "POST",
      path: "/calendars/groups/validate-slug",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Update Group */
  async editGroup(params: T.EditGroupData['path'] & T.EditGroupData['body']): Promise<T.EditGroupResponses[keyof T.EditGroupResponses]> {
    return this.transport.request<T.EditGroupResponses[keyof T.EditGroupResponses]>({
      method: "PUT",
      path: buildPath("/calendars/groups/{groupId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Delete Group */
  async deleteGroup(params: T.DeleteGroupData['path']): Promise<T.DeleteGroupResponses[keyof T.DeleteGroupResponses]> {
    return this.transport.request<T.DeleteGroupResponses[keyof T.DeleteGroupResponses]>({
      method: "DELETE",
      path: buildPath("/calendars/groups/{groupId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** Disable Group */
  async disableGroup(params: T.DisableGroupData['path'] & T.DisableGroupData['body']): Promise<T.DisableGroupResponses[keyof T.DisableGroupResponses]> {
    return this.transport.request<T.DisableGroupResponses[keyof T.DisableGroupResponses]>({
      method: "PUT",
      path: buildPath("/calendars/groups/{groupId}/status", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Create appointment */
  async createAppointment(params: T.CreateAppointmentData['body']): Promise<T.CreateAppointmentResponses[keyof T.CreateAppointmentResponses]> {
    return this.transport.request<T.CreateAppointmentResponses[keyof T.CreateAppointmentResponses]>({
      method: "POST",
      path: "/calendars/events/appointments",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Get Appointment */
  async getAppointment(params: T.GetAppointmentData['path']): Promise<T.GetAppointmentResponses[keyof T.GetAppointmentResponses]> {
    return this.transport.request<T.GetAppointmentResponses[keyof T.GetAppointmentResponses]>({
      method: "GET",
      path: buildPath("/calendars/events/appointments/{eventId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** Update Appointment */
  async editAppointment(params: T.EditAppointmentData['path'] & T.EditAppointmentData['body']): Promise<T.EditAppointmentResponses[keyof T.EditAppointmentResponses]> {
    return this.transport.request<T.EditAppointmentResponses[keyof T.EditAppointmentResponses]>({
      method: "PUT",
      path: buildPath("/calendars/events/appointments/{eventId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Get Calendar Events */
  async getCalendarEvents(params: T.GetCalendarEventsData['query']): Promise<T.GetCalendarEventsResponses[keyof T.GetCalendarEventsResponses]> {
    return this.transport.request<T.GetCalendarEventsResponses[keyof T.GetCalendarEventsResponses]>({
      method: "GET",
      path: "/calendars/events",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "userId": (params as unknown as Record<string, any>)["userId"],
        "calendarId": (params as unknown as Record<string, any>)["calendarId"],
        "groupId": (params as unknown as Record<string, any>)["groupId"],
        "startTime": (params as unknown as Record<string, any>)["startTime"],
        "endTime": (params as unknown as Record<string, any>)["endTime"],
      },
    });
  }

  /** Get Blocked Slots */
  async getBlockedSlots(params: T.GetBlockedSlotsData['query']): Promise<T.GetBlockedSlotsResponses[keyof T.GetBlockedSlotsResponses]> {
    return this.transport.request<T.GetBlockedSlotsResponses[keyof T.GetBlockedSlotsResponses]>({
      method: "GET",
      path: "/calendars/blocked-slots",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "userId": (params as unknown as Record<string, any>)["userId"],
        "calendarId": (params as unknown as Record<string, any>)["calendarId"],
        "groupId": (params as unknown as Record<string, any>)["groupId"],
        "startTime": (params as unknown as Record<string, any>)["startTime"],
        "endTime": (params as unknown as Record<string, any>)["endTime"],
      },
    });
  }

  /** Create Block Slot */
  async createBlockSlot(params: T.CreateBlockSlotData['body']): Promise<T.CreateBlockSlotResponses[keyof T.CreateBlockSlotResponses]> {
    return this.transport.request<T.CreateBlockSlotResponses[keyof T.CreateBlockSlotResponses]>({
      method: "POST",
      path: "/calendars/events/block-slots",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Update Block Slot */
  async editBlockSlot(params: T.EditBlockSlotData['path'] & T.EditBlockSlotData['body']): Promise<T.EditBlockSlotResponses[keyof T.EditBlockSlotResponses]> {
    return this.transport.request<T.EditBlockSlotResponses[keyof T.EditBlockSlotResponses]>({
      method: "PUT",
      path: buildPath("/calendars/events/block-slots/{eventId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Get Free Slots */
  async getSlots(params: T.GetSlotsData['path'] & T.GetSlotsData['query']): Promise<T.GetSlotsResponses[keyof T.GetSlotsResponses]> {
    return this.transport.request<T.GetSlotsResponses[keyof T.GetSlotsResponses]>({
      method: "GET",
      path: buildPath("/calendars/{calendarId}/free-slots", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "startDate": (params as unknown as Record<string, any>)["startDate"],
        "endDate": (params as unknown as Record<string, any>)["endDate"],
        "timezone": (params as unknown as Record<string, any>)["timezone"],
        "userId": (params as unknown as Record<string, any>)["userId"],
        "userIds": (params as unknown as Record<string, any>)["userIds"],
      },
    });
  }

  /** Get Calendar */
  async getCalendar(params: T.GetCalendarData['path']): Promise<T.GetCalendarResponses[keyof T.GetCalendarResponses]> {
    return this.transport.request<T.GetCalendarResponses[keyof T.GetCalendarResponses]>({
      method: "GET",
      path: buildPath("/calendars/{calendarId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** Update Calendar */
  async updateCalendar(params: T.UpdateCalendarData['path'] & T.UpdateCalendarData['body']): Promise<T.UpdateCalendarResponses[keyof T.UpdateCalendarResponses]> {
    return this.transport.request<T.UpdateCalendarResponses[keyof T.UpdateCalendarResponses]>({
      method: "PUT",
      path: buildPath("/calendars/{calendarId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Delete Calendar */
  async deleteCalendar(params: T.DeleteCalendarData['path']): Promise<T.DeleteCalendarResponses[keyof T.DeleteCalendarResponses]> {
    return this.transport.request<T.DeleteCalendarResponses[keyof T.DeleteCalendarResponses]>({
      method: "DELETE",
      path: buildPath("/calendars/{calendarId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** Delete Event */
  async deleteEvent(params: T.DeleteEventData['path'] & T.DeleteEventData['body']): Promise<T.DeleteEventResponses[keyof T.DeleteEventResponses]> {
    return this.transport.request<T.DeleteEventResponses[keyof T.DeleteEventResponses]>({
      method: "DELETE",
      path: buildPath("/calendars/events/{eventId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Get Notes */
  async getAppointmentNotes(params: T.GetAppointmentNotesData['path'] & T.GetAppointmentNotesData['query']): Promise<T.GetAppointmentNotesResponses[keyof T.GetAppointmentNotesResponses]> {
    return this.transport.request<T.GetAppointmentNotesResponses[keyof T.GetAppointmentNotesResponses]>({
      method: "GET",
      path: buildPath("/calendars/appointments/{appointmentId}/notes", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "limit": (params as unknown as Record<string, any>)["limit"],
        "offset": (params as unknown as Record<string, any>)["offset"],
      },
    });
  }

  /** Create Note */
  async createAppointmentNote(params: T.CreateAppointmentNoteData['path'] & T.CreateAppointmentNoteData['body']): Promise<T.CreateAppointmentNoteResponses[keyof T.CreateAppointmentNoteResponses]> {
    return this.transport.request<T.CreateAppointmentNoteResponses[keyof T.CreateAppointmentNoteResponses]>({
      method: "POST",
      path: buildPath("/calendars/appointments/{appointmentId}/notes", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Update Note */
  async updateAppointmentNote(params: T.UpdateAppointmentNoteData['path'] & T.UpdateAppointmentNoteData['body']): Promise<T.UpdateAppointmentNoteResponses[keyof T.UpdateAppointmentNoteResponses]> {
    return this.transport.request<T.UpdateAppointmentNoteResponses[keyof T.UpdateAppointmentNoteResponses]>({
      method: "PUT",
      path: buildPath("/calendars/appointments/{appointmentId}/notes/{noteId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Delete Note */
  async deleteAppointmentNote(params: T.DeleteAppointmentNoteData['path']): Promise<T.DeleteAppointmentNoteResponses[keyof T.DeleteAppointmentNoteResponses]> {
    return this.transport.request<T.DeleteAppointmentNoteResponses[keyof T.DeleteAppointmentNoteResponses]>({
      method: "DELETE",
      path: buildPath("/calendars/appointments/{appointmentId}/notes/{noteId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** Get Calendar Resource */
  async getCalendarResource(params: T.GetCalendarResourceData['path']): Promise<T.GetCalendarResourceResponses[keyof T.GetCalendarResourceResponses]> {
    return this.transport.request<T.GetCalendarResourceResponses[keyof T.GetCalendarResourceResponses]>({
      method: "GET",
      path: buildPath("/calendars/resources/{resourceType}/{id}", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** Update Calendar Resource */
  async updateCalendarResource(params: T.UpdateCalendarResourceData['path'] & T.UpdateCalendarResourceData['body']): Promise<T.UpdateCalendarResourceResponses[keyof T.UpdateCalendarResourceResponses]> {
    return this.transport.request<T.UpdateCalendarResourceResponses[keyof T.UpdateCalendarResourceResponses]>({
      method: "PUT",
      path: buildPath("/calendars/resources/{resourceType}/{id}", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Delete Calendar Resource */
  async deleteCalendarResource(params: T.DeleteCalendarResourceData['path']): Promise<T.DeleteCalendarResourceResponses[keyof T.DeleteCalendarResourceResponses]> {
    return this.transport.request<T.DeleteCalendarResourceResponses[keyof T.DeleteCalendarResourceResponses]>({
      method: "DELETE",
      path: buildPath("/calendars/resources/{resourceType}/{id}", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** List Calendar Resources */
  async fetchCalendarResources(params: T.FetchCalendarResourcesData['path'] & T.FetchCalendarResourcesData['query']): Promise<T.FetchCalendarResourcesResponses[keyof T.FetchCalendarResourcesResponses]> {
    return this.transport.request<T.FetchCalendarResourcesResponses[keyof T.FetchCalendarResourcesResponses]>({
      method: "GET",
      path: buildPath("/calendars/resources/{resourceType}", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "limit": (params as unknown as Record<string, any>)["limit"],
        "skip": (params as unknown as Record<string, any>)["skip"],
      },
    });
  }

  /** Create Calendar Resource */
  async createCalendarResource(params: T.CreateCalendarResourceData['path'] & T.CreateCalendarResourceData['body']): Promise<T.CreateCalendarResourceResponses[keyof T.CreateCalendarResourceResponses]> {
    return this.transport.request<T.CreateCalendarResourceResponses[keyof T.CreateCalendarResourceResponses]>({
      method: "POST",
      path: buildPath("/calendars/resources/{resourceType}", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Get notifications */
  async getEventNotification(params: T.GetEventNotificationData['path'] & T.GetEventNotificationData['query']): Promise<T.GetEventNotificationResponses[keyof T.GetEventNotificationResponses]> {
    return this.transport.request<T.GetEventNotificationResponses[keyof T.GetEventNotificationResponses]>({
      method: "GET",
      path: buildPath("/calendars/{calendarId}/notifications", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "isActive": (params as unknown as Record<string, any>)["isActive"],
        "deleted": (params as unknown as Record<string, any>)["deleted"],
        "limit": (params as unknown as Record<string, any>)["limit"],
        "skip": (params as unknown as Record<string, any>)["skip"],
      },
    });
  }

  /** Create notification */
  async createEventNotification(params: T.CreateEventNotificationData['path'] & T.CreateEventNotificationData['body']): Promise<T.CreateEventNotificationResponses[keyof T.CreateEventNotificationResponses]> {
    return this.transport.request<T.CreateEventNotificationResponses[keyof T.CreateEventNotificationResponses]>({
      method: "POST",
      path: buildPath("/calendars/{calendarId}/notifications", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Get notification */
  async findEventNotification(params: T.FindEventNotificationData['path']): Promise<T.FindEventNotificationResponses[keyof T.FindEventNotificationResponses]> {
    return this.transport.request<T.FindEventNotificationResponses[keyof T.FindEventNotificationResponses]>({
      method: "GET",
      path: buildPath("/calendars/{calendarId}/notifications/{notificationId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** Update notification */
  async updateEventNotification(params: T.UpdateEventNotificationData['path'] & T.UpdateEventNotificationData['body']): Promise<T.UpdateEventNotificationResponses[keyof T.UpdateEventNotificationResponses]> {
    return this.transport.request<T.UpdateEventNotificationResponses[keyof T.UpdateEventNotificationResponses]>({
      method: "PUT",
      path: buildPath("/calendars/{calendarId}/notifications/{notificationId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Delete Notification */
  async deleteEventNotification(params: T.DeleteEventNotificationData['path']): Promise<T.DeleteEventNotificationResponses[keyof T.DeleteEventNotificationResponses]> {
    return this.transport.request<T.DeleteEventNotificationResponses[keyof T.DeleteEventNotificationResponses]>({
      method: "DELETE",
      path: buildPath("/calendars/{calendarId}/notifications/{notificationId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** List user availability schedule */
  async getAllSchedules(params: T.GetAllSchedulesData['query']): Promise<T.GetAllSchedulesResponses[keyof T.GetAllSchedulesResponses]> {
    return this.transport.request<T.GetAllSchedulesResponses[keyof T.GetAllSchedulesResponses]>({
      method: "GET",
      path: "/calendars/schedules/search",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "userId": (params as unknown as Record<string, any>)["userId"],
        "calendarId": (params as unknown as Record<string, any>)["calendarId"],
        "skip": (params as unknown as Record<string, any>)["skip"],
        "limit": (params as unknown as Record<string, any>)["limit"],
      },
    });
  }

  /** Get user availability schedule */
  async getScheduleById(params: T.GetScheduleByIdData['path']): Promise<T.GetScheduleByIdResponses[keyof T.GetScheduleByIdResponses]> {
    return this.transport.request<T.GetScheduleByIdResponses[keyof T.GetScheduleByIdResponses]>({
      method: "GET",
      path: buildPath("/calendars/schedules/{id}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** Update user availability schedule */
  async updateSchedule(params: T.UpdateScheduleData['path'] & T.UpdateScheduleData['body']): Promise<T.UpdateScheduleResponses[keyof T.UpdateScheduleResponses]> {
    return this.transport.request<T.UpdateScheduleResponses[keyof T.UpdateScheduleResponses]>({
      method: "PUT",
      path: buildPath("/calendars/schedules/{id}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Delete user availability schedule */
  async deleteSchedule(params: T.DeleteScheduleData['path']): Promise<T.DeleteScheduleResponses[keyof T.DeleteScheduleResponses]> {
    return this.transport.request<T.DeleteScheduleResponses[keyof T.DeleteScheduleResponses]>({
      method: "DELETE",
      path: buildPath("/calendars/schedules/{id}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** Create user availability schedule */
  async createSchedule(params: T.CreateScheduleData['body']): Promise<T.CreateScheduleResponses[keyof T.CreateScheduleResponses]> {
    return this.transport.request<T.CreateScheduleResponses[keyof T.CreateScheduleResponses]>({
      method: "POST",
      path: "/calendars/schedules",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Apply user availability schedule to a calendar */
  async addCalendarToSchedule(params: T.AddCalendarToScheduleData['path']): Promise<T.AddCalendarToScheduleResponses[keyof T.AddCalendarToScheduleResponses]> {
    return this.transport.request<T.AddCalendarToScheduleResponses[keyof T.AddCalendarToScheduleResponses]>({
      method: "PUT",
      path: buildPath("/calendars/schedules/{id}/associations/{calendarId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** Remove user availability schedule from a calendar */
  async removeCalendarFromSchedule(params: T.RemoveCalendarFromScheduleData['path']): Promise<T.RemoveCalendarFromScheduleResponses[keyof T.RemoveCalendarFromScheduleResponses]> {
    return this.transport.request<T.RemoveCalendarFromScheduleResponses[keyof T.RemoveCalendarFromScheduleResponses]>({
      method: "DELETE",
      path: buildPath("/calendars/schedules/{id}/associations/{calendarId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** Get Calendars */
  async getCalendars(params: T.GetCalendarsData['query']): Promise<T.GetCalendarsResponses[keyof T.GetCalendarsResponses]> {
    return this.transport.request<T.GetCalendarsResponses[keyof T.GetCalendarsResponses]>({
      method: "GET",
      path: "/calendars/",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "groupId": (params as unknown as Record<string, any>)["groupId"],
        "showDrafted": (params as unknown as Record<string, any>)["showDrafted"],
      },
    });
  }

  /** Create Calendar */
  async createCalendar(params: T.CreateCalendarData['body']): Promise<T.CreateCalendarResponses[keyof T.CreateCalendarResponses]> {
    return this.transport.request<T.CreateCalendarResponses[keyof T.CreateCalendarResponses]>({
      method: "POST",
      path: "/calendars/",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }
}
