// AUTO-GENERATED by scripts/generate-resources.ts — do not edit directly.
// Re-run `npm run generate` after updating the specs submodule.
import type { HttpTransport } from '../../http/transport.js';
import { buildPath } from '../shared/build-path.js';
import type * as T from './generated/types.gen.js';

export class UsersResource {
  constructor(private readonly transport: HttpTransport) {}

  /** Search Users */
  async searchUsers(params: T.SearchUsersData['query']): Promise<T.SearchUsersResponses[keyof T.SearchUsersResponses]> {
    return this.transport.request<T.SearchUsersResponses[keyof T.SearchUsersResponses]>({
      method: "GET",
      path: "/users/search",
      securityScheme: "Agency-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "companyId": (params as unknown as Record<string, any>)["companyId"],
        "query": (params as unknown as Record<string, any>)["query"],
        "skip": (params as unknown as Record<string, any>)["skip"],
        "limit": (params as unknown as Record<string, any>)["limit"],
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "type": (params as unknown as Record<string, any>)["type"],
        "role": (params as unknown as Record<string, any>)["role"],
        "ids": (params as unknown as Record<string, any>)["ids"],
        "sort": (params as unknown as Record<string, any>)["sort"],
        "sortDirection": (params as unknown as Record<string, any>)["sortDirection"],
        "enabled2waySync": (params as unknown as Record<string, any>)["enabled2waySync"],
      },
    });
  }

  /** Filter Users by Email */
  async filterUsersByEmail(params: T.FilterUsersByEmailData['body']): Promise<T.FilterUsersByEmailResponses[keyof T.FilterUsersByEmailResponses]> {
    return this.transport.request<T.FilterUsersByEmailResponses[keyof T.FilterUsersByEmailResponses]>({
      method: "POST",
      path: "/users/search/filter-by-email",
      securityScheme: "Agency-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Get User */
  async getUser(params: T.GetUserData['path']): Promise<T.GetUserResponses[keyof T.GetUserResponses]> {
    return this.transport.request<T.GetUserResponses[keyof T.GetUserResponses]>({
      method: "GET",
      path: buildPath("/users/{userId}", params as unknown as Record<string, unknown>),
      securityScheme: "Agency-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** Update User */
  async updateUser(params: T.UpdateUserData['body']): Promise<T.UpdateUserResponses[keyof T.UpdateUserResponses]> {
    return this.transport.request<T.UpdateUserResponses[keyof T.UpdateUserResponses]>({
      method: "PUT",
      path: "/users/{userId}",
      securityScheme: "Agency-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Delete User */
  async deleteUser(): Promise<T.DeleteUserResponses[keyof T.DeleteUserResponses]> {
    return this.transport.request<T.DeleteUserResponses[keyof T.DeleteUserResponses]>({
      method: "DELETE",
      path: "/users/{userId}",
      securityScheme: "Agency-Access",
      locationId: undefined,
      companyId: undefined,
    });
  }

  /** Get User by Location */
  async getUserByLocation(params: T.GetUserByLocationData['query']): Promise<T.GetUserByLocationResponses[keyof T.GetUserByLocationResponses]> {
    return this.transport.request<T.GetUserByLocationResponses[keyof T.GetUserByLocationResponses]>({
      method: "GET",
      path: "/users/",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
      },
    });
  }

  /** Create User */
  async createUser(params: T.CreateUserData['body']): Promise<T.CreateUserResponses[keyof T.CreateUserResponses]> {
    return this.transport.request<T.CreateUserResponses[keyof T.CreateUserResponses]>({
      method: "POST",
      path: "/users/",
      securityScheme: "Agency-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }
}
