// AUTO-GENERATED by scripts/generate-resources.ts — do not edit directly.
// Re-run `npm run generate` after updating the specs submodule.
import type { HttpTransport } from '../../http/transport.js';
import { buildPath } from '../shared/build-path.js';
import type * as T from './generated/types.gen.js';

export class ObjectsResource {
  constructor(private readonly transport: HttpTransport) {}

  /** Get Object Schema by key / id */
  async getObjectSchemaByKey(params: T.GetObjectSchemaByKeyData['path'] & T.GetObjectSchemaByKeyData['query']): Promise<T.GetObjectSchemaByKeyResponses[keyof T.GetObjectSchemaByKeyResponses]> {
    return this.transport.request<T.GetObjectSchemaByKeyResponses[keyof T.GetObjectSchemaByKeyResponses]>({
      method: "GET",
      path: buildPath("/objects/{key}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "fetchProperties": (params as unknown as Record<string, any>)["fetchProperties"],
      },
    });
  }

  /** Update Object Schema By Key / Id */
  async updateCustomObject(params: T.UpdateCustomObjectData['path'] & T.UpdateCustomObjectData['body']): Promise<T.UpdateCustomObjectResponses[keyof T.UpdateCustomObjectResponses]> {
    return this.transport.request<T.UpdateCustomObjectResponses[keyof T.UpdateCustomObjectResponses]>({
      method: "PUT",
      path: buildPath("/objects/{key}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Get Record By Id */
  async getRecordById(params: T.GetRecordByIdData['path']): Promise<T.GetRecordByIdResponses[keyof T.GetRecordByIdResponses]> {
    return this.transport.request<T.GetRecordByIdResponses[keyof T.GetRecordByIdResponses]>({
      method: "GET",
      path: buildPath("/objects/{schemaKey}/records/{id}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** Update Record */
  async updateObjectRecord(params: T.UpdateObjectRecordData['path'] & T.UpdateObjectRecordData['query'] & T.UpdateObjectRecordData['body']): Promise<T.UpdateObjectRecordResponses[keyof T.UpdateObjectRecordResponses]> {
    return this.transport.request<T.UpdateObjectRecordResponses[keyof T.UpdateObjectRecordResponses]>({
      method: "PUT",
      path: buildPath("/objects/{schemaKey}/records/{id}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
      },
      body: params,
    });
  }

  /** Delete Record */
  async deleteObjectRecord(params: T.DeleteObjectRecordData['path']): Promise<T.DeleteObjectRecordResponses[keyof T.DeleteObjectRecordResponses]> {
    return this.transport.request<T.DeleteObjectRecordResponses[keyof T.DeleteObjectRecordResponses]>({
      method: "DELETE",
      path: buildPath("/objects/{schemaKey}/records/{id}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** Create Record */
  async createObjectRecord(params: T.CreateObjectRecordData['path'] & T.CreateObjectRecordData['body']): Promise<T.CreateObjectRecordResponses[keyof T.CreateObjectRecordResponses]> {
    return this.transport.request<T.CreateObjectRecordResponses[keyof T.CreateObjectRecordResponses]>({
      method: "POST",
      path: buildPath("/objects/{schemaKey}/records", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Search Object Records */
  async searchObjectRecords(params: T.SearchObjectRecordsData['path'] & T.SearchObjectRecordsData['body']): Promise<T.SearchObjectRecordsResponses[keyof T.SearchObjectRecordsResponses]> {
    return this.transport.request<T.SearchObjectRecordsResponses[keyof T.SearchObjectRecordsResponses]>({
      method: "POST",
      path: buildPath("/objects/{schemaKey}/records/search", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Get all objects for a location */
  async getObjectByLocationId(params: T.GetObjectByLocationIdData['query']): Promise<T.GetObjectByLocationIdResponses[keyof T.GetObjectByLocationIdResponses]> {
    return this.transport.request<T.GetObjectByLocationIdResponses[keyof T.GetObjectByLocationIdResponses]>({
      method: "GET",
      path: "/objects/",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
      },
    });
  }

  /** Create Custom Object */
  async createCustomObjectSchema(params: T.CreateCustomObjectSchemaData['body']): Promise<T.CreateCustomObjectSchemaResponses[keyof T.CreateCustomObjectSchemaResponses]> {
    return this.transport.request<T.CreateCustomObjectSchemaResponses[keyof T.CreateCustomObjectSchemaResponses]>({
      method: "POST",
      path: "/objects/",
      securityScheme: "Agency-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }
}
