// AUTO-GENERATED by scripts/generate-resources.ts — do not edit directly.
// Re-run `npm run generate` after updating the specs submodule.
import type { HttpTransport } from '../../http/transport.js';
import { buildPath } from '../shared/build-path.js';
import type * as T from './generated/types.gen.js';

export class CustomFieldsResource {
  constructor(private readonly transport: HttpTransport) {}

  /** Get Custom Field / Folder By Id */
  async getCustomFieldById(params: T.GetCustomFieldByIdData['path']): Promise<T.GetCustomFieldByIdResponses[keyof T.GetCustomFieldByIdResponses]> {
    return this.transport.request<T.GetCustomFieldByIdResponses[keyof T.GetCustomFieldByIdResponses]>({
      method: "GET",
      path: buildPath("/custom-fields/{id}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** Update Custom Field By Id */
  async updateCustomField(params: T.UpdateCustomFieldData['path'] & T.UpdateCustomFieldData['body']): Promise<T.UpdateCustomFieldResponses[keyof T.UpdateCustomFieldResponses]> {
    return this.transport.request<T.UpdateCustomFieldResponses[keyof T.UpdateCustomFieldResponses]>({
      method: "PUT",
      path: buildPath("/custom-fields/{id}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Delete Custom Field By Id */
  async deleteCustomField(params: T.DeleteCustomFieldData['path']): Promise<T.DeleteCustomFieldResponses[keyof T.DeleteCustomFieldResponses]> {
    return this.transport.request<T.DeleteCustomFieldResponses[keyof T.DeleteCustomFieldResponses]>({
      method: "DELETE",
      path: buildPath("/custom-fields/{id}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** Get Custom Fields By Object Key */
  async getCustomFieldsByObjectKey(params: T.GetCustomFieldsByObjectKeyData['path'] & T.GetCustomFieldsByObjectKeyData['query']): Promise<T.GetCustomFieldsByObjectKeyResponses[keyof T.GetCustomFieldsByObjectKeyResponses]> {
    return this.transport.request<T.GetCustomFieldsByObjectKeyResponses[keyof T.GetCustomFieldsByObjectKeyResponses]>({
      method: "GET",
      path: buildPath("/custom-fields/object-key/{objectKey}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
      },
    });
  }

  /** Create Custom Field Folder */
  async createCustomFieldFolder(params: T.CreateCustomFieldFolderData['body']): Promise<T.CreateCustomFieldFolderResponses[keyof T.CreateCustomFieldFolderResponses]> {
    return this.transport.request<T.CreateCustomFieldFolderResponses[keyof T.CreateCustomFieldFolderResponses]>({
      method: "POST",
      path: "/custom-fields/folder",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Update Custom Field Folder Name */
  async updateCustomFieldFolder(params: T.UpdateCustomFieldFolderData['path'] & T.UpdateCustomFieldFolderData['body']): Promise<T.UpdateCustomFieldFolderResponses[keyof T.UpdateCustomFieldFolderResponses]> {
    return this.transport.request<T.UpdateCustomFieldFolderResponses[keyof T.UpdateCustomFieldFolderResponses]>({
      method: "PUT",
      path: buildPath("/custom-fields/folder/{id}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Delete Custom Field Folder */
  async deleteCustomFieldFolder(params: T.DeleteCustomFieldFolderData['path'] & T.DeleteCustomFieldFolderData['query']): Promise<T.DeleteCustomFieldFolderResponses[keyof T.DeleteCustomFieldFolderResponses]> {
    return this.transport.request<T.DeleteCustomFieldFolderResponses[keyof T.DeleteCustomFieldFolderResponses]>({
      method: "DELETE",
      path: buildPath("/custom-fields/folder/{id}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
      },
    });
  }

  /** Create Custom Field */
  async createCustomField(params: T.CreateCustomFieldData['body']): Promise<T.CreateCustomFieldResponses[keyof T.CreateCustomFieldResponses]> {
    return this.transport.request<T.CreateCustomFieldResponses[keyof T.CreateCustomFieldResponses]>({
      method: "POST",
      path: "/custom-fields/",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }
}
