// AUTO-GENERATED by scripts/generate-resources.ts — do not edit directly.
// Re-run `npm run generate` after updating the specs submodule.
import type { HttpTransport } from '../../http/transport.js';
import { buildPath } from '../shared/build-path.js';
import type * as T from './generated/types.gen.js';

export class ProductsResource {
  constructor(private readonly transport: HttpTransport) {}

  /** Bulk Update Products */
  async bulkUpdate(params: T.BulkUpdateData['body']): Promise<T.BulkUpdateResponses[keyof T.BulkUpdateResponses]> {
    return this.transport.request<T.BulkUpdateResponses[keyof T.BulkUpdateResponses]>({
      method: "POST",
      path: "/products/bulk-update",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Bulk Edit Products and Prices */
  async bulkEdit(params: T.BulkEditData['body']): Promise<T.BulkEditResponses[keyof T.BulkEditResponses]> {
    return this.transport.request<T.BulkEditResponses[keyof T.BulkEditResponses]>({
      method: "POST",
      path: "/products/bulk-update/edit",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** List Prices for a Product */
  async listPricesForProduct(params: T.ListPricesForProductData['path'] & T.ListPricesForProductData['query']): Promise<T.ListPricesForProductResponses[keyof T.ListPricesForProductResponses]> {
    return this.transport.request<T.ListPricesForProductResponses[keyof T.ListPricesForProductResponses]>({
      method: "GET",
      path: buildPath("/products/{productId}/price", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "limit": (params as unknown as Record<string, any>)["limit"],
        "offset": (params as unknown as Record<string, any>)["offset"],
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "ids": (params as unknown as Record<string, any>)["ids"],
      },
    });
  }

  /** Create Price for a Product */
  async createPriceForProduct(params: T.CreatePriceForProductData['path'] & T.CreatePriceForProductData['body']): Promise<T.CreatePriceForProductResponses[keyof T.CreatePriceForProductResponses]> {
    return this.transport.request<T.CreatePriceForProductResponses[keyof T.CreatePriceForProductResponses]>({
      method: "POST",
      path: buildPath("/products/{productId}/price", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** List Inventory */
  async getListInventory(params: T.GetListInventoryData['query']): Promise<T.GetListInventoryResponses[keyof T.GetListInventoryResponses]> {
    return this.transport.request<T.GetListInventoryResponses[keyof T.GetListInventoryResponses]>({
      method: "GET",
      path: "/products/inventory",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "limit": (params as unknown as Record<string, any>)["limit"],
        "offset": (params as unknown as Record<string, any>)["offset"],
        "altId": (params as unknown as Record<string, any>)["altId"],
        "altType": (params as unknown as Record<string, any>)["altType"],
        "search": (params as unknown as Record<string, any>)["search"],
      },
    });
  }

  /** Update Inventory */
  async updateInventory(params: T.UpdateInventoryData['body']): Promise<T.UpdateInventoryResponses[keyof T.UpdateInventoryResponses]> {
    return this.transport.request<T.UpdateInventoryResponses[keyof T.UpdateInventoryResponses]>({
      method: "POST",
      path: "/products/inventory",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Get Price by ID for a Product */
  async getPriceByIdForProduct(params: T.GetPriceByIdForProductData['path'] & T.GetPriceByIdForProductData['query']): Promise<T.GetPriceByIdForProductResponses[keyof T.GetPriceByIdForProductResponses]> {
    return this.transport.request<T.GetPriceByIdForProductResponses[keyof T.GetPriceByIdForProductResponses]>({
      method: "GET",
      path: buildPath("/products/{productId}/price/{priceId}", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
      },
    });
  }

  /** Update Price by ID for a Product */
  async updatePriceByIdForProduct(params: T.UpdatePriceByIdForProductData['path'] & T.UpdatePriceByIdForProductData['body']): Promise<T.UpdatePriceByIdForProductResponses[keyof T.UpdatePriceByIdForProductResponses]> {
    return this.transport.request<T.UpdatePriceByIdForProductResponses[keyof T.UpdatePriceByIdForProductResponses]>({
      method: "PUT",
      path: buildPath("/products/{productId}/price/{priceId}", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Delete Price by ID for a Product */
  async deletePriceByIdForProduct(params: T.DeletePriceByIdForProductData['path'] & T.DeletePriceByIdForProductData['query']): Promise<T.DeletePriceByIdForProductResponses[keyof T.DeletePriceByIdForProductResponses]> {
    return this.transport.request<T.DeletePriceByIdForProductResponses[keyof T.DeletePriceByIdForProductResponses]>({
      method: "DELETE",
      path: buildPath("/products/{productId}/price/{priceId}", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
      },
    });
  }

  /** Fetch Product Store Stats */
  async getProductStoreStats(params: T.GetProductStoreStatsData['path'] & T.GetProductStoreStatsData['query']): Promise<T.GetProductStoreStatsResponses[keyof T.GetProductStoreStatsResponses]> {
    return this.transport.request<T.GetProductStoreStatsResponses[keyof T.GetProductStoreStatsResponses]>({
      method: "GET",
      path: buildPath("/products/store/{storeId}/stats", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "altId": (params as unknown as Record<string, any>)["altId"],
        "altType": (params as unknown as Record<string, any>)["altType"],
        "search": (params as unknown as Record<string, any>)["search"],
        "collectionIds": (params as unknown as Record<string, any>)["collectionIds"],
      },
    });
  }

  /** Action to include/exclude the product in store */
  async updateStoreStatus(params: T.UpdateStoreStatusData['path'] & T.UpdateStoreStatusData['body']): Promise<T.UpdateStoreStatusResponses[keyof T.UpdateStoreStatusResponses]> {
    return this.transport.request<T.UpdateStoreStatusResponses[keyof T.UpdateStoreStatusResponses]>({
      method: "POST",
      path: buildPath("/products/store/{storeId}", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Update product display priorities in store */
  async updateDisplayPriority(params: T.UpdateDisplayPriorityData['path'] & T.UpdateDisplayPriorityData['body']): Promise<void> {
    return this.transport.request<void>({
      method: "POST",
      path: buildPath("/products/store/{storeId}/priority", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Fetch Product Collections */
  async getProductCollection(params: T.GetProductCollectionData['query']): Promise<T.GetProductCollectionResponses[keyof T.GetProductCollectionResponses]> {
    return this.transport.request<T.GetProductCollectionResponses[keyof T.GetProductCollectionResponses]>({
      method: "GET",
      path: "/products/collections",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "limit": (params as unknown as Record<string, any>)["limit"],
        "offset": (params as unknown as Record<string, any>)["offset"],
        "altId": (params as unknown as Record<string, any>)["altId"],
        "altType": (params as unknown as Record<string, any>)["altType"],
        "collectionIds": (params as unknown as Record<string, any>)["collectionIds"],
        "name": (params as unknown as Record<string, any>)["name"],
      },
    });
  }

  /** Create Product Collection */
  async createProductCollection(params: T.CreateProductCollectionData['body']): Promise<T.CreateProductCollectionResponses[keyof T.CreateProductCollectionResponses]> {
    return this.transport.request<T.CreateProductCollectionResponses[keyof T.CreateProductCollectionResponses]>({
      method: "POST",
      path: "/products/collections",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Get Details about individual product collection */
  async getProductCollectionId(params: T.GetProductCollectionIdData['path'] & T.GetProductCollectionIdData['query']): Promise<T.GetProductCollectionIdResponses[keyof T.GetProductCollectionIdResponses]> {
    return this.transport.request<T.GetProductCollectionIdResponses[keyof T.GetProductCollectionIdResponses]>({
      method: "GET",
      path: buildPath("/products/collections/{collectionId}", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "altId": (params as unknown as Record<string, any>)["altId"],
      },
    });
  }

  /** Update Product Collection */
  async updateProductCollection(params: T.UpdateProductCollectionData['path'] & T.UpdateProductCollectionData['body']): Promise<T.UpdateProductCollectionResponses[keyof T.UpdateProductCollectionResponses]> {
    return this.transport.request<T.UpdateProductCollectionResponses[keyof T.UpdateProductCollectionResponses]>({
      method: "PUT",
      path: buildPath("/products/collections/{collectionId}", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Delete Product Collection */
  async deleteProductCollection(params: T.DeleteProductCollectionData['path'] & T.DeleteProductCollectionData['query']): Promise<T.DeleteProductCollectionResponses[keyof T.DeleteProductCollectionResponses]> {
    return this.transport.request<T.DeleteProductCollectionResponses[keyof T.DeleteProductCollectionResponses]>({
      method: "DELETE",
      path: buildPath("/products/collections/{collectionId}", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "altId": (params as unknown as Record<string, any>)["altId"],
        "altType": (params as unknown as Record<string, any>)["altType"],
      },
    });
  }

  /** Fetch Product Reviews */
  async getProductReviews(params: T.GetProductReviewsData['query']): Promise<T.GetProductReviewsResponses[keyof T.GetProductReviewsResponses]> {
    return this.transport.request<T.GetProductReviewsResponses[keyof T.GetProductReviewsResponses]>({
      method: "GET",
      path: "/products/reviews",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "altId": (params as unknown as Record<string, any>)["altId"],
        "altType": (params as unknown as Record<string, any>)["altType"],
        "limit": (params as unknown as Record<string, any>)["limit"],
        "offset": (params as unknown as Record<string, any>)["offset"],
        "sortField": (params as unknown as Record<string, any>)["sortField"],
        "sortOrder": (params as unknown as Record<string, any>)["sortOrder"],
        "rating": (params as unknown as Record<string, any>)["rating"],
        "startDate": (params as unknown as Record<string, any>)["startDate"],
        "endDate": (params as unknown as Record<string, any>)["endDate"],
        "productId": (params as unknown as Record<string, any>)["productId"],
        "storeId": (params as unknown as Record<string, any>)["storeId"],
      },
    });
  }

  /** Fetch Review Count as per status */
  async getReviewsCount(params: T.GetReviewsCountData['query']): Promise<T.GetReviewsCountResponses[keyof T.GetReviewsCountResponses]> {
    return this.transport.request<T.GetReviewsCountResponses[keyof T.GetReviewsCountResponses]>({
      method: "GET",
      path: "/products/reviews/count",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "altId": (params as unknown as Record<string, any>)["altId"],
        "altType": (params as unknown as Record<string, any>)["altType"],
        "rating": (params as unknown as Record<string, any>)["rating"],
        "startDate": (params as unknown as Record<string, any>)["startDate"],
        "endDate": (params as unknown as Record<string, any>)["endDate"],
        "productId": (params as unknown as Record<string, any>)["productId"],
        "storeId": (params as unknown as Record<string, any>)["storeId"],
      },
    });
  }

  /** Update Product Reviews */
  async updateProductReview(params: T.UpdateProductReviewData['path'] & T.UpdateProductReviewData['body']): Promise<T.UpdateProductReviewResponses[keyof T.UpdateProductReviewResponses]> {
    return this.transport.request<T.UpdateProductReviewResponses[keyof T.UpdateProductReviewResponses]>({
      method: "PUT",
      path: buildPath("/products/reviews/{reviewId}", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Delete Product Review */
  async deleteProductReview(params: T.DeleteProductReviewData['path'] & T.DeleteProductReviewData['query']): Promise<T.DeleteProductReviewResponses[keyof T.DeleteProductReviewResponses]> {
    return this.transport.request<T.DeleteProductReviewResponses[keyof T.DeleteProductReviewResponses]>({
      method: "DELETE",
      path: buildPath("/products/reviews/{reviewId}", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "altId": (params as unknown as Record<string, any>)["altId"],
        "altType": (params as unknown as Record<string, any>)["altType"],
        "productId": (params as unknown as Record<string, any>)["productId"],
      },
    });
  }

  /** Update Product Reviews */
  async bulkUpdateProductReview(params: T.BulkUpdateProductReviewData['body']): Promise<T.BulkUpdateProductReviewResponses[keyof T.BulkUpdateProductReviewResponses]> {
    return this.transport.request<T.BulkUpdateProductReviewResponses[keyof T.BulkUpdateProductReviewResponses]>({
      method: "POST",
      path: "/products/reviews/bulk-update",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Get Product by ID */
  async getProductById(params: T.GetProductByIdData['path'] & T.GetProductByIdData['query']): Promise<T.GetProductByIdResponses[keyof T.GetProductByIdResponses]> {
    return this.transport.request<T.GetProductByIdResponses[keyof T.GetProductByIdResponses]>({
      method: "GET",
      path: buildPath("/products/{productId}", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "sendWishlistStatus": (params as unknown as Record<string, any>)["sendWishlistStatus"],
      },
    });
  }

  /** Update Product by ID */
  async updateProductById(params: T.UpdateProductByIdData['path'] & T.UpdateProductByIdData['body']): Promise<T.UpdateProductByIdResponses[keyof T.UpdateProductByIdResponses]> {
    return this.transport.request<T.UpdateProductByIdResponses[keyof T.UpdateProductByIdResponses]>({
      method: "PUT",
      path: buildPath("/products/{productId}", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Delete Product by ID */
  async deleteProductById(params: T.DeleteProductByIdData['path'] & T.DeleteProductByIdData['query']): Promise<T.DeleteProductByIdResponses[keyof T.DeleteProductByIdResponses]> {
    return this.transport.request<T.DeleteProductByIdResponses[keyof T.DeleteProductByIdResponses]>({
      method: "DELETE",
      path: buildPath("/products/{productId}", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "sendWishlistStatus": (params as unknown as Record<string, any>)["sendWishlistStatus"],
      },
    });
  }

  /** List Products */
  async listInvoices(params: T.ListInvoicesData['query']): Promise<T.ListInvoicesResponses[keyof T.ListInvoicesResponses]> {
    return this.transport.request<T.ListInvoicesResponses[keyof T.ListInvoicesResponses]>({
      method: "GET",
      path: "/products/",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "limit": (params as unknown as Record<string, any>)["limit"],
        "offset": (params as unknown as Record<string, any>)["offset"],
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "search": (params as unknown as Record<string, any>)["search"],
        "collectionIds": (params as unknown as Record<string, any>)["collectionIds"],
        "collectionSlug": (params as unknown as Record<string, any>)["collectionSlug"],
        "expand": (params as unknown as Record<string, any>)["expand"],
        "productIds": (params as unknown as Record<string, any>)["productIds"],
        "storeId": (params as unknown as Record<string, any>)["storeId"],
        "includedInStore": (params as unknown as Record<string, any>)["includedInStore"],
        "availableInStore": (params as unknown as Record<string, any>)["availableInStore"],
        "sortOrder": (params as unknown as Record<string, any>)["sortOrder"],
      },
    });
  }

  /** Create Product */
  async createProduct(params: T.CreateProductData['body']): Promise<T.CreateProductResponses[keyof T.CreateProductResponses]> {
    return this.transport.request<T.CreateProductResponses[keyof T.CreateProductResponses]>({
      method: "POST",
      path: "/products/",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }
}
