// AUTO-GENERATED by scripts/generate-resources.ts — do not edit directly.
// Re-run `npm run generate` after updating the specs submodule.
import type { HttpTransport } from '../../http/transport.js';
import type * as T from './generated/types.gen.js';

export class ProposalsResource {
  constructor(private readonly transport: HttpTransport) {}

  /** List documents */
  async listDocumentsContracts(params: T.ListDocumentsContractsData['query']): Promise<T.ListDocumentsContractsResponses[keyof T.ListDocumentsContractsResponses]> {
    return this.transport.request<T.ListDocumentsContractsResponses[keyof T.ListDocumentsContractsResponses]>({
      method: "GET",
      path: "/proposals/document",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "status": (params as unknown as Record<string, any>)["status"],
        "paymentStatus": (params as unknown as Record<string, any>)["paymentStatus"],
        "limit": (params as unknown as Record<string, any>)["limit"],
        "skip": (params as unknown as Record<string, any>)["skip"],
        "query": (params as unknown as Record<string, any>)["query"],
        "dateFrom": (params as unknown as Record<string, any>)["dateFrom"],
        "dateTo": (params as unknown as Record<string, any>)["dateTo"],
      },
    });
  }

  /** Send document */
  async sendDocumentsContracts(params: T.SendDocumentsContractsData['body']): Promise<T.SendDocumentsContractsResponses[keyof T.SendDocumentsContractsResponses]> {
    return this.transport.request<T.SendDocumentsContractsResponses[keyof T.SendDocumentsContractsResponses]>({
      method: "POST",
      path: "/proposals/document/send",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** List templates */
  async listDocumentsContractsTemplates(params: T.ListDocumentsContractsTemplatesData['query']): Promise<T.ListDocumentsContractsTemplatesResponses[keyof T.ListDocumentsContractsTemplatesResponses]> {
    return this.transport.request<T.ListDocumentsContractsTemplatesResponses[keyof T.ListDocumentsContractsTemplatesResponses]>({
      method: "GET",
      path: "/proposals/templates",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "dateFrom": (params as unknown as Record<string, any>)["dateFrom"],
        "dateTo": (params as unknown as Record<string, any>)["dateTo"],
        "type": (params as unknown as Record<string, any>)["type"],
        "name": (params as unknown as Record<string, any>)["name"],
        "isPublicDocument": (params as unknown as Record<string, any>)["isPublicDocument"],
        "userId": (params as unknown as Record<string, any>)["userId"],
        "limit": (params as unknown as Record<string, any>)["limit"],
        "skip": (params as unknown as Record<string, any>)["skip"],
      },
    });
  }

  /** Send template */
  async sendDocumentsContractsTemplate(params: T.SendDocumentsContractsTemplateData['body']): Promise<T.SendDocumentsContractsTemplateResponses[keyof T.SendDocumentsContractsTemplateResponses]> {
    return this.transport.request<T.SendDocumentsContractsTemplateResponses[keyof T.SendDocumentsContractsTemplateResponses]>({
      method: "POST",
      path: "/proposals/templates/send",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }
}
