// AUTO-GENERATED by scripts/generate-resources.ts — do not edit directly.
// Re-run `npm run generate` after updating the specs submodule.
import type { HttpTransport } from '../../http/transport.js';
import { buildPath } from '../shared/build-path.js';
import type * as T from './generated/types.gen.js';

export class MarketplaceResource {
  constructor(private readonly transport: HttpTransport) {}

  /** Get all wallet charges */
  async getCharges(params: T.GetChargesData['query']): Promise<T.GetChargesResponses[keyof T.GetChargesResponses]> {
    return this.transport.request<T.GetChargesResponses[keyof T.GetChargesResponses]>({
      method: "GET",
      path: "/marketplace/billing/charges",
      securityScheme: "Location-Access-Only",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "meterId": (params as unknown as Record<string, any>)["meterId"],
        "eventId": (params as unknown as Record<string, any>)["eventId"],
        "userId": (params as unknown as Record<string, any>)["userId"],
        "startDate": (params as unknown as Record<string, any>)["startDate"],
        "endDate": (params as unknown as Record<string, any>)["endDate"],
        "skip": (params as unknown as Record<string, any>)["skip"],
        "limit": (params as unknown as Record<string, any>)["limit"],
      },
    });
  }

  /** Create a new wallet charge */
  async charge(params: T.ChargeData['body']): Promise<T.ChargeResponses[keyof T.ChargeResponses]> {
    return this.transport.request<T.ChargeResponses[keyof T.ChargeResponses]>({
      method: "POST",
      path: "/marketplace/billing/charges",
      securityScheme: "Location-Access-Only",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Get specific wallet charge details */
  async getSpecificCharge(params: T.GetSpecificChargeData['path']): Promise<T.GetSpecificChargeResponses[keyof T.GetSpecificChargeResponses]> {
    return this.transport.request<T.GetSpecificChargeResponses[keyof T.GetSpecificChargeResponses]>({
      method: "GET",
      path: buildPath("/marketplace/billing/charges/{chargeId}", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access-Only",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** Delete a wallet charge */
  async deleteCharge(params: T.DeleteChargeData['path']): Promise<T.DeleteChargeResponses[keyof T.DeleteChargeResponses]> {
    return this.transport.request<T.DeleteChargeResponses[keyof T.DeleteChargeResponses]>({
      method: "DELETE",
      path: buildPath("/marketplace/billing/charges/{chargeId}", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access-Only",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** Check if account has sufficient funds */
  async hasFunds(): Promise<T.HasFundsResponses[keyof T.HasFundsResponses]> {
    return this.transport.request<T.HasFundsResponses[keyof T.HasFundsResponses]>({
      method: "GET",
      path: "/marketplace/billing/charges/has-funds",
      securityScheme: "Location-Access-Only",
      locationId: undefined,
      companyId: undefined,
    });
  }

  /** Get Installer Details */
  async getInstallerDetails(params: T.GetInstallerDetailsData['path']): Promise<T.GetInstallerDetailsResponses[keyof T.GetInstallerDetailsResponses]> {
    return this.transport.request<T.GetInstallerDetailsResponses[keyof T.GetInstallerDetailsResponses]>({
      method: "GET",
      path: buildPath("/marketplace/app/{appId}/installations", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access-Only",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** Uninstall an application */
  async uninstallApplication(params: T.UninstallApplicationData['path'] & T.UninstallApplicationData['body']): Promise<T.UninstallApplicationResponses[keyof T.UninstallApplicationResponses]> {
    return this.transport.request<T.UninstallApplicationResponses[keyof T.UninstallApplicationResponses]>({
      method: "DELETE",
      path: buildPath("/marketplace/app/{appId}/installations", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access-Only",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Get rebilling config for an app subscription and usage plans */
  async getRebillingConfigForApp(params: T.GetRebillingConfigForAppData['path']): Promise<T.GetRebillingConfigForAppResponses[keyof T.GetRebillingConfigForAppResponses]> {
    return this.transport.request<T.GetRebillingConfigForAppResponses[keyof T.GetRebillingConfigForAppResponses]>({
      method: "GET",
      path: buildPath("/marketplace/app/{appId}/rebilling-config/location/{locationId}", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access-Only",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** Migrate external authentication connection */
  async migrateConnection(params: T.MigrateConnectionData['body']): Promise<T.MigrateConnectionResponses[keyof T.MigrateConnectionResponses]> {
    return this.transport.request<T.MigrateConnectionResponses[keyof T.MigrateConnectionResponses]>({
      method: "POST",
      path: "/marketplace/external-auth/migration",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }
}
