// AUTO-GENERATED by scripts/generate-resources.ts — do not edit directly.
// Re-run `npm run generate` after updating the specs submodule.
import type { HttpTransport } from '../../http/transport.js';
import { buildPath } from '../shared/build-path.js';
import type * as T from './generated/types.gen.js';

export class LinksResource {
  constructor(private readonly transport: HttpTransport) {}

  /** Get Link by ID */
  async getLinkById(params: T.GetLinkByIdData['path'] & T.GetLinkByIdData['query']): Promise<T.GetLinkByIdResponses[keyof T.GetLinkByIdResponses]> {
    return this.transport.request<T.GetLinkByIdResponses[keyof T.GetLinkByIdResponses]>({
      method: "GET",
      path: buildPath("/links/id/{linkId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
      },
    });
  }

  /** Update Link */
  async updateLink(params: T.UpdateLinkData['path'] & T.UpdateLinkData['body']): Promise<T.UpdateLinkResponses[keyof T.UpdateLinkResponses]> {
    return this.transport.request<T.UpdateLinkResponses[keyof T.UpdateLinkResponses]>({
      method: "PUT",
      path: buildPath("/links/{linkId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Delete Link */
  async deleteLink(params: T.DeleteLinkData['path']): Promise<T.DeleteLinkResponses[keyof T.DeleteLinkResponses]> {
    return this.transport.request<T.DeleteLinkResponses[keyof T.DeleteLinkResponses]>({
      method: "DELETE",
      path: buildPath("/links/{linkId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** Search Trigger Links */
  async searchTriggerLinks(params: T.SearchTriggerLinksData['query']): Promise<T.SearchTriggerLinksResponses[keyof T.SearchTriggerLinksResponses]> {
    return this.transport.request<T.SearchTriggerLinksResponses[keyof T.SearchTriggerLinksResponses]>({
      method: "GET",
      path: "/links/search",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "query": (params as unknown as Record<string, any>)["query"],
        "skip": (params as unknown as Record<string, any>)["skip"],
        "limit": (params as unknown as Record<string, any>)["limit"],
      },
    });
  }

  /** Get Links */
  async getLinks(params: T.GetLinksData['query']): Promise<T.GetLinksResponses[keyof T.GetLinksResponses]> {
    return this.transport.request<T.GetLinksResponses[keyof T.GetLinksResponses]>({
      method: "GET",
      path: "/links/",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
      },
    });
  }

  /** Create Link */
  async createLink(params: T.CreateLinkData['body']): Promise<T.CreateLinkResponses[keyof T.CreateLinkResponses]> {
    return this.transport.request<T.CreateLinkResponses[keyof T.CreateLinkResponses]>({
      method: "POST",
      path: "/links/",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }
}
