// AUTO-GENERATED by scripts/generate-resources.ts — do not edit directly.
// Re-run `npm run generate` after updating the specs submodule.
import type { HttpTransport } from '../../http/transport.js';
import { buildPath } from '../shared/build-path.js';
import type * as T from './generated/types.gen.js';

export class AssociationsResource {
  constructor(private readonly transport: HttpTransport) {}

  /** Create Relation for you associated entities. */
  async createRelation(params: T.CreateRelationData['body']): Promise<T.CreateRelationResponses[keyof T.CreateRelationResponses]> {
    return this.transport.request<T.CreateRelationResponses[keyof T.CreateRelationResponses]>({
      method: "POST",
      path: "/associations/relations",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Get all relations By record Id */
  async getRelationsByRecordId(params: T.GetRelationsByRecordIdData['path'] & T.GetRelationsByRecordIdData['query']): Promise<T.GetRelationsByRecordIdResponses[keyof T.GetRelationsByRecordIdResponses]> {
    return this.transport.request<T.GetRelationsByRecordIdResponses[keyof T.GetRelationsByRecordIdResponses]>({
      method: "GET",
      path: buildPath("/associations/relations/{recordId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "skip": (params as unknown as Record<string, any>)["skip"],
        "limit": (params as unknown as Record<string, any>)["limit"],
        "associationIds": (params as unknown as Record<string, any>)["associationIds"],
      },
    });
  }

  /** Delete Relation */
  async deleteRelation(params: T.DeleteRelationData['path'] & T.DeleteRelationData['query']): Promise<T.DeleteRelationResponses[keyof T.DeleteRelationResponses]> {
    return this.transport.request<T.DeleteRelationResponses[keyof T.DeleteRelationResponses]>({
      method: "DELETE",
      path: buildPath("/associations/relations/{relationId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
      },
    });
  }

  /** Get association key by key name */
  async getAssociationKeyByKeyName(params: T.GetAssociationKeyByKeyNameData['path'] & T.GetAssociationKeyByKeyNameData['query']): Promise<T.GetAssociationKeyByKeyNameResponses[keyof T.GetAssociationKeyByKeyNameResponses]> {
    return this.transport.request<T.GetAssociationKeyByKeyNameResponses[keyof T.GetAssociationKeyByKeyNameResponses]>({
      method: "GET",
      path: buildPath("/associations/key/{key_name}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
      },
    });
  }

  /** Get association by object keys */
  async getAssociationByObjectKeys(params: T.GetAssociationByObjectKeysData['path'] & T.GetAssociationByObjectKeysData['query']): Promise<T.GetAssociationByObjectKeysResponses[keyof T.GetAssociationByObjectKeysResponses]> {
    return this.transport.request<T.GetAssociationByObjectKeysResponses[keyof T.GetAssociationByObjectKeysResponses]>({
      method: "GET",
      path: buildPath("/associations/objectKey/{objectKey}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
      },
    });
  }

  /** Get association by ID */
  async getAssociationByID(params: T.GetAssociationByIdData['path']): Promise<T.GetAssociationByIdResponses[keyof T.GetAssociationByIdResponses]> {
    return this.transport.request<T.GetAssociationByIdResponses[keyof T.GetAssociationByIdResponses]>({
      method: "GET",
      path: buildPath("/associations/{associationId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** Update Association By Id */
  async updateAssociation(params: T.UpdateAssociationData['path'] & T.UpdateAssociationData['body']): Promise<T.UpdateAssociationResponses[keyof T.UpdateAssociationResponses]> {
    return this.transport.request<T.UpdateAssociationResponses[keyof T.UpdateAssociationResponses]>({
      method: "PUT",
      path: buildPath("/associations/{associationId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Delete Association */
  async deleteAssociation(params: T.DeleteAssociationData['path']): Promise<T.DeleteAssociationResponses[keyof T.DeleteAssociationResponses]> {
    return this.transport.request<T.DeleteAssociationResponses[keyof T.DeleteAssociationResponses]>({
      method: "DELETE",
      path: buildPath("/associations/{associationId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** Get all associations for a sub-account / location */
  async findAssociations(params: T.FindAssociationsData['query']): Promise<T.FindAssociationsResponses[keyof T.FindAssociationsResponses]> {
    return this.transport.request<T.FindAssociationsResponses[keyof T.FindAssociationsResponses]>({
      method: "GET",
      path: "/associations/",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "skip": (params as unknown as Record<string, any>)["skip"],
        "limit": (params as unknown as Record<string, any>)["limit"],
      },
    });
  }

  /** Create Association */
  async createAssociation(params: T.CreateAssociationData['body']): Promise<T.CreateAssociationResponses[keyof T.CreateAssociationResponses]> {
    return this.transport.request<T.CreateAssociationResponses[keyof T.CreateAssociationResponses]>({
      method: "POST",
      path: "/associations/",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }
}
