// AUTO-GENERATED by scripts/generate-resources.ts — do not edit directly.
// Re-run `npm run generate` after updating the specs submodule.
import type { HttpTransport } from '../../http/transport.js';
import { buildPath } from '../shared/build-path.js';
import type * as T from './generated/types.gen.js';

export class ConversationAiResource {
  constructor(private readonly transport: HttpTransport) {}

  /** Attach Action to Agent */
  async createAction(params: T.CreateActionData['path'] & T.CreateActionData['body']): Promise<T.CreateActionResponses[keyof T.CreateActionResponses]> {
    return this.transport.request<T.CreateActionResponses[keyof T.CreateActionResponses]>({
      method: "POST",
      path: buildPath("/conversation-ai/agents/{agentId}/actions", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** List Actions for an Agent */
  async listActions(params: T.ListActionsData['path']): Promise<T.ListActionsResponses[keyof T.ListActionsResponses]> {
    return this.transport.request<T.ListActionsResponses[keyof T.ListActionsResponses]>({
      method: "GET",
      path: buildPath("/conversation-ai/agents/{agentId}/actions/list", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** Get Action by ID */
  async getActionById(params: T.GetActionByIdData['path']): Promise<T.GetActionByIdResponses[keyof T.GetActionByIdResponses]> {
    return this.transport.request<T.GetActionByIdResponses[keyof T.GetActionByIdResponses]>({
      method: "GET",
      path: buildPath("/conversation-ai/agents/{agentId}/actions/{actionId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** Update Action */
  async updateAction(params: T.UpdateActionData['path'] & T.UpdateActionData['body']): Promise<T.UpdateActionResponses[keyof T.UpdateActionResponses]> {
    return this.transport.request<T.UpdateActionResponses[keyof T.UpdateActionResponses]>({
      method: "PUT",
      path: buildPath("/conversation-ai/agents/{agentId}/actions/{actionId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Remove Action from Agent */
  async deleteAction(params: T.DeleteActionData['path']): Promise<T.DeleteActionResponses[keyof T.DeleteActionResponses]> {
    return this.transport.request<T.DeleteActionResponses[keyof T.DeleteActionResponses]>({
      method: "DELETE",
      path: buildPath("/conversation-ai/agents/{agentId}/actions/{actionId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** Update Followup Settings */
  async updateFollowupSettings(params: T.UpdateFollowupSettingsData['path'] & T.UpdateFollowupSettingsData['body']): Promise<T.UpdateFollowupSettingsResponses[keyof T.UpdateFollowupSettingsResponses]> {
    return this.transport.request<T.UpdateFollowupSettingsResponses[keyof T.UpdateFollowupSettingsResponses]>({
      method: "PATCH",
      path: buildPath("/conversation-ai/agents/{agentId}/followup-settings", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Create an Agent */
  async createAgent(params: T.CreateAgentData['body']): Promise<T.CreateAgentResponses[keyof T.CreateAgentResponses]> {
    return this.transport.request<T.CreateAgentResponses[keyof T.CreateAgentResponses]>({
      method: "POST",
      path: "/conversation-ai/agents",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Search Agents */
  async searchAgent(params: T.SearchAgentData['query']): Promise<T.SearchAgentResponses[keyof T.SearchAgentResponses]> {
    return this.transport.request<T.SearchAgentResponses[keyof T.SearchAgentResponses]>({
      method: "GET",
      path: "/conversation-ai/agents/search",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "startAfter": (params as unknown as Record<string, any>)["startAfter"],
        "limit": (params as unknown as Record<string, any>)["limit"],
        "query": (params as unknown as Record<string, any>)["query"],
      },
    });
  }

  /** Get Agent */
  async getAgent(params: T.GetAgentData['path']): Promise<T.GetAgentResponses[keyof T.GetAgentResponses]> {
    return this.transport.request<T.GetAgentResponses[keyof T.GetAgentResponses]>({
      method: "GET",
      path: buildPath("/conversation-ai/agents/{agentId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** Update Agent */
  async updateAgent(params: T.UpdateAgentData['path'] & T.UpdateAgentData['body']): Promise<T.UpdateAgentResponses[keyof T.UpdateAgentResponses]> {
    return this.transport.request<T.UpdateAgentResponses[keyof T.UpdateAgentResponses]>({
      method: "PUT",
      path: buildPath("/conversation-ai/agents/{agentId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Delete Agent */
  async deleteAgent(params: T.DeleteAgentData['path']): Promise<T.DeleteAgentResponses[keyof T.DeleteAgentResponses]> {
    return this.transport.request<T.DeleteAgentResponses[keyof T.DeleteAgentResponses]>({
      method: "DELETE",
      path: buildPath("/conversation-ai/agents/{agentId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** Get the generation details */
  async getGenerationDetails(params: T.GetGenerationDetailsData['query']): Promise<T.GetGenerationDetailsResponses[keyof T.GetGenerationDetailsResponses]> {
    return this.transport.request<T.GetGenerationDetailsResponses[keyof T.GetGenerationDetailsResponses]>({
      method: "GET",
      path: "/conversation-ai/generations",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "messageId": (params as unknown as Record<string, any>)["messageId"],
        "source": (params as unknown as Record<string, any>)["source"],
      },
    });
  }
}
