// AUTO-GENERATED by scripts/generate-resources.ts — do not edit directly.
// Re-run `npm run generate` after updating the specs submodule.
import type { HttpTransport } from '../../http/transport.js';
import { buildPath } from '../shared/build-path.js';
import type * as T from './generated/types.gen.js';

export class PaymentsResource {
  constructor(private readonly transport: HttpTransport) {}

  /** List White-label Integration Providers */
  async listIntegrationProviders(params: T.ListIntegrationProvidersData['query']): Promise<T.ListIntegrationProvidersResponses[keyof T.ListIntegrationProvidersResponses]> {
    return this.transport.request<T.ListIntegrationProvidersResponses[keyof T.ListIntegrationProvidersResponses]>({
      method: "GET",
      path: "/payments/integrations/provider/whitelabel",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "altId": (params as unknown as Record<string, any>)["altId"],
        "altType": (params as unknown as Record<string, any>)["altType"],
        "limit": (params as unknown as Record<string, any>)["limit"],
        "offset": (params as unknown as Record<string, any>)["offset"],
      },
    });
  }

  /** Create White-label Integration Provider */
  async createIntegrationProvider(params: T.CreateIntegrationProviderData['body']): Promise<T.CreateIntegrationProviderResponses[keyof T.CreateIntegrationProviderResponses]> {
    return this.transport.request<T.CreateIntegrationProviderResponses[keyof T.CreateIntegrationProviderResponses]>({
      method: "POST",
      path: "/payments/integrations/provider/whitelabel",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** List Orders */
  async listOrders(params: T.ListOrdersData['query']): Promise<T.ListOrdersResponses[keyof T.ListOrdersResponses]> {
    return this.transport.request<T.ListOrdersResponses[keyof T.ListOrdersResponses]>({
      method: "GET",
      path: "/payments/orders",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "altId": (params as unknown as Record<string, any>)["altId"],
        "status": (params as unknown as Record<string, any>)["status"],
        "paymentStatus": (params as unknown as Record<string, any>)["paymentStatus"],
        "paymentMode": (params as unknown as Record<string, any>)["paymentMode"],
        "startAt": (params as unknown as Record<string, any>)["startAt"],
        "endAt": (params as unknown as Record<string, any>)["endAt"],
        "search": (params as unknown as Record<string, any>)["search"],
        "contactId": (params as unknown as Record<string, any>)["contactId"],
        "funnelProductIds": (params as unknown as Record<string, any>)["funnelProductIds"],
        "sourceId": (params as unknown as Record<string, any>)["sourceId"],
        "limit": (params as unknown as Record<string, any>)["limit"],
        "offset": (params as unknown as Record<string, any>)["offset"],
      },
    });
  }

  /** Get Order by ID */
  async getOrderById(params: T.GetOrderByIdData['path'] & T.GetOrderByIdData['query']): Promise<T.GetOrderByIdResponses[keyof T.GetOrderByIdResponses]> {
    return this.transport.request<T.GetOrderByIdResponses[keyof T.GetOrderByIdResponses]>({
      method: "GET",
      path: buildPath("/payments/orders/{orderId}", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "altId": (params as unknown as Record<string, any>)["altId"],
      },
    });
  }

  /** Record Order Payment */
  async recordOrderPayment(params: T.RecordOrderPaymentData['path'] & T.RecordOrderPaymentData['body']): Promise<T.RecordOrderPaymentResponses[keyof T.RecordOrderPaymentResponses]> {
    return this.transport.request<T.RecordOrderPaymentResponses[keyof T.RecordOrderPaymentResponses]>({
      method: "POST",
      path: buildPath("/payments/orders/{orderId}/record-payment", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** List fulfillment */
  async listOrderFulfillment(params: T.ListOrderFulfillmentData['path'] & T.ListOrderFulfillmentData['query']): Promise<T.ListOrderFulfillmentResponses[keyof T.ListOrderFulfillmentResponses]> {
    return this.transport.request<T.ListOrderFulfillmentResponses[keyof T.ListOrderFulfillmentResponses]>({
      method: "GET",
      path: buildPath("/payments/orders/{orderId}/fulfillments", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "altId": (params as unknown as Record<string, any>)["altId"],
        "altType": (params as unknown as Record<string, any>)["altType"],
      },
    });
  }

  /** Create order fulfillment */
  async createOrderFulfillment(params: T.CreateOrderFulfillmentData['path'] & T.CreateOrderFulfillmentData['body']): Promise<T.CreateOrderFulfillmentResponses[keyof T.CreateOrderFulfillmentResponses]> {
    return this.transport.request<T.CreateOrderFulfillmentResponses[keyof T.CreateOrderFulfillmentResponses]>({
      method: "POST",
      path: buildPath("/payments/orders/{orderId}/fulfillments", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** List Order Notes */
  async listOrderNotes(params: T.ListOrderNotesData['path'] & T.ListOrderNotesData['query']): Promise<void> {
    return this.transport.request<void>({
      method: "GET",
      path: buildPath("/payments/orders/{orderId}/notes", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "altId": (params as unknown as Record<string, any>)["altId"],
        "altType": (params as unknown as Record<string, any>)["altType"],
      },
    });
  }

  /** List Transactions */
  async listTransactions(params: T.ListTransactionsData['query']): Promise<T.ListTransactionsResponses[keyof T.ListTransactionsResponses]> {
    return this.transport.request<T.ListTransactionsResponses[keyof T.ListTransactionsResponses]>({
      method: "GET",
      path: "/payments/transactions",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "altId": (params as unknown as Record<string, any>)["altId"],
        "altType": (params as unknown as Record<string, any>)["altType"],
        "paymentMode": (params as unknown as Record<string, any>)["paymentMode"],
        "startAt": (params as unknown as Record<string, any>)["startAt"],
        "endAt": (params as unknown as Record<string, any>)["endAt"],
        "entitySourceType": (params as unknown as Record<string, any>)["entitySourceType"],
        "entitySourceSubType": (params as unknown as Record<string, any>)["entitySourceSubType"],
        "search": (params as unknown as Record<string, any>)["search"],
        "subscriptionId": (params as unknown as Record<string, any>)["subscriptionId"],
        "entityId": (params as unknown as Record<string, any>)["entityId"],
        "contactId": (params as unknown as Record<string, any>)["contactId"],
        "limit": (params as unknown as Record<string, any>)["limit"],
        "offset": (params as unknown as Record<string, any>)["offset"],
      },
    });
  }

  /** Get Transaction by ID */
  async getTransactionById(params: T.GetTransactionByIdData['path'] & T.GetTransactionByIdData['query']): Promise<T.GetTransactionByIdResponses[keyof T.GetTransactionByIdResponses]> {
    return this.transport.request<T.GetTransactionByIdResponses[keyof T.GetTransactionByIdResponses]>({
      method: "GET",
      path: buildPath("/payments/transactions/{transactionId}", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "altId": (params as unknown as Record<string, any>)["altId"],
        "altType": (params as unknown as Record<string, any>)["altType"],
      },
    });
  }

  /** List Subscriptions */
  async listSubscriptions(params: T.ListSubscriptionsData['query']): Promise<T.ListSubscriptionsResponses[keyof T.ListSubscriptionsResponses]> {
    return this.transport.request<T.ListSubscriptionsResponses[keyof T.ListSubscriptionsResponses]>({
      method: "GET",
      path: "/payments/subscriptions",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "altId": (params as unknown as Record<string, any>)["altId"],
        "altType": (params as unknown as Record<string, any>)["altType"],
        "entityId": (params as unknown as Record<string, any>)["entityId"],
        "paymentMode": (params as unknown as Record<string, any>)["paymentMode"],
        "startAt": (params as unknown as Record<string, any>)["startAt"],
        "endAt": (params as unknown as Record<string, any>)["endAt"],
        "entitySourceType": (params as unknown as Record<string, any>)["entitySourceType"],
        "search": (params as unknown as Record<string, any>)["search"],
        "contactId": (params as unknown as Record<string, any>)["contactId"],
        "id": (params as unknown as Record<string, any>)["id"],
        "limit": (params as unknown as Record<string, any>)["limit"],
        "offset": (params as unknown as Record<string, any>)["offset"],
        "getPaymentsCollectedCount": (params as unknown as Record<string, any>)["getPaymentsCollectedCount"],
      },
    });
  }

  /** Get Subscription by ID */
  async getSubscriptionById(params: T.GetSubscriptionByIdData['path'] & T.GetSubscriptionByIdData['query']): Promise<T.GetSubscriptionByIdResponses[keyof T.GetSubscriptionByIdResponses]> {
    return this.transport.request<T.GetSubscriptionByIdResponses[keyof T.GetSubscriptionByIdResponses]>({
      method: "GET",
      path: buildPath("/payments/subscriptions/{subscriptionId}", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "altId": (params as unknown as Record<string, any>)["altId"],
        "altType": (params as unknown as Record<string, any>)["altType"],
      },
    });
  }

  /** List Coupons */
  async listCoupons(params: T.ListCouponsData['query']): Promise<T.ListCouponsResponses[keyof T.ListCouponsResponses]> {
    return this.transport.request<T.ListCouponsResponses[keyof T.ListCouponsResponses]>({
      method: "GET",
      path: "/payments/coupon/list",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "altId": (params as unknown as Record<string, any>)["altId"],
        "altType": (params as unknown as Record<string, any>)["altType"],
        "limit": (params as unknown as Record<string, any>)["limit"],
        "offset": (params as unknown as Record<string, any>)["offset"],
        "status": (params as unknown as Record<string, any>)["status"],
        "search": (params as unknown as Record<string, any>)["search"],
      },
    });
  }

  /** Fetch Coupon */
  async getCoupon(params: T.GetCouponData['query']): Promise<T.GetCouponResponses[keyof T.GetCouponResponses]> {
    return this.transport.request<T.GetCouponResponses[keyof T.GetCouponResponses]>({
      method: "GET",
      path: "/payments/coupon",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "altId": (params as unknown as Record<string, any>)["altId"],
        "altType": (params as unknown as Record<string, any>)["altType"],
        "id": (params as unknown as Record<string, any>)["id"],
        "code": (params as unknown as Record<string, any>)["code"],
      },
    });
  }

  /** Create Coupon */
  async createCoupon(params: T.CreateCouponData['body']): Promise<T.CreateCouponResponses[keyof T.CreateCouponResponses]> {
    return this.transport.request<T.CreateCouponResponses[keyof T.CreateCouponResponses]>({
      method: "POST",
      path: "/payments/coupon",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Update Coupon */
  async updateCoupon(params: T.UpdateCouponData['body']): Promise<T.UpdateCouponResponses[keyof T.UpdateCouponResponses]> {
    return this.transport.request<T.UpdateCouponResponses[keyof T.UpdateCouponResponses]>({
      method: "PUT",
      path: "/payments/coupon",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Delete Coupon */
  async deleteCoupon(params: T.DeleteCouponData['body']): Promise<T.DeleteCouponResponses[keyof T.DeleteCouponResponses]> {
    return this.transport.request<T.DeleteCouponResponses[keyof T.DeleteCouponResponses]>({
      method: "DELETE",
      path: "/payments/coupon",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Create new integration */
  async createIntegration(params: T.CreateIntegrationData['query'] & T.CreateIntegrationData['body']): Promise<T.CreateIntegrationResponses[keyof T.CreateIntegrationResponses]> {
    return this.transport.request<T.CreateIntegrationResponses[keyof T.CreateIntegrationResponses]>({
      method: "POST",
      path: "/payments/custom-provider/provider",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
      },
      body: params,
    });
  }

  /** Deleting an existing integration */
  async deleteIntegration(params: T.DeleteIntegrationData['query']): Promise<T.DeleteIntegrationResponses[keyof T.DeleteIntegrationResponses]> {
    return this.transport.request<T.DeleteIntegrationResponses[keyof T.DeleteIntegrationResponses]>({
      method: "DELETE",
      path: "/payments/custom-provider/provider",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
      },
    });
  }

  /** Fetch given provider config */
  async fetchConfig(params: T.FetchConfigData['query']): Promise<T.FetchConfigResponses[keyof T.FetchConfigResponses]> {
    return this.transport.request<T.FetchConfigResponses[keyof T.FetchConfigResponses]>({
      method: "GET",
      path: "/payments/custom-provider/connect",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
      },
    });
  }

  /** Create new provider config */
  async createConfig(params: T.CreateConfigData['query'] & T.CreateConfigData['body']): Promise<T.CreateConfigResponses[keyof T.CreateConfigResponses]> {
    return this.transport.request<T.CreateConfigResponses[keyof T.CreateConfigResponses]>({
      method: "POST",
      path: "/payments/custom-provider/connect",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
      },
      body: params,
    });
  }

  /** Disconnect existing provider config */
  async disconnectConfig(params: T.DisconnectConfigData['query'] & T.DisconnectConfigData['body']): Promise<T.DisconnectConfigResponses[keyof T.DisconnectConfigResponses]> {
    return this.transport.request<T.DisconnectConfigResponses[keyof T.DisconnectConfigResponses]>({
      method: "POST",
      path: "/payments/custom-provider/disconnect",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
      },
      body: params,
    });
  }

  /** Custom-provider marketplace app update capabilities */
  async customProviderMarketplaceAppUpdateCapabilities(params: T.CustomProviderMarketplaceAppUpdateCapabilitiesData['body']): Promise<T.CustomProviderMarketplaceAppUpdateCapabilitiesResponses[keyof T.CustomProviderMarketplaceAppUpdateCapabilitiesResponses]> {
    return this.transport.request<T.CustomProviderMarketplaceAppUpdateCapabilitiesResponses[keyof T.CustomProviderMarketplaceAppUpdateCapabilitiesResponses]>({
      method: "PUT",
      path: "/payments/custom-provider/capabilities",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }
}
