// AUTO-GENERATED by scripts/generate-resources.ts — do not edit directly.
// Re-run `npm run generate` after updating the specs submodule.
import type { HttpTransport } from '../../http/transport.js';
import { buildPath } from '../shared/build-path.js';
import type * as T from './generated/types.gen.js';

export class ContactsResource {
  constructor(private readonly transport: HttpTransport) {}

  /** Search Contacts */
  async searchContactsAdvanced(params: T.SearchContactsAdvancedData['body']): Promise<void> {
    return this.transport.request<void>({
      method: "POST",
      path: "/contacts/search",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Get Duplicate Contact */
  async getDuplicateContact(params: T.GetDuplicateContactData['query']): Promise<void> {
    return this.transport.request<void>({
      method: "GET",
      path: "/contacts/search/duplicate",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "number": (params as unknown as Record<string, any>)["number"],
        "email": (params as unknown as Record<string, any>)["email"],
      },
    });
  }

  /** Get all Tasks */
  async getAllTasks(params: T.GetAllTasksData['path']): Promise<T.GetAllTasksResponses[keyof T.GetAllTasksResponses]> {
    return this.transport.request<T.GetAllTasksResponses[keyof T.GetAllTasksResponses]>({
      method: "GET",
      path: buildPath("/contacts/{contactId}/tasks", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** Create Task */
  async createTask(params: T.CreateTaskData['path'] & T.CreateTaskData['body']): Promise<T.CreateTaskResponses[keyof T.CreateTaskResponses]> {
    return this.transport.request<T.CreateTaskResponses[keyof T.CreateTaskResponses]>({
      method: "POST",
      path: buildPath("/contacts/{contactId}/tasks", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Get Task */
  async getTask(params: T.GetTaskData['path']): Promise<T.GetTaskResponses[keyof T.GetTaskResponses]> {
    return this.transport.request<T.GetTaskResponses[keyof T.GetTaskResponses]>({
      method: "GET",
      path: buildPath("/contacts/{contactId}/tasks/{taskId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** Update Task */
  async updateTask(params: T.UpdateTaskData['path'] & T.UpdateTaskData['body']): Promise<T.UpdateTaskResponses[keyof T.UpdateTaskResponses]> {
    return this.transport.request<T.UpdateTaskResponses[keyof T.UpdateTaskResponses]>({
      method: "PUT",
      path: buildPath("/contacts/{contactId}/tasks/{taskId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Delete Task */
  async deleteTask(params: T.DeleteTaskData['path']): Promise<T.DeleteTaskResponses[keyof T.DeleteTaskResponses]> {
    return this.transport.request<T.DeleteTaskResponses[keyof T.DeleteTaskResponses]>({
      method: "DELETE",
      path: buildPath("/contacts/{contactId}/tasks/{taskId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** Update Task Completed */
  async updateTaskCompleted(params: T.UpdateTaskCompletedData['path'] & T.UpdateTaskCompletedData['body']): Promise<T.UpdateTaskCompletedResponses[keyof T.UpdateTaskCompletedResponses]> {
    return this.transport.request<T.UpdateTaskCompletedResponses[keyof T.UpdateTaskCompletedResponses]>({
      method: "PUT",
      path: buildPath("/contacts/{contactId}/tasks/{taskId}/completed", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Get Appointments for Contact */
  async getAppointmentsForContact(params: T.GetAppointmentsForContactData['path']): Promise<T.GetAppointmentsForContactResponses[keyof T.GetAppointmentsForContactResponses]> {
    return this.transport.request<T.GetAppointmentsForContactResponses[keyof T.GetAppointmentsForContactResponses]>({
      method: "GET",
      path: buildPath("/contacts/{contactId}/appointments", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** Add Tags */
  async addTags(params: T.AddTagsData['path'] & T.AddTagsData['body']): Promise<T.AddTagsResponses[keyof T.AddTagsResponses]> {
    return this.transport.request<T.AddTagsResponses[keyof T.AddTagsResponses]>({
      method: "POST",
      path: buildPath("/contacts/{contactId}/tags", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Remove Tags */
  async removeTags(params: T.RemoveTagsData['path'] & T.RemoveTagsData['body']): Promise<T.RemoveTagsResponses[keyof T.RemoveTagsResponses]> {
    return this.transport.request<T.RemoveTagsResponses[keyof T.RemoveTagsResponses]>({
      method: "DELETE",
      path: buildPath("/contacts/{contactId}/tags", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Get All Notes */
  async getAllNotes(params: T.GetAllNotesData['path']): Promise<T.GetAllNotesResponses[keyof T.GetAllNotesResponses]> {
    return this.transport.request<T.GetAllNotesResponses[keyof T.GetAllNotesResponses]>({
      method: "GET",
      path: buildPath("/contacts/{contactId}/notes", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** Create Note */
  async createNote(params: T.CreateNoteData['path'] & T.CreateNoteData['body']): Promise<T.CreateNoteResponses[keyof T.CreateNoteResponses]> {
    return this.transport.request<T.CreateNoteResponses[keyof T.CreateNoteResponses]>({
      method: "POST",
      path: buildPath("/contacts/{contactId}/notes", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Get Note */
  async getNote(params: T.GetNoteData['path']): Promise<T.GetNoteResponses[keyof T.GetNoteResponses]> {
    return this.transport.request<T.GetNoteResponses[keyof T.GetNoteResponses]>({
      method: "GET",
      path: buildPath("/contacts/{contactId}/notes/{id}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** Update Note */
  async updateNote(params: T.UpdateNoteData['path'] & T.UpdateNoteData['body']): Promise<T.UpdateNoteResponses[keyof T.UpdateNoteResponses]> {
    return this.transport.request<T.UpdateNoteResponses[keyof T.UpdateNoteResponses]>({
      method: "PUT",
      path: buildPath("/contacts/{contactId}/notes/{id}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Delete Note */
  async deleteNote(params: T.DeleteNoteData['path']): Promise<T.DeleteNoteResponses[keyof T.DeleteNoteResponses]> {
    return this.transport.request<T.DeleteNoteResponses[keyof T.DeleteNoteResponses]>({
      method: "DELETE",
      path: buildPath("/contacts/{contactId}/notes/{id}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** Update Contacts Tags */
  async createAssociation(params: T.CreateAssociationData['body']): Promise<T.CreateAssociationResponses[keyof T.CreateAssociationResponses]> {
    return this.transport.request<T.CreateAssociationResponses[keyof T.CreateAssociationResponses]>({
      method: "POST",
      path: "/contacts/bulk/tags/update/{type}",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Add/Remove Contacts From Business */
  async addRemoveContactFromBusiness(params: T.AddRemoveContactFromBusinessData['body']): Promise<T.AddRemoveContactFromBusinessResponses[keyof T.AddRemoveContactFromBusinessResponses]> {
    return this.transport.request<T.AddRemoveContactFromBusinessResponses[keyof T.AddRemoveContactFromBusinessResponses]>({
      method: "POST",
      path: "/contacts/bulk/business",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Get Contact */
  async getContact(params: T.GetContactData['path']): Promise<T.GetContactResponses[keyof T.GetContactResponses]> {
    return this.transport.request<T.GetContactResponses[keyof T.GetContactResponses]>({
      method: "GET",
      path: buildPath("/contacts/{contactId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** Update Contact */
  async updateContact(params: T.UpdateContactData['path'] & T.UpdateContactData['body']): Promise<T.UpdateContactResponses[keyof T.UpdateContactResponses]> {
    return this.transport.request<T.UpdateContactResponses[keyof T.UpdateContactResponses]>({
      method: "PUT",
      path: buildPath("/contacts/{contactId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Delete Contact */
  async deleteContact(params: T.DeleteContactData['path']): Promise<T.DeleteContactResponses[keyof T.DeleteContactResponses]> {
    return this.transport.request<T.DeleteContactResponses[keyof T.DeleteContactResponses]>({
      method: "DELETE",
      path: buildPath("/contacts/{contactId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** Upsert Contact */
  async upsertContact(params: T.UpsertContactData['body']): Promise<T.UpsertContactResponses[keyof T.UpsertContactResponses]> {
    return this.transport.request<T.UpsertContactResponses[keyof T.UpsertContactResponses]>({
      method: "POST",
      path: "/contacts/upsert",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Get Contacts By BusinessId */
  async getContactsByBusinessId(params: T.GetContactsByBusinessIdData['path'] & T.GetContactsByBusinessIdData['query']): Promise<T.GetContactsByBusinessIdResponses[keyof T.GetContactsByBusinessIdResponses]> {
    return this.transport.request<T.GetContactsByBusinessIdResponses[keyof T.GetContactsByBusinessIdResponses]>({
      method: "GET",
      path: buildPath("/contacts/business/{businessId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "limit": (params as unknown as Record<string, any>)["limit"],
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "skip": (params as unknown as Record<string, any>)["skip"],
        "query": (params as unknown as Record<string, any>)["query"],
      },
    });
  }

  /** Add Followers */
  async addFollowersContact(params: T.AddFollowersContactData['path'] & T.AddFollowersContactData['body']): Promise<T.AddFollowersContactResponses[keyof T.AddFollowersContactResponses]> {
    return this.transport.request<T.AddFollowersContactResponses[keyof T.AddFollowersContactResponses]>({
      method: "POST",
      path: buildPath("/contacts/{contactId}/followers", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Remove Followers */
  async removeFollowersContact(params: T.RemoveFollowersContactData['path'] & T.RemoveFollowersContactData['body']): Promise<T.RemoveFollowersContactResponses[keyof T.RemoveFollowersContactResponses]> {
    return this.transport.request<T.RemoveFollowersContactResponses[keyof T.RemoveFollowersContactResponses]>({
      method: "DELETE",
      path: buildPath("/contacts/{contactId}/followers", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Add Contact to Campaign */
  async addContactToCampaign(params: T.AddContactToCampaignData['path'] & T.AddContactToCampaignData['body']): Promise<T.AddContactToCampaignResponses[keyof T.AddContactToCampaignResponses]> {
    return this.transport.request<T.AddContactToCampaignResponses[keyof T.AddContactToCampaignResponses]>({
      method: "POST",
      path: buildPath("/contacts/{contactId}/campaigns/{campaignId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Remove Contact From Campaign */
  async removeContactFromCampaign(params: T.RemoveContactFromCampaignData['path']): Promise<T.RemoveContactFromCampaignResponses[keyof T.RemoveContactFromCampaignResponses]> {
    return this.transport.request<T.RemoveContactFromCampaignResponses[keyof T.RemoveContactFromCampaignResponses]>({
      method: "DELETE",
      path: buildPath("/contacts/{contactId}/campaigns/{campaignId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** Remove Contact From Every Campaign */
  async removeContactFromEveryCampaign(params: T.RemoveContactFromEveryCampaignData['path']): Promise<T.RemoveContactFromEveryCampaignResponses[keyof T.RemoveContactFromEveryCampaignResponses]> {
    return this.transport.request<T.RemoveContactFromEveryCampaignResponses[keyof T.RemoveContactFromEveryCampaignResponses]>({
      method: "DELETE",
      path: buildPath("/contacts/{contactId}/campaigns/removeAll", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** Add Contact to Workflow */
  async addContactToWorkflow(params: T.AddContactToWorkflowData['path'] & T.AddContactToWorkflowData['body']): Promise<T.AddContactToWorkflowResponses[keyof T.AddContactToWorkflowResponses]> {
    return this.transport.request<T.AddContactToWorkflowResponses[keyof T.AddContactToWorkflowResponses]>({
      method: "POST",
      path: buildPath("/contacts/{contactId}/workflow/{workflowId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Delete Contact from Workflow */
  async deleteContactFromWorkflow(params: T.DeleteContactFromWorkflowData['path'] & T.DeleteContactFromWorkflowData['body']): Promise<T.DeleteContactFromWorkflowResponses[keyof T.DeleteContactFromWorkflowResponses]> {
    return this.transport.request<T.DeleteContactFromWorkflowResponses[keyof T.DeleteContactFromWorkflowResponses]>({
      method: "DELETE",
      path: buildPath("/contacts/{contactId}/workflow/{workflowId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Get Contacts */
  async getContacts(params: T.GetContactsData['query']): Promise<T.GetContactsResponses[keyof T.GetContactsResponses]> {
    return this.transport.request<T.GetContactsResponses[keyof T.GetContactsResponses]>({
      method: "GET",
      path: "/contacts/",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "startAfterId": (params as unknown as Record<string, any>)["startAfterId"],
        "startAfter": (params as unknown as Record<string, any>)["startAfter"],
        "query": (params as unknown as Record<string, any>)["query"],
        "limit": (params as unknown as Record<string, any>)["limit"],
      },
    });
  }

  /** Create Contact */
  async createContact(params: T.CreateContactData['body']): Promise<T.CreateContactResponses[keyof T.CreateContactResponses]> {
    return this.transport.request<T.CreateContactResponses[keyof T.CreateContactResponses]>({
      method: "POST",
      path: "/contacts/",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }
}
