// AUTO-GENERATED by scripts/generate-resources.ts — do not edit directly.
// Re-run `npm run generate` after updating the specs submodule.
import type { HttpTransport } from '../../http/transport.js';
import { buildPath } from '../shared/build-path.js';
import type * as T from './generated/types.gen.js';

export class VoiceAiResource {
  constructor(private readonly transport: HttpTransport) {}

  /** List Agents */
  async getAgents(params: T.GetAgentsData['query']): Promise<T.GetAgentsResponses[keyof T.GetAgentsResponses]> {
    return this.transport.request<T.GetAgentsResponses[keyof T.GetAgentsResponses]>({
      method: "GET",
      path: "/voice-ai/agents",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "page": (params as unknown as Record<string, any>)["page"],
        "pageSize": (params as unknown as Record<string, any>)["pageSize"],
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "query": (params as unknown as Record<string, any>)["query"],
      },
    });
  }

  /** Create Agent */
  async createAgent(params: T.CreateAgentData['body']): Promise<T.CreateAgentResponses[keyof T.CreateAgentResponses]> {
    return this.transport.request<T.CreateAgentResponses[keyof T.CreateAgentResponses]>({
      method: "POST",
      path: "/voice-ai/agents",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Get Agent */
  async getAgent(params: T.GetAgentData['path'] & T.GetAgentData['query']): Promise<T.GetAgentResponses[keyof T.GetAgentResponses]> {
    return this.transport.request<T.GetAgentResponses[keyof T.GetAgentResponses]>({
      method: "GET",
      path: buildPath("/voice-ai/agents/{agentId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
      },
    });
  }

  /** Patch Agent */
  async patchAgent(params: T.PatchAgentData['path'] & T.PatchAgentData['query'] & T.PatchAgentData['body']): Promise<T.PatchAgentResponses[keyof T.PatchAgentResponses]> {
    return this.transport.request<T.PatchAgentResponses[keyof T.PatchAgentResponses]>({
      method: "PATCH",
      path: buildPath("/voice-ai/agents/{agentId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
      },
      body: params,
    });
  }

  /** Delete Agent */
  async deleteAgent(params: T.DeleteAgentData['path'] & T.DeleteAgentData['query']): Promise<void> {
    return this.transport.request<void>({
      method: "DELETE",
      path: buildPath("/voice-ai/agents/{agentId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
      },
    });
  }

  /** List Call Logs */
  async getCallLogs(params: T.GetCallLogsData['query']): Promise<T.GetCallLogsResponses[keyof T.GetCallLogsResponses]> {
    return this.transport.request<T.GetCallLogsResponses[keyof T.GetCallLogsResponses]>({
      method: "GET",
      path: "/voice-ai/dashboard/call-logs",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "agentId": (params as unknown as Record<string, any>)["agentId"],
        "contactId": (params as unknown as Record<string, any>)["contactId"],
        "callType": (params as unknown as Record<string, any>)["callType"],
        "startDate": (params as unknown as Record<string, any>)["startDate"],
        "endDate": (params as unknown as Record<string, any>)["endDate"],
        "actionType": (params as unknown as Record<string, any>)["actionType"],
        "sortBy": (params as unknown as Record<string, any>)["sortBy"],
        "sort": (params as unknown as Record<string, any>)["sort"],
        "page": (params as unknown as Record<string, any>)["page"],
        "pageSize": (params as unknown as Record<string, any>)["pageSize"],
      },
    });
  }

  /** Get Call Log */
  async getCallLog(params: T.GetCallLogData['path'] & T.GetCallLogData['query']): Promise<T.GetCallLogResponses[keyof T.GetCallLogResponses]> {
    return this.transport.request<T.GetCallLogResponses[keyof T.GetCallLogResponses]>({
      method: "GET",
      path: buildPath("/voice-ai/dashboard/call-logs/{callId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
      },
    });
  }

  /** Create Agent Action */
  async createAction(params: T.CreateActionData['body']): Promise<T.CreateActionResponses[keyof T.CreateActionResponses]> {
    return this.transport.request<T.CreateActionResponses[keyof T.CreateActionResponses]>({
      method: "POST",
      path: "/voice-ai/actions",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Get Agent Action */
  async getAction(params: T.GetActionData['path'] & T.GetActionData['query']): Promise<T.GetActionResponses[keyof T.GetActionResponses]> {
    return this.transport.request<T.GetActionResponses[keyof T.GetActionResponses]>({
      method: "GET",
      path: buildPath("/voice-ai/actions/{actionId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
      },
    });
  }

  /** Update Agent Action */
  async updateAction(params: T.UpdateActionData['path'] & T.UpdateActionData['body']): Promise<T.UpdateActionResponses[keyof T.UpdateActionResponses]> {
    return this.transport.request<T.UpdateActionResponses[keyof T.UpdateActionResponses]>({
      method: "PUT",
      path: buildPath("/voice-ai/actions/{actionId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Delete Agent Action */
  async deleteAction(params: T.DeleteActionData['path'] & T.DeleteActionData['query']): Promise<void> {
    return this.transport.request<void>({
      method: "DELETE",
      path: buildPath("/voice-ai/actions/{actionId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "agentId": (params as unknown as Record<string, any>)["agentId"],
      },
    });
  }
}
