// AUTO-GENERATED by scripts/generate-resources.ts — do not edit directly.
// Re-run `npm run generate` after updating the specs submodule.
import type { HttpTransport } from '../../http/transport.js';
import { buildPath } from '../shared/build-path.js';
import type * as T from './generated/types.gen.js';

export class PhoneSystemResource {
  constructor(private readonly transport: HttpTransport) {}

  /** List Number Pools */
  async getNumberPoolList(params: T.GetNumberPoolListData['query']): Promise<T.GetNumberPoolListResponses[keyof T.GetNumberPoolListResponses]> {
    return this.transport.request<T.GetNumberPoolListResponses[keyof T.GetNumberPoolListResponses]>({
      method: "GET",
      path: "/phone-system/number-pools",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
      },
    });
  }

  /** List available phone numbers */
  async availableNumbers(params: T.AvailableNumbersData['path'] & T.AvailableNumbersData['query']): Promise<T.AvailableNumbersResponses[keyof T.AvailableNumbersResponses]> {
    return this.transport.request<T.AvailableNumbersResponses[keyof T.AvailableNumbersResponses]>({
      method: "GET",
      path: buildPath("/phone-system/numbers/location/{locationId}/available", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "countryCode": (params as unknown as Record<string, any>)["countryCode"],
        "numberTypes": (params as unknown as Record<string, any>)["numberTypes"],
        "firstPart": (params as unknown as Record<string, any>)["firstPart"],
        "lastPart": (params as unknown as Record<string, any>)["lastPart"],
        "anywhere": (params as unknown as Record<string, any>)["anywhere"],
        "smsEnabled": (params as unknown as Record<string, any>)["smsEnabled"],
        "mmsEnabled": (params as unknown as Record<string, any>)["mmsEnabled"],
        "voiceEnabled": (params as unknown as Record<string, any>)["voiceEnabled"],
      },
    });
  }

  /** Purchase a phone number */
  async purchasePhoneNumber(params: T.PurchasePhoneNumberData['path'] & T.PurchasePhoneNumberData['body']): Promise<T.PurchasePhoneNumberResponses[keyof T.PurchasePhoneNumberResponses]> {
    return this.transport.request<T.PurchasePhoneNumberResponses[keyof T.PurchasePhoneNumberResponses]>({
      method: "POST",
      path: buildPath("/phone-system/numbers/location/{locationId}/purchase", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** List active numbers */
  async activeNumbers(params: T.ActiveNumbersData['path'] & T.ActiveNumbersData['query']): Promise<T.ActiveNumbersResponses[keyof T.ActiveNumbersResponses]> {
    return this.transport.request<T.ActiveNumbersResponses[keyof T.ActiveNumbersResponses]>({
      method: "GET",
      path: buildPath("/phone-system/numbers/location/{locationId}", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "pageSize": (params as unknown as Record<string, any>)["pageSize"],
        "page": (params as unknown as Record<string, any>)["page"],
        "searchFilter": (params as unknown as Record<string, any>)["searchFilter"],
        "skipNumberPool": (params as unknown as Record<string, any>)["skipNumberPool"],
      },
    });
  }
}
