// AUTO-GENERATED by scripts/generate-resources.ts — do not edit directly.
// Re-run `npm run generate` after updating the specs submodule.
import type { HttpTransport } from '../../http/transport.js';
import { buildPath } from '../shared/build-path.js';
import type * as T from './generated/types.gen.js';

export class SocialMediaPostingResource {
  constructor(private readonly transport: HttpTransport) {}

  /** Starts OAuth For Google Account */
  async startGoogleOauth(params: T.StartGoogleOauthData['query']): Promise<void> {
    return this.transport.request<void>({
      method: "GET",
      path: "/social-media-posting/oauth/google/start",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "userId": (params as unknown as Record<string, any>)["userId"],
        "page": (params as unknown as Record<string, any>)["page"],
        "reconnect": (params as unknown as Record<string, any>)["reconnect"],
      },
    });
  }

  /** Get google business locations */
  async getGoogleLocations(params: T.GetGoogleLocationsData['path']): Promise<T.GetGoogleLocationsResponses[keyof T.GetGoogleLocationsResponses]> {
    return this.transport.request<T.GetGoogleLocationsResponses[keyof T.GetGoogleLocationsResponses]>({
      method: "GET",
      path: buildPath("/social-media-posting/oauth/{locationId}/google/locations/{accountId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** Set google business locations */
  async setGoogleLocations(params: T.SetGoogleLocationsData['path'] & T.SetGoogleLocationsData['body']): Promise<T.SetGoogleLocationsResponses[keyof T.SetGoogleLocationsResponses]> {
    return this.transport.request<T.SetGoogleLocationsResponses[keyof T.SetGoogleLocationsResponses]>({
      method: "POST",
      path: buildPath("/social-media-posting/oauth/{locationId}/google/locations/{accountId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Get posts */
  async getPosts(params: T.GetPostsData['path'] & T.GetPostsData['body']): Promise<T.GetPostsResponses[keyof T.GetPostsResponses]> {
    return this.transport.request<T.GetPostsResponses[keyof T.GetPostsResponses]>({
      method: "POST",
      path: buildPath("/social-media-posting/{locationId}/posts/list", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Create post */
  async createPost(params: T.CreatePostData['path'] & T.CreatePostData['body']): Promise<T.CreatePostResponses[keyof T.CreatePostResponses]> {
    return this.transport.request<T.CreatePostResponses[keyof T.CreatePostResponses]>({
      method: "POST",
      path: buildPath("/social-media-posting/{locationId}/posts", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Get post */
  async getPost(params: T.GetPostData['path']): Promise<T.GetPostResponses[keyof T.GetPostResponses]> {
    return this.transport.request<T.GetPostResponses[keyof T.GetPostResponses]>({
      method: "GET",
      path: buildPath("/social-media-posting/{locationId}/posts/{id}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** Edit post */
  async editPost(params: T.EditPostData['path'] & T.EditPostData['body']): Promise<T.EditPostResponses[keyof T.EditPostResponses]> {
    return this.transport.request<T.EditPostResponses[keyof T.EditPostResponses]>({
      method: "PUT",
      path: buildPath("/social-media-posting/{locationId}/posts/{id}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Delete Post */
  async deletePost(params: T.DeletePostData['path']): Promise<T.DeletePostResponses[keyof T.DeletePostResponses]> {
    return this.transport.request<T.DeletePostResponses[keyof T.DeletePostResponses]>({
      method: "DELETE",
      path: buildPath("/social-media-posting/{locationId}/posts/{id}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** Bulk Delete Social Planner Posts */
  async bulkDeleteSocialPlannerPosts(params: T.BulkDeleteSocialPlannerPostsData['body']): Promise<T.BulkDeleteSocialPlannerPostsResponses[keyof T.BulkDeleteSocialPlannerPostsResponses]> {
    return this.transport.request<T.BulkDeleteSocialPlannerPostsResponses[keyof T.BulkDeleteSocialPlannerPostsResponses]>({
      method: "POST",
      path: "/social-media-posting/{locationId}/posts/bulk-delete",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Get Accounts */
  async getAccount(params: T.GetAccountData['path']): Promise<T.GetAccountResponses[keyof T.GetAccountResponses]> {
    return this.transport.request<T.GetAccountResponses[keyof T.GetAccountResponses]>({
      method: "GET",
      path: buildPath("/social-media-posting/{locationId}/accounts", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** Delete Account */
  async deleteAccount(params: T.DeleteAccountData['path'] & T.DeleteAccountData['query']): Promise<T.DeleteAccountResponses[keyof T.DeleteAccountResponses]> {
    return this.transport.request<T.DeleteAccountResponses[keyof T.DeleteAccountResponses]>({
      method: "DELETE",
      path: buildPath("/social-media-posting/{locationId}/accounts/{id}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "companyId": (params as unknown as Record<string, any>)["companyId"],
        "userId": (params as unknown as Record<string, any>)["userId"],
      },
    });
  }

  /** Starts OAuth For Facebook Account */
  async startFacebookOauth(params: T.StartFacebookOauthData['query']): Promise<void> {
    return this.transport.request<void>({
      method: "GET",
      path: "/social-media-posting/oauth/facebook/start",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "userId": (params as unknown as Record<string, any>)["userId"],
        "page": (params as unknown as Record<string, any>)["page"],
        "reconnect": (params as unknown as Record<string, any>)["reconnect"],
      },
    });
  }

  /** Get facebook pages */
  async getFacebookPageGroup(params: T.GetFacebookPageGroupData['path']): Promise<T.GetFacebookPageGroupResponses[keyof T.GetFacebookPageGroupResponses]> {
    return this.transport.request<T.GetFacebookPageGroupResponses[keyof T.GetFacebookPageGroupResponses]>({
      method: "GET",
      path: buildPath("/social-media-posting/oauth/{locationId}/facebook/accounts/{accountId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** Attach facebook pages */
  async attachFacebookPageGroup(params: T.AttachFacebookPageGroupData['path'] & T.AttachFacebookPageGroupData['body']): Promise<T.AttachFacebookPageGroupResponses[keyof T.AttachFacebookPageGroupResponses]> {
    return this.transport.request<T.AttachFacebookPageGroupResponses[keyof T.AttachFacebookPageGroupResponses]>({
      method: "POST",
      path: buildPath("/social-media-posting/oauth/{locationId}/facebook/accounts/{accountId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Starts OAuth For Instagram Account */
  async startInstagramOauth(params: T.StartInstagramOauthData['query']): Promise<void> {
    return this.transport.request<void>({
      method: "GET",
      path: "/social-media-posting/oauth/instagram/start",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "userId": (params as unknown as Record<string, any>)["userId"],
        "page": (params as unknown as Record<string, any>)["page"],
        "reconnect": (params as unknown as Record<string, any>)["reconnect"],
      },
    });
  }

  /** Get Instagram Professional Accounts */
  async getInstagramPageGroup(params: T.GetInstagramPageGroupData['path']): Promise<T.GetInstagramPageGroupResponses[keyof T.GetInstagramPageGroupResponses]> {
    return this.transport.request<T.GetInstagramPageGroupResponses[keyof T.GetInstagramPageGroupResponses]>({
      method: "GET",
      path: buildPath("/social-media-posting/oauth/{locationId}/instagram/accounts/{accountId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** Attach Instagram Professional Accounts */
  async attachInstagramPageGroup(params: T.AttachInstagramPageGroupData['path'] & T.AttachInstagramPageGroupData['body']): Promise<T.AttachInstagramPageGroupResponses[keyof T.AttachInstagramPageGroupResponses]> {
    return this.transport.request<T.AttachInstagramPageGroupResponses[keyof T.AttachInstagramPageGroupResponses]>({
      method: "POST",
      path: buildPath("/social-media-posting/oauth/{locationId}/instagram/accounts/{accountId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Starts OAuth For LinkedIn Account */
  async startLinkedinOauth(params: T.StartLinkedinOauthData['query']): Promise<void> {
    return this.transport.request<void>({
      method: "GET",
      path: "/social-media-posting/oauth/linkedin/start",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "userId": (params as unknown as Record<string, any>)["userId"],
        "page": (params as unknown as Record<string, any>)["page"],
        "reconnect": (params as unknown as Record<string, any>)["reconnect"],
      },
    });
  }

  /** Get Linkedin pages and profile */
  async getLinkedinPageProfile(params: T.GetLinkedinPageProfileData['path']): Promise<T.GetLinkedinPageProfileResponses[keyof T.GetLinkedinPageProfileResponses]> {
    return this.transport.request<T.GetLinkedinPageProfileResponses[keyof T.GetLinkedinPageProfileResponses]>({
      method: "GET",
      path: buildPath("/social-media-posting/oauth/{locationId}/linkedin/accounts/{accountId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** Attach linkedin pages and profile */
  async attachLinkedinPageProfile(params: T.AttachLinkedinPageProfileData['path'] & T.AttachLinkedinPageProfileData['body']): Promise<T.AttachLinkedinPageProfileResponses[keyof T.AttachLinkedinPageProfileResponses]> {
    return this.transport.request<T.AttachLinkedinPageProfileResponses[keyof T.AttachLinkedinPageProfileResponses]>({
      method: "POST",
      path: buildPath("/social-media-posting/oauth/{locationId}/linkedin/accounts/{accountId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Starts OAuth For Twitter Account */
  async startTwitterOauth(params: T.StartTwitterOauthData['query']): Promise<void> {
    return this.transport.request<void>({
      method: "GET",
      path: "/social-media-posting/oauth/twitter/start",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "userId": (params as unknown as Record<string, any>)["userId"],
        "page": (params as unknown as Record<string, any>)["page"],
        "reconnect": (params as unknown as Record<string, any>)["reconnect"],
      },
    });
  }

  /** Get Twitter profile */
  async getTwitterProfile(params: T.GetTwitterProfileData['path']): Promise<T.GetTwitterProfileResponses[keyof T.GetTwitterProfileResponses]> {
    return this.transport.request<T.GetTwitterProfileResponses[keyof T.GetTwitterProfileResponses]>({
      method: "GET",
      path: buildPath("/social-media-posting/oauth/{locationId}/twitter/accounts/{accountId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** Attach Twitter profile */
  async attachTwitterProfile(params: T.AttachTwitterProfileData['path'] & T.AttachTwitterProfileData['body']): Promise<T.AttachTwitterProfileResponses[keyof T.AttachTwitterProfileResponses]> {
    return this.transport.request<T.AttachTwitterProfileResponses[keyof T.AttachTwitterProfileResponses]>({
      method: "POST",
      path: buildPath("/social-media-posting/oauth/{locationId}/twitter/accounts/{accountId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Get Upload Status */
  async getUploadStatus(params: T.GetUploadStatusData['path'] & T.GetUploadStatusData['query']): Promise<T.GetUploadStatusResponses[keyof T.GetUploadStatusResponses]> {
    return this.transport.request<T.GetUploadStatusResponses[keyof T.GetUploadStatusResponses]>({
      method: "GET",
      path: buildPath("/social-media-posting/{locationId}/csv", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "skip": (params as unknown as Record<string, any>)["skip"],
        "limit": (params as unknown as Record<string, any>)["limit"],
        "includeUsers": (params as unknown as Record<string, any>)["includeUsers"],
        "userId": (params as unknown as Record<string, any>)["userId"],
      },
    });
  }

  /** Upload CSV */
  async uploadCsv(params: T.UploadCsvData['path']): Promise<T.UploadCsvResponses[keyof T.UploadCsvResponses]> {
    return this.transport.request<T.UploadCsvResponses[keyof T.UploadCsvResponses]>({
      method: "POST",
      path: buildPath("/social-media-posting/{locationId}/csv", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** Set Accounts */
  async setAccounts(params: T.SetAccountsData['path'] & T.SetAccountsData['body']): Promise<T.SetAccountsResponses[keyof T.SetAccountsResponses]> {
    return this.transport.request<T.SetAccountsResponses[keyof T.SetAccountsResponses]>({
      method: "POST",
      path: buildPath("/social-media-posting/{locationId}/set-accounts", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Get CSV Post */
  async getCsvPost(params: T.GetCsvPostData['path'] & T.GetCsvPostData['query']): Promise<T.GetCsvPostResponses[keyof T.GetCsvPostResponses]> {
    return this.transport.request<T.GetCsvPostResponses[keyof T.GetCsvPostResponses]>({
      method: "GET",
      path: buildPath("/social-media-posting/{locationId}/csv/{id}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "skip": (params as unknown as Record<string, any>)["skip"],
        "limit": (params as unknown as Record<string, any>)["limit"],
      },
    });
  }

  /** Start CSV Finalize */
  async startCsvFinalize(params: T.StartCsvFinalizeData['path'] & T.StartCsvFinalizeData['body']): Promise<T.StartCsvFinalizeResponses[keyof T.StartCsvFinalizeResponses]> {
    return this.transport.request<T.StartCsvFinalizeResponses[keyof T.StartCsvFinalizeResponses]>({
      method: "PATCH",
      path: buildPath("/social-media-posting/{locationId}/csv/{id}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Delete CSV */
  async deleteCsv(params: T.DeleteCsvData['path']): Promise<T.DeleteCsvResponses[keyof T.DeleteCsvResponses]> {
    return this.transport.request<T.DeleteCsvResponses[keyof T.DeleteCsvResponses]>({
      method: "DELETE",
      path: buildPath("/social-media-posting/{locationId}/csv/{id}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** Delete CSV Post */
  async deleteCsvPost(params: T.DeleteCsvPostData['path']): Promise<T.DeleteCsvPostResponses[keyof T.DeleteCsvPostResponses]> {
    return this.transport.request<T.DeleteCsvPostResponses[keyof T.DeleteCsvPostResponses]>({
      method: "DELETE",
      path: buildPath("/social-media-posting/{locationId}/csv/{csvId}/post/{postId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** Starts OAuth For Tiktok Account */
  async startTiktokOauth(params: T.StartTiktokOauthData['query']): Promise<void> {
    return this.transport.request<void>({
      method: "GET",
      path: "/social-media-posting/oauth/tiktok/start",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "userId": (params as unknown as Record<string, any>)["userId"],
        "page": (params as unknown as Record<string, any>)["page"],
        "reconnect": (params as unknown as Record<string, any>)["reconnect"],
      },
    });
  }

  /** Get Tiktok profile */
  async getTiktokProfile(params: T.GetTiktokProfileData['path']): Promise<T.GetTiktokProfileResponses[keyof T.GetTiktokProfileResponses]> {
    return this.transport.request<T.GetTiktokProfileResponses[keyof T.GetTiktokProfileResponses]>({
      method: "GET",
      path: buildPath("/social-media-posting/oauth/{locationId}/tiktok/accounts/{accountId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** Attach Tiktok profile */
  async attachTiktokProfile(params: T.AttachTiktokProfileData['path'] & T.AttachTiktokProfileData['body']): Promise<T.AttachTiktokProfileResponses[keyof T.AttachTiktokProfileResponses]> {
    return this.transport.request<T.AttachTiktokProfileResponses[keyof T.AttachTiktokProfileResponses]>({
      method: "POST",
      path: buildPath("/social-media-posting/oauth/{locationId}/tiktok/accounts/{accountId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Starts OAuth For Tiktok Business Account */
  async startTiktokBusinessOauth(params: T.StartTiktokBusinessOauthData['query']): Promise<void> {
    return this.transport.request<void>({
      method: "GET",
      path: "/social-media-posting/oauth/tiktok-business/start",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "userId": (params as unknown as Record<string, any>)["userId"],
        "page": (params as unknown as Record<string, any>)["page"],
        "reconnect": (params as unknown as Record<string, any>)["reconnect"],
      },
    });
  }

  /** Get Tiktok Business profile */
  async getTiktokBusinessProfile(params: T.GetTiktokBusinessProfileData['path']): Promise<T.GetTiktokBusinessProfileResponses[keyof T.GetTiktokBusinessProfileResponses]> {
    return this.transport.request<T.GetTiktokBusinessProfileResponses[keyof T.GetTiktokBusinessProfileResponses]>({
      method: "GET",
      path: buildPath("/social-media-posting/oauth/{locationId}/tiktok-business/accounts/{accountId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** Get categories by location id */
  async getCategoriesLocationId(params: T.GetCategoriesLocationIdData['path'] & T.GetCategoriesLocationIdData['query']): Promise<T.GetCategoriesLocationIdResponses[keyof T.GetCategoriesLocationIdResponses]> {
    return this.transport.request<T.GetCategoriesLocationIdResponses[keyof T.GetCategoriesLocationIdResponses]>({
      method: "GET",
      path: buildPath("/social-media-posting/{locationId}/categories", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "searchText": (params as unknown as Record<string, any>)["searchText"],
        "limit": (params as unknown as Record<string, any>)["limit"],
        "skip": (params as unknown as Record<string, any>)["skip"],
      },
    });
  }

  /** Get categories by id */
  async getCategoriesId(params: T.GetCategoriesIdData['path']): Promise<T.GetCategoriesIdResponses[keyof T.GetCategoriesIdResponses]> {
    return this.transport.request<T.GetCategoriesIdResponses[keyof T.GetCategoriesIdResponses]>({
      method: "GET",
      path: buildPath("/social-media-posting/{locationId}/categories/{id}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** Get tags by location id */
  async getTagsLocationId(params: T.GetTagsLocationIdData['path'] & T.GetTagsLocationIdData['query']): Promise<T.GetTagsLocationIdResponses[keyof T.GetTagsLocationIdResponses]> {
    return this.transport.request<T.GetTagsLocationIdResponses[keyof T.GetTagsLocationIdResponses]>({
      method: "GET",
      path: buildPath("/social-media-posting/{locationId}/tags", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "searchText": (params as unknown as Record<string, any>)["searchText"],
        "limit": (params as unknown as Record<string, any>)["limit"],
        "skip": (params as unknown as Record<string, any>)["skip"],
      },
    });
  }

  /** Get tags by ids */
  async getTagsByIds(params: T.GetTagsByIdsData['path'] & T.GetTagsByIdsData['body']): Promise<T.GetTagsByIdsResponses[keyof T.GetTagsByIdsResponses]> {
    return this.transport.request<T.GetTagsByIdsResponses[keyof T.GetTagsByIdsResponses]>({
      method: "POST",
      path: buildPath("/social-media-posting/{locationId}/tags/details", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Get Social Media Statistics */
  async getSocialMediaStatistics(params: T.GetSocialMediaStatisticsData['query'] & T.GetSocialMediaStatisticsData['body']): Promise<T.GetSocialMediaStatisticsResponses[keyof T.GetSocialMediaStatisticsResponses]> {
    return this.transport.request<T.GetSocialMediaStatisticsResponses[keyof T.GetSocialMediaStatisticsResponses]>({
      method: "POST",
      path: "/social-media-posting/statistics",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
      },
      body: params,
    });
  }
}
