// AUTO-GENERATED by scripts/generate-resources.ts — do not edit directly.
// Re-run `npm run generate` after updating the specs submodule.
import type { HttpTransport } from '../../http/transport.js';
import { buildPath } from '../shared/build-path.js';
import type * as T from './generated/types.gen.js';

export class EmailsResource {
  constructor(private readonly transport: HttpTransport) {}

  /** Get Campaigns */
  async fetchCampaigns(params: T.FetchCampaignsData['query']): Promise<T.FetchCampaignsResponses[keyof T.FetchCampaignsResponses]> {
    return this.transport.request<T.FetchCampaignsResponses[keyof T.FetchCampaignsResponses]>({
      method: "GET",
      path: "/emails/schedule",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "limit": (params as unknown as Record<string, any>)["limit"],
        "offset": (params as unknown as Record<string, any>)["offset"],
        "status": (params as unknown as Record<string, any>)["status"],
        "emailStatus": (params as unknown as Record<string, any>)["emailStatus"],
        "name": (params as unknown as Record<string, any>)["name"],
        "parentId": (params as unknown as Record<string, any>)["parentId"],
        "limitedFields": (params as unknown as Record<string, any>)["limitedFields"],
        "archived": (params as unknown as Record<string, any>)["archived"],
        "campaignsOnly": (params as unknown as Record<string, any>)["campaignsOnly"],
        "showStats": (params as unknown as Record<string, any>)["showStats"],
      },
    });
  }

  /** Fetch email templates */
  async fetchTemplate(params: T.FetchTemplateData['query']): Promise<T.FetchTemplateResponses[keyof T.FetchTemplateResponses]> {
    return this.transport.request<T.FetchTemplateResponses[keyof T.FetchTemplateResponses]>({
      method: "GET",
      path: "/emails/builder",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "limit": (params as unknown as Record<string, any>)["limit"],
        "offset": (params as unknown as Record<string, any>)["offset"],
        "search": (params as unknown as Record<string, any>)["search"],
        "sortByDate": (params as unknown as Record<string, any>)["sortByDate"],
        "archived": (params as unknown as Record<string, any>)["archived"],
        "builderVersion": (params as unknown as Record<string, any>)["builderVersion"],
        "name": (params as unknown as Record<string, any>)["name"],
        "parentId": (params as unknown as Record<string, any>)["parentId"],
        "originId": (params as unknown as Record<string, any>)["originId"],
        "templatesOnly": (params as unknown as Record<string, any>)["templatesOnly"],
      },
    });
  }

  /** Create a new template */
  async createTemplate(params: T.CreateTemplateData['body']): Promise<T.CreateTemplateResponses[keyof T.CreateTemplateResponses]> {
    return this.transport.request<T.CreateTemplateResponses[keyof T.CreateTemplateResponses]>({
      method: "POST",
      path: "/emails/builder",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Delete a template */
  async deleteTemplate(params: T.DeleteTemplateData['path']): Promise<T.DeleteTemplateResponses[keyof T.DeleteTemplateResponses]> {
    return this.transport.request<T.DeleteTemplateResponses[keyof T.DeleteTemplateResponses]>({
      method: "DELETE",
      path: buildPath("/emails/builder/{locationId}/{templateId}", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** Update a template */
  async updateTemplate(params: T.UpdateTemplateData['body']): Promise<T.UpdateTemplateResponses[keyof T.UpdateTemplateResponses]> {
    return this.transport.request<T.UpdateTemplateResponses[keyof T.UpdateTemplateResponses]>({
      method: "POST",
      path: "/emails/builder/data",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }
}
