// AUTO-GENERATED by scripts/generate-resources.ts — do not edit directly.
// Re-run `npm run generate` after updating the specs submodule.
import type { HttpTransport } from '../../http/transport.js';
import { buildPath } from '../shared/build-path.js';
import type * as T from './generated/types.gen.js';

export class InvoicesResource {
  constructor(private readonly transport: HttpTransport) {}

  /** List templates */
  async listInvoiceTemplates(params: T.ListInvoiceTemplatesData['query']): Promise<T.ListInvoiceTemplatesResponses[keyof T.ListInvoiceTemplatesResponses]> {
    return this.transport.request<T.ListInvoiceTemplatesResponses[keyof T.ListInvoiceTemplatesResponses]>({
      method: "GET",
      path: "/invoices/template",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "altId": (params as unknown as Record<string, any>)["altId"],
        "altType": (params as unknown as Record<string, any>)["altType"],
        "status": (params as unknown as Record<string, any>)["status"],
        "startAt": (params as unknown as Record<string, any>)["startAt"],
        "endAt": (params as unknown as Record<string, any>)["endAt"],
        "search": (params as unknown as Record<string, any>)["search"],
        "paymentMode": (params as unknown as Record<string, any>)["paymentMode"],
        "limit": (params as unknown as Record<string, any>)["limit"],
        "offset": (params as unknown as Record<string, any>)["offset"],
      },
    });
  }

  /** Create template */
  async createInvoiceTemplate(params: T.CreateInvoiceTemplateData['body']): Promise<T.CreateInvoiceTemplateResponses[keyof T.CreateInvoiceTemplateResponses]> {
    return this.transport.request<T.CreateInvoiceTemplateResponses[keyof T.CreateInvoiceTemplateResponses]>({
      method: "POST",
      path: "/invoices/template",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Get an template */
  async getInvoiceTemplate(params: T.GetInvoiceTemplateData['path'] & T.GetInvoiceTemplateData['query']): Promise<T.GetInvoiceTemplateResponses[keyof T.GetInvoiceTemplateResponses]> {
    return this.transport.request<T.GetInvoiceTemplateResponses[keyof T.GetInvoiceTemplateResponses]>({
      method: "GET",
      path: buildPath("/invoices/template/{templateId}", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "altId": (params as unknown as Record<string, any>)["altId"],
        "altType": (params as unknown as Record<string, any>)["altType"],
      },
    });
  }

  /** Update template */
  async updateInvoiceTemplate(params: T.UpdateInvoiceTemplateData['path'] & T.UpdateInvoiceTemplateData['body']): Promise<T.UpdateInvoiceTemplateResponses[keyof T.UpdateInvoiceTemplateResponses]> {
    return this.transport.request<T.UpdateInvoiceTemplateResponses[keyof T.UpdateInvoiceTemplateResponses]>({
      method: "PUT",
      path: buildPath("/invoices/template/{templateId}", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Delete template */
  async deleteInvoiceTemplate(params: T.DeleteInvoiceTemplateData['path'] & T.DeleteInvoiceTemplateData['query']): Promise<T.DeleteInvoiceTemplateResponses[keyof T.DeleteInvoiceTemplateResponses]> {
    return this.transport.request<T.DeleteInvoiceTemplateResponses[keyof T.DeleteInvoiceTemplateResponses]>({
      method: "DELETE",
      path: buildPath("/invoices/template/{templateId}", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "altId": (params as unknown as Record<string, any>)["altId"],
        "altType": (params as unknown as Record<string, any>)["altType"],
      },
    });
  }

  /** Update template late fees configuration */
  async updateInvoiceTemplateLateFeesConfiguration(params: T.UpdateInvoiceTemplateLateFeesConfigurationData['path'] & T.UpdateInvoiceTemplateLateFeesConfigurationData['body']): Promise<T.UpdateInvoiceTemplateLateFeesConfigurationResponses[keyof T.UpdateInvoiceTemplateLateFeesConfigurationResponses]> {
    return this.transport.request<T.UpdateInvoiceTemplateLateFeesConfigurationResponses[keyof T.UpdateInvoiceTemplateLateFeesConfigurationResponses]>({
      method: "PATCH",
      path: buildPath("/invoices/template/{templateId}/late-fees-configuration", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Update template late fees configuration */
  async updateInvoicePaymentMethodsConfiguration(params: T.UpdateInvoicePaymentMethodsConfigurationData['path'] & T.UpdateInvoicePaymentMethodsConfigurationData['body']): Promise<T.UpdateInvoicePaymentMethodsConfigurationResponses[keyof T.UpdateInvoicePaymentMethodsConfigurationResponses]> {
    return this.transport.request<T.UpdateInvoicePaymentMethodsConfigurationResponses[keyof T.UpdateInvoicePaymentMethodsConfigurationResponses]>({
      method: "PATCH",
      path: buildPath("/invoices/template/{templateId}/payment-methods-configuration", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** List schedules */
  async listInvoiceSchedules(params: T.ListInvoiceSchedulesData['query']): Promise<T.ListInvoiceSchedulesResponses[keyof T.ListInvoiceSchedulesResponses]> {
    return this.transport.request<T.ListInvoiceSchedulesResponses[keyof T.ListInvoiceSchedulesResponses]>({
      method: "GET",
      path: "/invoices/schedule",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "altId": (params as unknown as Record<string, any>)["altId"],
        "altType": (params as unknown as Record<string, any>)["altType"],
        "status": (params as unknown as Record<string, any>)["status"],
        "startAt": (params as unknown as Record<string, any>)["startAt"],
        "endAt": (params as unknown as Record<string, any>)["endAt"],
        "search": (params as unknown as Record<string, any>)["search"],
        "paymentMode": (params as unknown as Record<string, any>)["paymentMode"],
        "limit": (params as unknown as Record<string, any>)["limit"],
        "offset": (params as unknown as Record<string, any>)["offset"],
      },
    });
  }

  /** Create Invoice Schedule */
  async createInvoiceSchedule(params: T.CreateInvoiceScheduleData['body']): Promise<T.CreateInvoiceScheduleResponses[keyof T.CreateInvoiceScheduleResponses]> {
    return this.transport.request<T.CreateInvoiceScheduleResponses[keyof T.CreateInvoiceScheduleResponses]>({
      method: "POST",
      path: "/invoices/schedule",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Get an schedule */
  async getInvoiceSchedule(params: T.GetInvoiceScheduleData['path'] & T.GetInvoiceScheduleData['query']): Promise<T.GetInvoiceScheduleResponses[keyof T.GetInvoiceScheduleResponses]> {
    return this.transport.request<T.GetInvoiceScheduleResponses[keyof T.GetInvoiceScheduleResponses]>({
      method: "GET",
      path: buildPath("/invoices/schedule/{scheduleId}", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "altId": (params as unknown as Record<string, any>)["altId"],
        "altType": (params as unknown as Record<string, any>)["altType"],
      },
    });
  }

  /** Update schedule */
  async updateInvoiceSchedule(params: T.UpdateInvoiceScheduleData['path'] & T.UpdateInvoiceScheduleData['body']): Promise<T.UpdateInvoiceScheduleResponses[keyof T.UpdateInvoiceScheduleResponses]> {
    return this.transport.request<T.UpdateInvoiceScheduleResponses[keyof T.UpdateInvoiceScheduleResponses]>({
      method: "PUT",
      path: buildPath("/invoices/schedule/{scheduleId}", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Delete schedule */
  async deleteInvoiceSchedule(params: T.DeleteInvoiceScheduleData['path'] & T.DeleteInvoiceScheduleData['query']): Promise<T.DeleteInvoiceScheduleResponses[keyof T.DeleteInvoiceScheduleResponses]> {
    return this.transport.request<T.DeleteInvoiceScheduleResponses[keyof T.DeleteInvoiceScheduleResponses]>({
      method: "DELETE",
      path: buildPath("/invoices/schedule/{scheduleId}", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "altId": (params as unknown as Record<string, any>)["altId"],
        "altType": (params as unknown as Record<string, any>)["altType"],
      },
    });
  }

  /** Update scheduled recurring invoice */
  async updateAndScheduleInvoiceSchedule(params: T.UpdateAndScheduleInvoiceScheduleData['path']): Promise<T.UpdateAndScheduleInvoiceScheduleResponses[keyof T.UpdateAndScheduleInvoiceScheduleResponses]> {
    return this.transport.request<T.UpdateAndScheduleInvoiceScheduleResponses[keyof T.UpdateAndScheduleInvoiceScheduleResponses]>({
      method: "POST",
      path: buildPath("/invoices/schedule/{scheduleId}/updateAndSchedule", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** Schedule an schedule invoice */
  async scheduleInvoiceSchedule(params: T.ScheduleInvoiceScheduleData['path'] & T.ScheduleInvoiceScheduleData['body']): Promise<T.ScheduleInvoiceScheduleResponses[keyof T.ScheduleInvoiceScheduleResponses]> {
    return this.transport.request<T.ScheduleInvoiceScheduleResponses[keyof T.ScheduleInvoiceScheduleResponses]>({
      method: "POST",
      path: buildPath("/invoices/schedule/{scheduleId}/schedule", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Manage Auto payment for an schedule invoice */
  async autoPaymentInvoiceSchedule(params: T.AutoPaymentInvoiceScheduleData['path'] & T.AutoPaymentInvoiceScheduleData['body']): Promise<T.AutoPaymentInvoiceScheduleResponses[keyof T.AutoPaymentInvoiceScheduleResponses]> {
    return this.transport.request<T.AutoPaymentInvoiceScheduleResponses[keyof T.AutoPaymentInvoiceScheduleResponses]>({
      method: "POST",
      path: buildPath("/invoices/schedule/{scheduleId}/auto-payment", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Cancel an scheduled invoice */
  async cancelInvoiceSchedule(params: T.CancelInvoiceScheduleData['path'] & T.CancelInvoiceScheduleData['body']): Promise<T.CancelInvoiceScheduleResponses[keyof T.CancelInvoiceScheduleResponses]> {
    return this.transport.request<T.CancelInvoiceScheduleResponses[keyof T.CancelInvoiceScheduleResponses]>({
      method: "POST",
      path: buildPath("/invoices/schedule/{scheduleId}/cancel", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Create & Send */
  async text2payInvoice(params: T.Text2PayInvoiceData['body']): Promise<T.Text2PayInvoiceResponses[keyof T.Text2PayInvoiceResponses]> {
    return this.transport.request<T.Text2PayInvoiceResponses[keyof T.Text2PayInvoiceResponses]>({
      method: "POST",
      path: "/invoices/text2pay",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Generate Invoice Number */
  async generateInvoiceNumber(params: T.GenerateInvoiceNumberData['query']): Promise<T.GenerateInvoiceNumberResponses[keyof T.GenerateInvoiceNumberResponses]> {
    return this.transport.request<T.GenerateInvoiceNumberResponses[keyof T.GenerateInvoiceNumberResponses]>({
      method: "GET",
      path: "/invoices/generate-invoice-number",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "altId": (params as unknown as Record<string, any>)["altId"],
        "altType": (params as unknown as Record<string, any>)["altType"],
      },
    });
  }

  /** Get Invoice Settings */
  async getInvoiceSettings(params: T.GetInvoiceSettingsData['query']): Promise<T.GetInvoiceSettingsResponses[keyof T.GetInvoiceSettingsResponses]> {
    return this.transport.request<T.GetInvoiceSettingsResponses[keyof T.GetInvoiceSettingsResponses]>({
      method: "GET",
      path: "/invoices/settings",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "altId": (params as unknown as Record<string, any>)["altId"],
        "altType": (params as unknown as Record<string, any>)["altType"],
      },
    });
  }

  /** Get invoice */
  async getInvoice(params: T.GetInvoiceData['path'] & T.GetInvoiceData['query']): Promise<T.GetInvoiceResponses[keyof T.GetInvoiceResponses]> {
    return this.transport.request<T.GetInvoiceResponses[keyof T.GetInvoiceResponses]>({
      method: "GET",
      path: buildPath("/invoices/{invoiceId}", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "altId": (params as unknown as Record<string, any>)["altId"],
        "altType": (params as unknown as Record<string, any>)["altType"],
      },
    });
  }

  /** Update invoice */
  async updateInvoice(params: T.UpdateInvoiceData['path'] & T.UpdateInvoiceData['body']): Promise<T.UpdateInvoiceResponses[keyof T.UpdateInvoiceResponses]> {
    return this.transport.request<T.UpdateInvoiceResponses[keyof T.UpdateInvoiceResponses]>({
      method: "PUT",
      path: buildPath("/invoices/{invoiceId}", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Delete invoice */
  async deleteInvoice(params: T.DeleteInvoiceData['path'] & T.DeleteInvoiceData['query']): Promise<T.DeleteInvoiceResponses[keyof T.DeleteInvoiceResponses]> {
    return this.transport.request<T.DeleteInvoiceResponses[keyof T.DeleteInvoiceResponses]>({
      method: "DELETE",
      path: buildPath("/invoices/{invoiceId}", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "altId": (params as unknown as Record<string, any>)["altId"],
        "altType": (params as unknown as Record<string, any>)["altType"],
      },
    });
  }

  /** Update invoice late fees configuration */
  async updateInvoiceLateFeesConfiguration(params: T.UpdateInvoiceLateFeesConfigurationData['path'] & T.UpdateInvoiceLateFeesConfigurationData['body']): Promise<T.UpdateInvoiceLateFeesConfigurationResponses[keyof T.UpdateInvoiceLateFeesConfigurationResponses]> {
    return this.transport.request<T.UpdateInvoiceLateFeesConfigurationResponses[keyof T.UpdateInvoiceLateFeesConfigurationResponses]>({
      method: "PATCH",
      path: buildPath("/invoices/{invoiceId}/late-fees-configuration", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Void invoice */
  async voidInvoice(params: T.VoidInvoiceData['path'] & T.VoidInvoiceData['body']): Promise<T.VoidInvoiceResponses[keyof T.VoidInvoiceResponses]> {
    return this.transport.request<T.VoidInvoiceResponses[keyof T.VoidInvoiceResponses]>({
      method: "POST",
      path: buildPath("/invoices/{invoiceId}/void", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Send invoice */
  async sendInvoice(params: T.SendInvoiceData['path'] & T.SendInvoiceData['body']): Promise<T.SendInvoiceResponses[keyof T.SendInvoiceResponses]> {
    return this.transport.request<T.SendInvoiceResponses[keyof T.SendInvoiceResponses]>({
      method: "POST",
      path: buildPath("/invoices/{invoiceId}/send", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Record a manual payment for an invoice */
  async recordInvoice(params: T.RecordInvoiceData['path'] & T.RecordInvoiceData['body']): Promise<T.RecordInvoiceResponses[keyof T.RecordInvoiceResponses]> {
    return this.transport.request<T.RecordInvoiceResponses[keyof T.RecordInvoiceResponses]>({
      method: "POST",
      path: buildPath("/invoices/{invoiceId}/record-payment", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Update invoice last visited at */
  async updateInvoiceLastVisitedAt(params: T.UpdateInvoiceLastVisitedAtData['body']): Promise<void> {
    return this.transport.request<void>({
      method: "PATCH",
      path: "/invoices/stats/last-visited-at",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Create New Estimate */
  async createNewEstimate(params: T.CreateNewEstimateData['body']): Promise<T.CreateNewEstimateResponses[keyof T.CreateNewEstimateResponses]> {
    return this.transport.request<T.CreateNewEstimateResponses[keyof T.CreateNewEstimateResponses]>({
      method: "POST",
      path: "/invoices/estimate",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Update Estimate */
  async updateEstimate(params: T.UpdateEstimateData['path'] & T.UpdateEstimateData['body']): Promise<T.UpdateEstimateResponses[keyof T.UpdateEstimateResponses]> {
    return this.transport.request<T.UpdateEstimateResponses[keyof T.UpdateEstimateResponses]>({
      method: "PUT",
      path: buildPath("/invoices/estimate/{estimateId}", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Delete Estimate */
  async deleteEstimate(params: T.DeleteEstimateData['path'] & T.DeleteEstimateData['body']): Promise<T.DeleteEstimateResponses[keyof T.DeleteEstimateResponses]> {
    return this.transport.request<T.DeleteEstimateResponses[keyof T.DeleteEstimateResponses]>({
      method: "DELETE",
      path: buildPath("/invoices/estimate/{estimateId}", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Generate Estimate Number */
  async generateEstimateNumber(params: T.GenerateEstimateNumberData['query']): Promise<T.GenerateEstimateNumberResponses[keyof T.GenerateEstimateNumberResponses]> {
    return this.transport.request<T.GenerateEstimateNumberResponses[keyof T.GenerateEstimateNumberResponses]>({
      method: "GET",
      path: "/invoices/estimate/number/generate",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "altId": (params as unknown as Record<string, any>)["altId"],
        "altType": (params as unknown as Record<string, any>)["altType"],
      },
    });
  }

  /** Send Estimate */
  async sendEstimate(params: T.SendEstimateData['path'] & T.SendEstimateData['body']): Promise<T.SendEstimateResponses[keyof T.SendEstimateResponses]> {
    return this.transport.request<T.SendEstimateResponses[keyof T.SendEstimateResponses]>({
      method: "POST",
      path: buildPath("/invoices/estimate/{estimateId}/send", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Create Invoice from Estimate */
  async createInvoiceFromEstimate(params: T.CreateInvoiceFromEstimateData['path'] & T.CreateInvoiceFromEstimateData['body']): Promise<T.CreateInvoiceFromEstimateResponses[keyof T.CreateInvoiceFromEstimateResponses]> {
    return this.transport.request<T.CreateInvoiceFromEstimateResponses[keyof T.CreateInvoiceFromEstimateResponses]>({
      method: "POST",
      path: buildPath("/invoices/estimate/{estimateId}/invoice", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** List Estimates */
  async listEstimates(params: T.ListEstimatesData['query']): Promise<T.ListEstimatesResponses[keyof T.ListEstimatesResponses]> {
    return this.transport.request<T.ListEstimatesResponses[keyof T.ListEstimatesResponses]>({
      method: "GET",
      path: "/invoices/estimate/list",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "altId": (params as unknown as Record<string, any>)["altId"],
        "altType": (params as unknown as Record<string, any>)["altType"],
        "startAt": (params as unknown as Record<string, any>)["startAt"],
        "endAt": (params as unknown as Record<string, any>)["endAt"],
        "search": (params as unknown as Record<string, any>)["search"],
        "status": (params as unknown as Record<string, any>)["status"],
        "contactId": (params as unknown as Record<string, any>)["contactId"],
        "limit": (params as unknown as Record<string, any>)["limit"],
        "offset": (params as unknown as Record<string, any>)["offset"],
      },
    });
  }

  /** Update estimate last visited at */
  async updateEstimateLastVisitedAt(params: T.UpdateEstimateLastVisitedAtData['body']): Promise<void> {
    return this.transport.request<void>({
      method: "PATCH",
      path: "/invoices/estimate/stats/last-visited-at",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** List Estimate Templates */
  async listEstimateTemplates(params: T.ListEstimateTemplatesData['query']): Promise<T.ListEstimateTemplatesResponses[keyof T.ListEstimateTemplatesResponses]> {
    return this.transport.request<T.ListEstimateTemplatesResponses[keyof T.ListEstimateTemplatesResponses]>({
      method: "GET",
      path: "/invoices/estimate/template",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "altId": (params as unknown as Record<string, any>)["altId"],
        "altType": (params as unknown as Record<string, any>)["altType"],
        "search": (params as unknown as Record<string, any>)["search"],
        "limit": (params as unknown as Record<string, any>)["limit"],
        "offset": (params as unknown as Record<string, any>)["offset"],
      },
    });
  }

  /** Create Estimate Template */
  async createEstimateTemplate(params: T.CreateEstimateTemplateData['body']): Promise<T.CreateEstimateTemplateResponses[keyof T.CreateEstimateTemplateResponses]> {
    return this.transport.request<T.CreateEstimateTemplateResponses[keyof T.CreateEstimateTemplateResponses]>({
      method: "POST",
      path: "/invoices/estimate/template",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Update Estimate Template */
  async updateEstimateTemplate(params: T.UpdateEstimateTemplateData['path'] & T.UpdateEstimateTemplateData['body']): Promise<T.UpdateEstimateTemplateResponses[keyof T.UpdateEstimateTemplateResponses]> {
    return this.transport.request<T.UpdateEstimateTemplateResponses[keyof T.UpdateEstimateTemplateResponses]>({
      method: "PUT",
      path: buildPath("/invoices/estimate/template/{templateId}", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Delete Estimate Template */
  async deleteEstimateTemplate(params: T.DeleteEstimateTemplateData['path'] & T.DeleteEstimateTemplateData['body']): Promise<T.DeleteEstimateTemplateResponses[keyof T.DeleteEstimateTemplateResponses]> {
    return this.transport.request<T.DeleteEstimateTemplateResponses[keyof T.DeleteEstimateTemplateResponses]>({
      method: "DELETE",
      path: buildPath("/invoices/estimate/template/{templateId}", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Preview Estimate Template */
  async previewEstimateTemplate(params: T.PreviewEstimateTemplateData['query']): Promise<T.PreviewEstimateTemplateResponses[keyof T.PreviewEstimateTemplateResponses]> {
    return this.transport.request<T.PreviewEstimateTemplateResponses[keyof T.PreviewEstimateTemplateResponses]>({
      method: "GET",
      path: "/invoices/estimate/template/preview",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "altId": (params as unknown as Record<string, any>)["altId"],
        "altType": (params as unknown as Record<string, any>)["altType"],
        "templateId": (params as unknown as Record<string, any>)["templateId"],
      },
    });
  }

  /** List invoices */
  async listInvoices(params: T.ListInvoicesData['query']): Promise<T.ListInvoicesResponses[keyof T.ListInvoicesResponses]> {
    return this.transport.request<T.ListInvoicesResponses[keyof T.ListInvoicesResponses]>({
      method: "GET",
      path: "/invoices/",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "altId": (params as unknown as Record<string, any>)["altId"],
        "altType": (params as unknown as Record<string, any>)["altType"],
        "status": (params as unknown as Record<string, any>)["status"],
        "startAt": (params as unknown as Record<string, any>)["startAt"],
        "endAt": (params as unknown as Record<string, any>)["endAt"],
        "search": (params as unknown as Record<string, any>)["search"],
        "paymentMode": (params as unknown as Record<string, any>)["paymentMode"],
        "contactId": (params as unknown as Record<string, any>)["contactId"],
        "limit": (params as unknown as Record<string, any>)["limit"],
        "offset": (params as unknown as Record<string, any>)["offset"],
        "sortField": (params as unknown as Record<string, any>)["sortField"],
        "sortOrder": (params as unknown as Record<string, any>)["sortOrder"],
      },
    });
  }

  /** Create Invoice */
  async createInvoice(params: T.CreateInvoiceData['body']): Promise<T.CreateInvoiceResponses[keyof T.CreateInvoiceResponses]> {
    return this.transport.request<T.CreateInvoiceResponses[keyof T.CreateInvoiceResponses]>({
      method: "POST",
      path: "/invoices/",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }
}
