// AUTO-GENERATED by scripts/generate-resources.ts — do not edit directly.
// Re-run `npm run generate` after updating the specs submodule.
import type { HttpTransport } from '../../http/transport.js';
import { buildPath } from '../shared/build-path.js';
import type * as T from './generated/types.gen.js';

export class BrandBoardsResource {
  constructor(private readonly transport: HttpTransport) {}

  /** Get Brand Boards */
  async getBrandBoardsByLocation(params: T.GetBrandBoardsByLocationData['path'] & T.GetBrandBoardsByLocationData['query']): Promise<T.GetBrandBoardsByLocationResponses[keyof T.GetBrandBoardsByLocationResponses]> {
    return this.transport.request<T.GetBrandBoardsByLocationResponses[keyof T.GetBrandBoardsByLocationResponses]>({
      method: "GET",
      path: buildPath("/brand-boards/{locationId}", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "limit": (params as unknown as Record<string, any>)["limit"],
        "offset": (params as unknown as Record<string, any>)["offset"],
        "search": (params as unknown as Record<string, any>)["search"],
        "deleted": (params as unknown as Record<string, any>)["deleted"],
      },
    });
  }

  /** Get Brand Board */
  async getBrandBoardById(params: T.GetBrandBoardByIdData['path']): Promise<T.GetBrandBoardByIdResponses[keyof T.GetBrandBoardByIdResponses]> {
    return this.transport.request<T.GetBrandBoardByIdResponses[keyof T.GetBrandBoardByIdResponses]>({
      method: "GET",
      path: buildPath("/brand-boards/{locationId}/{id}", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** Update a Brand Board */
  async updateBrandBoard(params: T.UpdateBrandBoardData['path'] & T.UpdateBrandBoardData['body']): Promise<T.UpdateBrandBoardResponses[keyof T.UpdateBrandBoardResponses]> {
    return this.transport.request<T.UpdateBrandBoardResponses[keyof T.UpdateBrandBoardResponses]>({
      method: "PATCH",
      path: buildPath("/brand-boards/{locationId}/{id}", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Delete a Brand Board */
  async deleteBrandBoard(params: T.DeleteBrandBoardData['path']): Promise<T.DeleteBrandBoardResponses[keyof T.DeleteBrandBoardResponses]> {
    return this.transport.request<T.DeleteBrandBoardResponses[keyof T.DeleteBrandBoardResponses]>({
      method: "DELETE",
      path: buildPath("/brand-boards/{locationId}/{id}", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** Create a new brand board */
  async createBrandBoard(params: T.CreateBrandBoardData['body']): Promise<T.CreateBrandBoardResponses[keyof T.CreateBrandBoardResponses]> {
    return this.transport.request<T.CreateBrandBoardResponses[keyof T.CreateBrandBoardResponses]>({
      method: "POST",
      path: "/brand-boards/",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }
}
