// AUTO-GENERATED by scripts/generate-resources.ts — do not edit directly.
// Re-run `npm run generate` after updating the specs submodule.
import type { HttpTransport } from '../../http/transport.js';
import type * as T from './generated/types.gen.js';

export class BlogsResource {
  constructor(private readonly transport: HttpTransport) {}

  /** Check url slug */
  async checkUrlSlugExists(params: T.CheckUrlSlugExistsData['query']): Promise<T.CheckUrlSlugExistsResponses[keyof T.CheckUrlSlugExistsResponses]> {
    return this.transport.request<T.CheckUrlSlugExistsResponses[keyof T.CheckUrlSlugExistsResponses]>({
      method: "GET",
      path: "/blogs/posts/url-slug-exists",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "urlSlug": (params as unknown as Record<string, any>)["urlSlug"],
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "postId": (params as unknown as Record<string, any>)["postId"],
      },
    });
  }

  /** Update Blog Post */
  async updateBlogPost(params: T.UpdateBlogPostData['body']): Promise<T.UpdateBlogPostResponses[keyof T.UpdateBlogPostResponses]> {
    return this.transport.request<T.UpdateBlogPostResponses[keyof T.UpdateBlogPostResponses]>({
      method: "PUT",
      path: "/blogs/posts/{postId}",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Create Blog Post */
  async createBlogPost(params: T.CreateBlogPostData['body']): Promise<T.CreateBlogPostResponses[keyof T.CreateBlogPostResponses]> {
    return this.transport.request<T.CreateBlogPostResponses[keyof T.CreateBlogPostResponses]>({
      method: "POST",
      path: "/blogs/posts",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Get all authors */
  async getAllBlogAuthorsByLocation(params: T.GetAllBlogAuthorsByLocationData['query']): Promise<T.GetAllBlogAuthorsByLocationResponses[keyof T.GetAllBlogAuthorsByLocationResponses]> {
    return this.transport.request<T.GetAllBlogAuthorsByLocationResponses[keyof T.GetAllBlogAuthorsByLocationResponses]>({
      method: "GET",
      path: "/blogs/authors",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "limit": (params as unknown as Record<string, any>)["limit"],
        "offset": (params as unknown as Record<string, any>)["offset"],
      },
    });
  }

  /** Get all categories */
  async getAllCategoriesByLocation(params: T.GetAllCategoriesByLocationData['query']): Promise<T.GetAllCategoriesByLocationResponses[keyof T.GetAllCategoriesByLocationResponses]> {
    return this.transport.request<T.GetAllCategoriesByLocationResponses[keyof T.GetAllCategoriesByLocationResponses]>({
      method: "GET",
      path: "/blogs/categories",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "limit": (params as unknown as Record<string, any>)["limit"],
        "offset": (params as unknown as Record<string, any>)["offset"],
      },
    });
  }

  /** Get Blog posts by Blog ID */
  async getBlogPost(params: T.GetBlogPostData['query']): Promise<T.GetBlogPostResponses[keyof T.GetBlogPostResponses]> {
    return this.transport.request<T.GetBlogPostResponses[keyof T.GetBlogPostResponses]>({
      method: "GET",
      path: "/blogs/posts/all",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "blogId": (params as unknown as Record<string, any>)["blogId"],
        "limit": (params as unknown as Record<string, any>)["limit"],
        "offset": (params as unknown as Record<string, any>)["offset"],
        "searchTerm": (params as unknown as Record<string, any>)["searchTerm"],
        "status": (params as unknown as Record<string, any>)["status"],
      },
    });
  }

  /** Get Blogs by Location ID */
  async getBlogs(params: T.GetBlogsData['query']): Promise<T.GetBlogsResponses[keyof T.GetBlogsResponses]> {
    return this.transport.request<T.GetBlogsResponses[keyof T.GetBlogsResponses]>({
      method: "GET",
      path: "/blogs/site/all",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "skip": (params as unknown as Record<string, any>)["skip"],
        "limit": (params as unknown as Record<string, any>)["limit"],
        "searchTerm": (params as unknown as Record<string, any>)["searchTerm"],
      },
    });
  }
}
