// AUTO-GENERATED by scripts/generate-resources.ts — do not edit directly.
// Re-run `npm run generate` after updating the specs submodule.
import type { HttpTransport } from '../../http/transport.js';
import { buildPath } from '../shared/build-path.js';
import type * as T from './generated/types.gen.js';

export class AffiliateManagerResource {
  constructor(private readonly transport: HttpTransport) {}

  /** List Affiliates */
  async listAffiliates(params: T.ListAffiliatesData['path'] & T.ListAffiliatesData['query']): Promise<T.ListAffiliatesResponses[keyof T.ListAffiliatesResponses]> {
    return this.transport.request<T.ListAffiliatesResponses[keyof T.ListAffiliatesResponses]>({
      method: "GET",
      path: buildPath("/affiliate-manager/{locationId}/affiliates", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "query": (params as unknown as Record<string, any>)["query"],
        "active": (params as unknown as Record<string, any>)["active"],
        "campaignId": (params as unknown as Record<string, any>)["campaignId"],
        "skip": (params as unknown as Record<string, any>)["skip"],
        "limit": (params as unknown as Record<string, any>)["limit"],
        "fromDate": (params as unknown as Record<string, any>)["fromDate"],
        "toDate": (params as unknown as Record<string, any>)["toDate"],
      },
    });
  }

  /** Get Affiliate */
  async getAffiliate(params: T.GetAffiliateData['path']): Promise<T.GetAffiliateResponses[keyof T.GetAffiliateResponses]> {
    return this.transport.request<T.GetAffiliateResponses[keyof T.GetAffiliateResponses]>({
      method: "GET",
      path: buildPath("/affiliate-manager/{locationId}/affiliates/{affiliateId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** List Payouts */
  async listPayouts(params: T.ListPayoutsData['path'] & T.ListPayoutsData['query']): Promise<T.ListPayoutsResponses[keyof T.ListPayoutsResponses]> {
    return this.transport.request<T.ListPayoutsResponses[keyof T.ListPayoutsResponses]>({
      method: "GET",
      path: buildPath("/affiliate-manager/{locationId}/payouts", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "status": (params as unknown as Record<string, any>)["status"],
        "query": (params as unknown as Record<string, any>)["query"],
        "affiliateId": (params as unknown as Record<string, any>)["affiliateId"],
        "campaignId": (params as unknown as Record<string, any>)["campaignId"],
        "skip": (params as unknown as Record<string, any>)["skip"],
        "limit": (params as unknown as Record<string, any>)["limit"],
        "start": (params as unknown as Record<string, any>)["start"],
        "end": (params as unknown as Record<string, any>)["end"],
      },
    });
  }

  /** List Commissions */
  async listCommissions(params: T.ListCommissionsData['path'] & T.ListCommissionsData['query']): Promise<T.ListCommissionsResponses[keyof T.ListCommissionsResponses]> {
    return this.transport.request<T.ListCommissionsResponses[keyof T.ListCommissionsResponses]>({
      method: "GET",
      path: buildPath("/affiliate-manager/{locationId}/commissions", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "campaignId": (params as unknown as Record<string, any>)["campaignId"],
        "affiliateId": (params as unknown as Record<string, any>)["affiliateId"],
        "status": (params as unknown as Record<string, any>)["status"],
        "query": (params as unknown as Record<string, any>)["query"],
        "skip": (params as unknown as Record<string, any>)["skip"],
        "limit": (params as unknown as Record<string, any>)["limit"],
        "fromDate": (params as unknown as Record<string, any>)["fromDate"],
        "toDate": (params as unknown as Record<string, any>)["toDate"],
      },
    });
  }
}
