// AUTO-GENERATED by scripts/generate-resources.ts — do not edit directly.
// Re-run `npm run generate` after updating the specs submodule.
import type { HttpTransport } from '../../http/transport.js';
import type * as T from './generated/types.gen.js';

export class SurveysResource {
  constructor(private readonly transport: HttpTransport) {}

  /** Get Surveys Submissions */
  async getSurveysSubmissions(params: T.GetSurveysSubmissionsData['query']): Promise<T.GetSurveysSubmissionsResponses[keyof T.GetSurveysSubmissionsResponses]> {
    return this.transport.request<T.GetSurveysSubmissionsResponses[keyof T.GetSurveysSubmissionsResponses]>({
      method: "GET",
      path: "/surveys/submissions",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "page": (params as unknown as Record<string, any>)["page"],
        "limit": (params as unknown as Record<string, any>)["limit"],
        "surveyId": (params as unknown as Record<string, any>)["surveyId"],
        "q": (params as unknown as Record<string, any>)["q"],
        "startAt": (params as unknown as Record<string, any>)["startAt"],
        "endAt": (params as unknown as Record<string, any>)["endAt"],
      },
    });
  }

  /** Get Surveys */
  async getSurveys(params: T.GetSurveysData['query']): Promise<T.GetSurveysResponses[keyof T.GetSurveysResponses]> {
    return this.transport.request<T.GetSurveysResponses[keyof T.GetSurveysResponses]>({
      method: "GET",
      path: "/surveys/",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "skip": (params as unknown as Record<string, any>)["skip"],
        "limit": (params as unknown as Record<string, any>)["limit"],
        "type": (params as unknown as Record<string, any>)["type"],
      },
    });
  }
}
