// AUTO-GENERATED by scripts/generate-resources.ts — do not edit directly.
// Re-run `npm run generate` after updating the specs submodule.
import type { HttpTransport } from '../../http/transport.js';
import { buildPath } from '../shared/build-path.js';
import type * as T from './generated/types.gen.js';

export class StoreResource {
  constructor(private readonly transport: HttpTransport) {}

  /** List Shipping Zones */
  async listShippingZones(params: T.ListShippingZonesData['query']): Promise<T.ListShippingZonesResponses[keyof T.ListShippingZonesResponses]> {
    return this.transport.request<T.ListShippingZonesResponses[keyof T.ListShippingZonesResponses]>({
      method: "GET",
      path: "/store/shipping-zone",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "altId": (params as unknown as Record<string, any>)["altId"],
        "altType": (params as unknown as Record<string, any>)["altType"],
        "limit": (params as unknown as Record<string, any>)["limit"],
        "offset": (params as unknown as Record<string, any>)["offset"],
        "withShippingRate": (params as unknown as Record<string, any>)["withShippingRate"],
      },
    });
  }

  /** Create Shipping Zone */
  async createShippingZone(params: T.CreateShippingZoneData['body']): Promise<T.CreateShippingZoneResponses[keyof T.CreateShippingZoneResponses]> {
    return this.transport.request<T.CreateShippingZoneResponses[keyof T.CreateShippingZoneResponses]>({
      method: "POST",
      path: "/store/shipping-zone",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Get Shipping Zone */
  async getShippingZones(params: T.GetShippingZonesData['path'] & T.GetShippingZonesData['query']): Promise<T.GetShippingZonesResponses[keyof T.GetShippingZonesResponses]> {
    return this.transport.request<T.GetShippingZonesResponses[keyof T.GetShippingZonesResponses]>({
      method: "GET",
      path: buildPath("/store/shipping-zone/{shippingZoneId}", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "altId": (params as unknown as Record<string, any>)["altId"],
        "altType": (params as unknown as Record<string, any>)["altType"],
        "withShippingRate": (params as unknown as Record<string, any>)["withShippingRate"],
      },
    });
  }

  /** Update Shipping Zone */
  async updateShippingZone(params: T.UpdateShippingZoneData['path'] & T.UpdateShippingZoneData['body']): Promise<T.UpdateShippingZoneResponses[keyof T.UpdateShippingZoneResponses]> {
    return this.transport.request<T.UpdateShippingZoneResponses[keyof T.UpdateShippingZoneResponses]>({
      method: "PUT",
      path: buildPath("/store/shipping-zone/{shippingZoneId}", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Delete shipping zone */
  async deleteShippingZone(params: T.DeleteShippingZoneData['path'] & T.DeleteShippingZoneData['query']): Promise<T.DeleteShippingZoneResponses[keyof T.DeleteShippingZoneResponses]> {
    return this.transport.request<T.DeleteShippingZoneResponses[keyof T.DeleteShippingZoneResponses]>({
      method: "DELETE",
      path: buildPath("/store/shipping-zone/{shippingZoneId}", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "altId": (params as unknown as Record<string, any>)["altId"],
        "altType": (params as unknown as Record<string, any>)["altType"],
      },
    });
  }

  /** Get available shipping rates */
  async getAvailableShippingZones(params: T.GetAvailableShippingZonesData['body']): Promise<T.GetAvailableShippingZonesResponses[keyof T.GetAvailableShippingZonesResponses]> {
    return this.transport.request<T.GetAvailableShippingZonesResponses[keyof T.GetAvailableShippingZonesResponses]>({
      method: "POST",
      path: "/store/shipping-zone/shipping-rates",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** List Shipping Rates */
  async listShippingRates(params: T.ListShippingRatesData['path'] & T.ListShippingRatesData['query']): Promise<T.ListShippingRatesResponses[keyof T.ListShippingRatesResponses]> {
    return this.transport.request<T.ListShippingRatesResponses[keyof T.ListShippingRatesResponses]>({
      method: "GET",
      path: buildPath("/store/shipping-zone/{shippingZoneId}/shipping-rate", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "altId": (params as unknown as Record<string, any>)["altId"],
        "altType": (params as unknown as Record<string, any>)["altType"],
        "limit": (params as unknown as Record<string, any>)["limit"],
        "offset": (params as unknown as Record<string, any>)["offset"],
      },
    });
  }

  /** Create Shipping Rate */
  async createShippingRate(params: T.CreateShippingRateData['path'] & T.CreateShippingRateData['body']): Promise<T.CreateShippingRateResponses[keyof T.CreateShippingRateResponses]> {
    return this.transport.request<T.CreateShippingRateResponses[keyof T.CreateShippingRateResponses]>({
      method: "POST",
      path: buildPath("/store/shipping-zone/{shippingZoneId}/shipping-rate", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Get Shipping Rate */
  async getShippingRates(params: T.GetShippingRatesData['path'] & T.GetShippingRatesData['query']): Promise<T.GetShippingRatesResponses[keyof T.GetShippingRatesResponses]> {
    return this.transport.request<T.GetShippingRatesResponses[keyof T.GetShippingRatesResponses]>({
      method: "GET",
      path: buildPath("/store/shipping-zone/{shippingZoneId}/shipping-rate/{shippingRateId}", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "altId": (params as unknown as Record<string, any>)["altId"],
        "altType": (params as unknown as Record<string, any>)["altType"],
      },
    });
  }

  /** Update Shipping Rate */
  async updateShippingRate(params: T.UpdateShippingRateData['path'] & T.UpdateShippingRateData['body']): Promise<T.UpdateShippingRateResponses[keyof T.UpdateShippingRateResponses]> {
    return this.transport.request<T.UpdateShippingRateResponses[keyof T.UpdateShippingRateResponses]>({
      method: "PUT",
      path: buildPath("/store/shipping-zone/{shippingZoneId}/shipping-rate/{shippingRateId}", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Delete shipping rate */
  async deleteShippingRate(params: T.DeleteShippingRateData['path'] & T.DeleteShippingRateData['query']): Promise<T.DeleteShippingRateResponses[keyof T.DeleteShippingRateResponses]> {
    return this.transport.request<T.DeleteShippingRateResponses[keyof T.DeleteShippingRateResponses]>({
      method: "DELETE",
      path: buildPath("/store/shipping-zone/{shippingZoneId}/shipping-rate/{shippingRateId}", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "altId": (params as unknown as Record<string, any>)["altId"],
        "altType": (params as unknown as Record<string, any>)["altType"],
      },
    });
  }

  /** List Shipping Carriers */
  async listShippingCarriers(params: T.ListShippingCarriersData['query']): Promise<T.ListShippingCarriersResponses[keyof T.ListShippingCarriersResponses]> {
    return this.transport.request<T.ListShippingCarriersResponses[keyof T.ListShippingCarriersResponses]>({
      method: "GET",
      path: "/store/shipping-carrier",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "altId": (params as unknown as Record<string, any>)["altId"],
        "altType": (params as unknown as Record<string, any>)["altType"],
      },
    });
  }

  /** Create Shipping Carrier */
  async createShippingCarrier(params: T.CreateShippingCarrierData['body']): Promise<T.CreateShippingCarrierResponses[keyof T.CreateShippingCarrierResponses]> {
    return this.transport.request<T.CreateShippingCarrierResponses[keyof T.CreateShippingCarrierResponses]>({
      method: "POST",
      path: "/store/shipping-carrier",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Get Shipping Carrier */
  async getShippingCarriers(params: T.GetShippingCarriersData['path'] & T.GetShippingCarriersData['query']): Promise<T.GetShippingCarriersResponses[keyof T.GetShippingCarriersResponses]> {
    return this.transport.request<T.GetShippingCarriersResponses[keyof T.GetShippingCarriersResponses]>({
      method: "GET",
      path: buildPath("/store/shipping-carrier/{shippingCarrierId}", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "altId": (params as unknown as Record<string, any>)["altId"],
        "altType": (params as unknown as Record<string, any>)["altType"],
      },
    });
  }

  /** Update Shipping Carrier */
  async updateShippingCarrier(params: T.UpdateShippingCarrierData['path'] & T.UpdateShippingCarrierData['body']): Promise<T.UpdateShippingCarrierResponses[keyof T.UpdateShippingCarrierResponses]> {
    return this.transport.request<T.UpdateShippingCarrierResponses[keyof T.UpdateShippingCarrierResponses]>({
      method: "PUT",
      path: buildPath("/store/shipping-carrier/{shippingCarrierId}", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Delete shipping carrier */
  async deleteShippingCarrier(params: T.DeleteShippingCarrierData['path'] & T.DeleteShippingCarrierData['query']): Promise<T.DeleteShippingCarrierResponses[keyof T.DeleteShippingCarrierResponses]> {
    return this.transport.request<T.DeleteShippingCarrierResponses[keyof T.DeleteShippingCarrierResponses]>({
      method: "DELETE",
      path: buildPath("/store/shipping-carrier/{shippingCarrierId}", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "altId": (params as unknown as Record<string, any>)["altId"],
        "altType": (params as unknown as Record<string, any>)["altType"],
      },
    });
  }

  /** Get Store Settings */
  async getStoreSettings(params: T.GetStoreSettingsData['query']): Promise<T.GetStoreSettingsResponses[keyof T.GetStoreSettingsResponses]> {
    return this.transport.request<T.GetStoreSettingsResponses[keyof T.GetStoreSettingsResponses]>({
      method: "GET",
      path: "/store/store-setting",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "altId": (params as unknown as Record<string, any>)["altId"],
        "altType": (params as unknown as Record<string, any>)["altType"],
      },
    });
  }

  /** Create/Update Store Settings */
  async createStoreSetting(params: T.CreateStoreSettingData['body']): Promise<T.CreateStoreSettingResponses[keyof T.CreateStoreSettingResponses]> {
    return this.transport.request<T.CreateStoreSettingResponses[keyof T.CreateStoreSettingResponses]>({
      method: "POST",
      path: "/store/store-setting",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }
}
