// AUTO-GENERATED by scripts/generate-resources.ts — do not edit directly.
// Re-run `npm run generate` after updating the specs submodule.
import type { HttpTransport } from '../../http/transport.js';
import type * as T from './generated/types.gen.js';

export class CampaignsResource {
  constructor(private readonly transport: HttpTransport) {}

  /** Get Campaigns */
  async getCampaigns(params: T.GetCampaignsData['query']): Promise<T.GetCampaignsResponses[keyof T.GetCampaignsResponses]> {
    return this.transport.request<T.GetCampaignsResponses[keyof T.GetCampaignsResponses]>({
      method: "GET",
      path: "/campaigns/",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "status": (params as unknown as Record<string, any>)["status"],
      },
    });
  }
}
