// AUTO-GENERATED by scripts/generate-resources.ts — do not edit directly.
// Re-run `npm run generate` after updating the specs submodule.
import type { HttpTransport } from '../../http/transport.js';
import { buildPath } from '../shared/build-path.js';
import type * as T from './generated/types.gen.js';

export class OpportunitiesResource {
  constructor(private readonly transport: HttpTransport) {}

  /** Get lost reason */
  async getLostReason(params: T.GetLostReasonData['query']): Promise<T.GetLostReasonResponses[keyof T.GetLostReasonResponses]> {
    return this.transport.request<T.GetLostReasonResponses[keyof T.GetLostReasonResponses]>({
      method: "GET",
      path: "/opportunities/lost-reason",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "name": (params as unknown as Record<string, any>)["name"],
        "deleted": (params as unknown as Record<string, any>)["deleted"],
        "query": (params as unknown as Record<string, any>)["query"],
        "skip": (params as unknown as Record<string, any>)["skip"],
        "limit": (params as unknown as Record<string, any>)["limit"],
        "getCount": (params as unknown as Record<string, any>)["getCount"],
      },
    });
  }

  /** Search Opportunity */
  async searchOpportunity(params: T.SearchOpportunityData['query']): Promise<T.SearchOpportunityResponses[keyof T.SearchOpportunityResponses]> {
    return this.transport.request<T.SearchOpportunityResponses[keyof T.SearchOpportunityResponses]>({
      method: "GET",
      path: "/opportunities/search",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "q": (params as unknown as Record<string, any>)["q"],
        "location_id": (params as unknown as Record<string, any>)["location_id"],
        "pipeline_id": (params as unknown as Record<string, any>)["pipeline_id"],
        "pipeline_stage_id": (params as unknown as Record<string, any>)["pipeline_stage_id"],
        "contact_id": (params as unknown as Record<string, any>)["contact_id"],
        "status": (params as unknown as Record<string, any>)["status"],
        "assigned_to": (params as unknown as Record<string, any>)["assigned_to"],
        "campaignId": (params as unknown as Record<string, any>)["campaignId"],
        "id": (params as unknown as Record<string, any>)["id"],
        "order": (params as unknown as Record<string, any>)["order"],
        "endDate": (params as unknown as Record<string, any>)["endDate"],
        "startAfter": (params as unknown as Record<string, any>)["startAfter"],
        "startAfterId": (params as unknown as Record<string, any>)["startAfterId"],
        "date": (params as unknown as Record<string, any>)["date"],
        "country": (params as unknown as Record<string, any>)["country"],
        "page": (params as unknown as Record<string, any>)["page"],
        "limit": (params as unknown as Record<string, any>)["limit"],
        "getTasks": (params as unknown as Record<string, any>)["getTasks"],
        "getNotes": (params as unknown as Record<string, any>)["getNotes"],
        "getCalendarEvents": (params as unknown as Record<string, any>)["getCalendarEvents"],
      },
    });
  }

  /** Search Opportunities */
  async searchOpportunitiesAdvanced(params: T.SearchOpportunitiesAdvancedData['body']): Promise<T.SearchOpportunitiesAdvancedResponses[keyof T.SearchOpportunitiesAdvancedResponses]> {
    return this.transport.request<T.SearchOpportunitiesAdvancedResponses[keyof T.SearchOpportunitiesAdvancedResponses]>({
      method: "POST",
      path: "/opportunities/search",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Get Pipelines */
  async getPipelines(params: T.GetPipelinesData['query']): Promise<T.GetPipelinesResponses[keyof T.GetPipelinesResponses]> {
    return this.transport.request<T.GetPipelinesResponses[keyof T.GetPipelinesResponses]>({
      method: "GET",
      path: "/opportunities/pipelines",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
      },
    });
  }

  /** Get Opportunity */
  async getOpportunity(params: T.GetOpportunityData['path']): Promise<T.GetOpportunityResponses[keyof T.GetOpportunityResponses]> {
    return this.transport.request<T.GetOpportunityResponses[keyof T.GetOpportunityResponses]>({
      method: "GET",
      path: buildPath("/opportunities/{id}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** Update Opportunity */
  async updateOpportunity(params: T.UpdateOpportunityData['path'] & T.UpdateOpportunityData['body']): Promise<T.UpdateOpportunityResponses[keyof T.UpdateOpportunityResponses]> {
    return this.transport.request<T.UpdateOpportunityResponses[keyof T.UpdateOpportunityResponses]>({
      method: "PUT",
      path: buildPath("/opportunities/{id}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Delete Opportunity */
  async deleteOpportunity(params: T.DeleteOpportunityData['path']): Promise<T.DeleteOpportunityResponses[keyof T.DeleteOpportunityResponses]> {
    return this.transport.request<T.DeleteOpportunityResponses[keyof T.DeleteOpportunityResponses]>({
      method: "DELETE",
      path: buildPath("/opportunities/{id}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** Update Opportunity Status */
  async updateOpportunityStatus(params: T.UpdateOpportunityStatusData['path'] & T.UpdateOpportunityStatusData['body']): Promise<T.UpdateOpportunityStatusResponses[keyof T.UpdateOpportunityStatusResponses]> {
    return this.transport.request<T.UpdateOpportunityStatusResponses[keyof T.UpdateOpportunityStatusResponses]>({
      method: "PUT",
      path: buildPath("/opportunities/{id}/status", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Upsert Opportunity */
  async upsertOpportunity(params: T.UpsertOpportunityData['body']): Promise<T.UpsertOpportunityResponses[keyof T.UpsertOpportunityResponses]> {
    return this.transport.request<T.UpsertOpportunityResponses[keyof T.UpsertOpportunityResponses]>({
      method: "POST",
      path: "/opportunities/upsert",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Add Followers */
  async addFollowersOpportunity(params: T.AddFollowersOpportunityData['path'] & T.AddFollowersOpportunityData['body']): Promise<T.AddFollowersOpportunityResponses[keyof T.AddFollowersOpportunityResponses]> {
    return this.transport.request<T.AddFollowersOpportunityResponses[keyof T.AddFollowersOpportunityResponses]>({
      method: "POST",
      path: buildPath("/opportunities/{id}/followers", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Remove Followers */
  async removeFollowersOpportunity(params: T.RemoveFollowersOpportunityData['path'] & T.RemoveFollowersOpportunityData['query'] & T.RemoveFollowersOpportunityData['body']): Promise<T.RemoveFollowersOpportunityResponses[keyof T.RemoveFollowersOpportunityResponses]> {
    return this.transport.request<T.RemoveFollowersOpportunityResponses[keyof T.RemoveFollowersOpportunityResponses]>({
      method: "DELETE",
      path: buildPath("/opportunities/{id}/followers", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "isRemoveAllFollowers": (params as unknown as Record<string, any>)["isRemoveAllFollowers"],
      },
      body: params,
    });
  }

  /** Create Opportunity */
  async createOpportunity(params: T.CreateOpportunityData['body']): Promise<T.CreateOpportunityResponses[keyof T.CreateOpportunityResponses]> {
    return this.transport.request<T.CreateOpportunityResponses[keyof T.CreateOpportunityResponses]>({
      method: "POST",
      path: "/opportunities/",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }
}
