// AUTO-GENERATED by scripts/generate-resources.ts — do not edit directly.
// Re-run `npm run generate` after updating the specs submodule.
import type { HttpTransport } from '../../http/transport.js';
import { buildPath } from '../shared/build-path.js';
import type * as T from './generated/types.gen.js';

export class AgentStudioResource {
  constructor(private readonly transport: HttpTransport) {}

  /** List Agents */
  async getAgents(params: T.GetAgentsData['query']): Promise<T.GetAgentsResponses[keyof T.GetAgentsResponses]> {
    return this.transport.request<T.GetAgentsResponses[keyof T.GetAgentsResponses]>({
      method: "GET",
      path: "/agent-studio/agent",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "isPublished": (params as unknown as Record<string, any>)["isPublished"],
        "limit": (params as unknown as Record<string, any>)["limit"],
        "offset": (params as unknown as Record<string, any>)["offset"],
        "source": (params as unknown as Record<string, any>)["source"],
      },
    });
  }

  /** Create Agent */
  async createAgent(params: T.CreateAgentData['query'] & T.CreateAgentData['body']): Promise<T.CreateAgentResponses[keyof T.CreateAgentResponses]> {
    return this.transport.request<T.CreateAgentResponses[keyof T.CreateAgentResponses]>({
      method: "POST",
      path: "/agent-studio/agent",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "source": (params as unknown as Record<string, any>)["source"],
      },
      body: params,
    });
  }

  /** Update Agent */
  async updateAgentVersion(params: T.UpdateAgentVersionData['path'] & T.UpdateAgentVersionData['query'] & T.UpdateAgentVersionData['body']): Promise<T.UpdateAgentVersionResponses[keyof T.UpdateAgentVersionResponses]> {
    return this.transport.request<T.UpdateAgentVersionResponses[keyof T.UpdateAgentVersionResponses]>({
      method: "PATCH",
      path: buildPath("/agent-studio/agent/versions/{versionId}", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "source": (params as unknown as Record<string, any>)["source"],
      },
      body: params,
    });
  }

  /** Get Agent */
  async getAgentById(params: T.GetAgentByIdData['path'] & T.GetAgentByIdData['query']): Promise<T.GetAgentByIdResponses[keyof T.GetAgentByIdResponses]> {
    return this.transport.request<T.GetAgentByIdResponses[keyof T.GetAgentByIdResponses]>({
      method: "GET",
      path: buildPath("/agent-studio/agent/{agentId}", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "source": (params as unknown as Record<string, any>)["source"],
      },
    });
  }

  /** Update Agent Metadata */
  async updateAgentMetadata(params: T.UpdateAgentMetadataData['path'] & T.UpdateAgentMetadataData['query'] & T.UpdateAgentMetadataData['body']): Promise<T.UpdateAgentMetadataResponses[keyof T.UpdateAgentMetadataResponses]> {
    return this.transport.request<T.UpdateAgentMetadataResponses[keyof T.UpdateAgentMetadataResponses]>({
      method: "PATCH",
      path: buildPath("/agent-studio/agent/{agentId}", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "source": (params as unknown as Record<string, any>)["source"],
      },
      body: params,
    });
  }

  /** Delete Agent */
  async deleteAgent(params: T.DeleteAgentData['path'] & T.DeleteAgentData['query']): Promise<T.DeleteAgentResponses[keyof T.DeleteAgentResponses]> {
    return this.transport.request<T.DeleteAgentResponses[keyof T.DeleteAgentResponses]>({
      method: "DELETE",
      path: buildPath("/agent-studio/agent/{agentId}", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "source": (params as unknown as Record<string, any>)["source"],
      },
    });
  }

  /** Promote to Production */
  async promoteAndPublish(params: T.PromoteAndPublishData['path'] & T.PromoteAndPublishData['query'] & T.PromoteAndPublishData['body']): Promise<T.PromoteAndPublishResponses[keyof T.PromoteAndPublishResponses]> {
    return this.transport.request<T.PromoteAndPublishResponses[keyof T.PromoteAndPublishResponses]>({
      method: "POST",
      path: buildPath("/agent-studio/agent/versions/{versionId}/publish", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "source": (params as unknown as Record<string, any>)["source"],
      },
      body: params,
    });
  }

  /** Execute Agent */
  async executeAgent(params: T.ExecuteAgentData['path'] & T.ExecuteAgentData['query'] & T.ExecuteAgentData['body']): Promise<T.ExecuteAgentResponses[keyof T.ExecuteAgentResponses]> {
    return this.transport.request<T.ExecuteAgentResponses[keyof T.ExecuteAgentResponses]>({
      method: "POST",
      path: buildPath("/agent-studio/agent/{agentId}/execute", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "source": (params as unknown as Record<string, any>)["source"],
      },
      body: params,
    });
  }

  /** List Agents (Deprecated) */
  async getAgentsDeprecated(params: T.GetAgentsDeprecatedData['query']): Promise<T.GetAgentsDeprecatedResponses[keyof T.GetAgentsDeprecatedResponses]> {
    return this.transport.request<T.GetAgentsDeprecatedResponses[keyof T.GetAgentsDeprecatedResponses]>({
      method: "GET",
      path: "/agent-studio/public-api/agents",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "limit": (params as unknown as Record<string, any>)["limit"],
        "offset": (params as unknown as Record<string, any>)["offset"],
        "source": (params as unknown as Record<string, any>)["source"],
      },
    });
  }

  /** Get Agent (Deprecated) */
  async getAgentByIdDeprecated(params: T.GetAgentByIdDeprecatedData['path'] & T.GetAgentByIdDeprecatedData['query']): Promise<T.GetAgentByIdDeprecatedResponses[keyof T.GetAgentByIdDeprecatedResponses]> {
    return this.transport.request<T.GetAgentByIdDeprecatedResponses[keyof T.GetAgentByIdDeprecatedResponses]>({
      method: "GET",
      path: buildPath("/agent-studio/public-api/agents/{agentId}", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "source": (params as unknown as Record<string, any>)["source"],
      },
    });
  }

  /** Execute Agent (Deprecated) */
  async executeAgentDeprecated(params: T.ExecuteAgentDeprecatedData['path'] & T.ExecuteAgentDeprecatedData['query'] & T.ExecuteAgentDeprecatedData['body']): Promise<T.ExecuteAgentDeprecatedResponses[keyof T.ExecuteAgentDeprecatedResponses]> {
    return this.transport.request<T.ExecuteAgentDeprecatedResponses[keyof T.ExecuteAgentDeprecatedResponses]>({
      method: "POST",
      path: buildPath("/agent-studio/public-api/agents/{agentId}/execute", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "source": (params as unknown as Record<string, any>)["source"],
      },
      body: params,
    });
  }
}
