// AUTO-GENERATED by scripts/generate-resources.ts — do not edit directly.
// Re-run `npm run generate` after updating the specs submodule.
import type { HttpTransport } from '../../http/transport.js';
import { buildPath } from '../shared/build-path.js';
import type * as T from './generated/types.gen.js';

export class BusinessesResource {
  constructor(private readonly transport: HttpTransport) {}

  /** Get Business */
  async getBusiness(params: T.GetBusinessData['path']): Promise<T.GetBusinessResponses[keyof T.GetBusinessResponses]> {
    return this.transport.request<T.GetBusinessResponses[keyof T.GetBusinessResponses]>({
      method: "GET",
      path: buildPath("/businesses/{businessId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** Update Business */
  async updateBusiness(params: T.UpdateBusinessData['path'] & T.UpdateBusinessData['body']): Promise<T.UpdateBusinessResponses[keyof T.UpdateBusinessResponses]> {
    return this.transport.request<T.UpdateBusinessResponses[keyof T.UpdateBusinessResponses]>({
      method: "PUT",
      path: buildPath("/businesses/{businessId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Delete Business */
  async deleteBusiness(params: T.DeleteBusinessData['path']): Promise<T.DeleteBusinessResponses[keyof T.DeleteBusinessResponses]> {
    return this.transport.request<T.DeleteBusinessResponses[keyof T.DeleteBusinessResponses]>({
      method: "DELETE",
      path: buildPath("/businesses/{businessId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** Get Businesses by Location */
  async getBusinessesByLocation(params: T.GetBusinessesByLocationData['query']): Promise<T.GetBusinessesByLocationResponses[keyof T.GetBusinessesByLocationResponses]> {
    return this.transport.request<T.GetBusinessesByLocationResponses[keyof T.GetBusinessesByLocationResponses]>({
      method: "GET",
      path: "/businesses/",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "limit": (params as unknown as Record<string, any>)["limit"],
        "skip": (params as unknown as Record<string, any>)["skip"],
      },
    });
  }

  /** Create Business */
  async createBusiness(params: T.CreateBusinessData['body']): Promise<T.CreateBusinessResponses[keyof T.CreateBusinessResponses]> {
    return this.transport.request<T.CreateBusinessResponses[keyof T.CreateBusinessResponses]>({
      method: "POST",
      path: "/businesses/",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }
}
