// AUTO-GENERATED by scripts/generate-resources.ts — do not edit directly.
// Re-run `npm run generate` after updating the specs submodule.
import type { HttpTransport } from '../../http/transport.js';
import { buildPath } from '../shared/build-path.js';
import type * as T from './generated/types.gen.js';

export class ConversationsResource {
  constructor(private readonly transport: HttpTransport) {}

  /** Search Conversations */
  async searchConversation(params: T.SearchConversationData['query']): Promise<T.SearchConversationResponses[keyof T.SearchConversationResponses]> {
    return this.transport.request<T.SearchConversationResponses[keyof T.SearchConversationResponses]>({
      method: "GET",
      path: "/conversations/search",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "contactId": (params as unknown as Record<string, any>)["contactId"],
        "assignedTo": (params as unknown as Record<string, any>)["assignedTo"],
        "followers": (params as unknown as Record<string, any>)["followers"],
        "mentions": (params as unknown as Record<string, any>)["mentions"],
        "query": (params as unknown as Record<string, any>)["query"],
        "sort": (params as unknown as Record<string, any>)["sort"],
        "startAfterDate": (params as unknown as Record<string, any>)["startAfterDate"],
        "id": (params as unknown as Record<string, any>)["id"],
        "limit": (params as unknown as Record<string, any>)["limit"],
        "lastMessageType": (params as unknown as Record<string, any>)["lastMessageType"],
        "lastMessageAction": (params as unknown as Record<string, any>)["lastMessageAction"],
        "lastMessageDirection": (params as unknown as Record<string, any>)["lastMessageDirection"],
        "status": (params as unknown as Record<string, any>)["status"],
        "sortBy": (params as unknown as Record<string, any>)["sortBy"],
        "sortScoreProfile": (params as unknown as Record<string, any>)["sortScoreProfile"],
        "scoreProfile": (params as unknown as Record<string, any>)["scoreProfile"],
        "scoreProfileMin": (params as unknown as Record<string, any>)["scoreProfileMin"],
        "scoreProfileMax": (params as unknown as Record<string, any>)["scoreProfileMax"],
        "startDate": (params as unknown as Record<string, any>)["startDate"],
        "endDate": (params as unknown as Record<string, any>)["endDate"],
      },
    });
  }

  /** Get Conversation */
  async getConversation(params: T.GetConversationData['path']): Promise<T.GetConversationResponses[keyof T.GetConversationResponses]> {
    return this.transport.request<T.GetConversationResponses[keyof T.GetConversationResponses]>({
      method: "GET",
      path: buildPath("/conversations/{conversationId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** Update Conversation */
  async updateConversation(params: T.UpdateConversationData['path'] & T.UpdateConversationData['body']): Promise<T.UpdateConversationResponses[keyof T.UpdateConversationResponses]> {
    return this.transport.request<T.UpdateConversationResponses[keyof T.UpdateConversationResponses]>({
      method: "PUT",
      path: buildPath("/conversations/{conversationId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Delete Conversation */
  async deleteConversation(params: T.DeleteConversationData['path']): Promise<T.DeleteConversationResponses[keyof T.DeleteConversationResponses]> {
    return this.transport.request<T.DeleteConversationResponses[keyof T.DeleteConversationResponses]>({
      method: "DELETE",
      path: buildPath("/conversations/{conversationId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** Get All Custom Subtypes */
  async getAllCustomSubtypes(params: T.GetAllCustomSubtypesData['query']): Promise<void> {
    return this.transport.request<void>({
      method: "GET",
      path: "/conversations/preferences/custom-subtypes",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
      },
    });
  }

  /** Create Custom Subtype */
  async createCustomSubtype(params: T.CreateCustomSubtypeData['query'] & T.CreateCustomSubtypeData['body']): Promise<void> {
    return this.transport.request<void>({
      method: "POST",
      path: "/conversations/preferences/custom-subtypes",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
      },
      body: params,
    });
  }

  /** Update Custom Subtype */
  async updateCustomSubtype(params: T.UpdateCustomSubtypeData['path'] & T.UpdateCustomSubtypeData['query'] & T.UpdateCustomSubtypeData['body']): Promise<void> {
    return this.transport.request<void>({
      method: "PUT",
      path: buildPath("/conversations/preferences/custom-subtypes/{id}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
      },
      body: params,
    });
  }

  /** Get Contact Unsubscription Status */
  async getContactUnsubscriptionStatus(params: T.GetContactUnsubscriptionStatusData['query']): Promise<void> {
    return this.transport.request<void>({
      method: "GET",
      path: "/conversations/preferences/unsubscriptions/status",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "contactId": (params as unknown as Record<string, any>)["contactId"],
        "email": (params as unknown as Record<string, any>)["email"],
      },
    });
  }

  /** User Subscription Change */
  async userSubscriptionChange(params: T.UserSubscriptionChangeData['body']): Promise<void> {
    return this.transport.request<void>({
      method: "POST",
      path: "/conversations/preferences/unsubscriptions/user-change",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Get email by Id */
  async getEmailById(): Promise<T.GetEmailByIdResponses[keyof T.GetEmailByIdResponses]> {
    return this.transport.request<T.GetEmailByIdResponses[keyof T.GetEmailByIdResponses]>({
      method: "GET",
      path: "/conversations/messages/email/{id}",
      securityScheme: "bearer",
      locationId: undefined,
      companyId: undefined,
    });
  }

  /** Cancel a scheduled email message. */
  async cancelScheduledEmailMessage(params: T.CancelScheduledEmailMessageData['path']): Promise<T.CancelScheduledEmailMessageResponses[keyof T.CancelScheduledEmailMessageResponses]> {
    return this.transport.request<T.CancelScheduledEmailMessageResponses[keyof T.CancelScheduledEmailMessageResponses]>({
      method: "DELETE",
      path: buildPath("/conversations/messages/email/{emailMessageId}/schedule", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** Export messages by location ID */
  async exportMessagesByLocation(params: T.ExportMessagesByLocationData['query']): Promise<T.ExportMessagesByLocationResponses[keyof T.ExportMessagesByLocationResponses]> {
    return this.transport.request<T.ExportMessagesByLocationResponses[keyof T.ExportMessagesByLocationResponses]>({
      method: "GET",
      path: "/conversations/messages/export",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "limit": (params as unknown as Record<string, any>)["limit"],
        "cursor": (params as unknown as Record<string, any>)["cursor"],
        "sortBy": (params as unknown as Record<string, any>)["sortBy"],
        "sortOrder": (params as unknown as Record<string, any>)["sortOrder"],
        "conversationId": (params as unknown as Record<string, any>)["conversationId"],
        "contactId": (params as unknown as Record<string, any>)["contactId"],
        "channel": (params as unknown as Record<string, any>)["channel"],
        "startDate": (params as unknown as Record<string, any>)["startDate"],
        "endDate": (params as unknown as Record<string, any>)["endDate"],
      },
    });
  }

  /** Get message by message id */
  async getMessage(): Promise<T.GetMessageResponses[keyof T.GetMessageResponses]> {
    return this.transport.request<T.GetMessageResponses[keyof T.GetMessageResponses]>({
      method: "GET",
      path: "/conversations/messages/{id}",
      securityScheme: "bearer",
      locationId: undefined,
      companyId: undefined,
    });
  }

  /** Get messages by conversation id */
  async getMessages(params: T.GetMessagesData['path'] & T.GetMessagesData['query']): Promise<T.GetMessagesResponses[keyof T.GetMessagesResponses]> {
    return this.transport.request<T.GetMessagesResponses[keyof T.GetMessagesResponses]>({
      method: "GET",
      path: buildPath("/conversations/{conversationId}/messages", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "lastMessageId": (params as unknown as Record<string, any>)["lastMessageId"],
        "limit": (params as unknown as Record<string, any>)["limit"],
        "type": (params as unknown as Record<string, any>)["type"],
      },
    });
  }

  /** Send a new message */
  async sendANewMessage(params: T.SendANewMessageData['body']): Promise<T.SendANewMessageResponses[keyof T.SendANewMessageResponses]> {
    return this.transport.request<T.SendANewMessageResponses[keyof T.SendANewMessageResponses]>({
      method: "POST",
      path: "/conversations/messages",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Add an inbound message */
  async addAnInboundMessage(params: T.AddAnInboundMessageData['body']): Promise<T.AddAnInboundMessageResponses[keyof T.AddAnInboundMessageResponses]> {
    return this.transport.request<T.AddAnInboundMessageResponses[keyof T.AddAnInboundMessageResponses]>({
      method: "POST",
      path: "/conversations/messages/inbound",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Add an external outbound call */
  async addAnOutboundMessage(params: T.AddAnOutboundMessageData['body']): Promise<T.AddAnOutboundMessageResponses[keyof T.AddAnOutboundMessageResponses]> {
    return this.transport.request<T.AddAnOutboundMessageResponses[keyof T.AddAnOutboundMessageResponses]>({
      method: "POST",
      path: "/conversations/messages/outbound",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Send a review reply to Google My Business */
  async sendReviewReply(params: T.SendReviewReplyData['body']): Promise<T.SendReviewReplyResponses[keyof T.SendReviewReplyResponses]> {
    return this.transport.request<T.SendReviewReplyResponses[keyof T.SendReviewReplyResponses]>({
      method: "POST",
      path: "/conversations/messages/review-reply",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Cancel a scheduled message. */
  async cancelScheduledMessage(params: T.CancelScheduledMessageData['path']): Promise<T.CancelScheduledMessageResponses[keyof T.CancelScheduledMessageResponses]> {
    return this.transport.request<T.CancelScheduledMessageResponses[keyof T.CancelScheduledMessageResponses]>({
      method: "DELETE",
      path: buildPath("/conversations/messages/{messageId}/schedule", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** Upload file attachments */
  async uploadFileAttachments(): Promise<T.UploadFileAttachmentsResponses[keyof T.UploadFileAttachmentsResponses]> {
    return this.transport.request<T.UploadFileAttachmentsResponses[keyof T.UploadFileAttachmentsResponses]>({
      method: "POST",
      path: "/conversations/messages/upload",
      securityScheme: "bearer",
      locationId: undefined,
      companyId: undefined,
    });
  }

  /** Initiate file upload to GCS */
  async initiateFileUpload(params: T.InitiateFileUploadData['body']): Promise<T.InitiateFileUploadResponses[keyof T.InitiateFileUploadResponses]> {
    return this.transport.request<T.InitiateFileUploadResponses[keyof T.InitiateFileUploadResponses]>({
      method: "POST",
      path: "/conversations/messages/upload/initiate",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Complete file upload */
  async completeFileUpload(params: T.CompleteFileUploadData['body']): Promise<T.CompleteFileUploadResponses[keyof T.CompleteFileUploadResponses]> {
    return this.transport.request<T.CompleteFileUploadResponses[keyof T.CompleteFileUploadResponses]>({
      method: "POST",
      path: "/conversations/messages/upload/complete",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Update message status */
  async updateMessageStatus(params: T.UpdateMessageStatusData['path'] & T.UpdateMessageStatusData['body']): Promise<T.UpdateMessageStatusResponses[keyof T.UpdateMessageStatusResponses]> {
    return this.transport.request<T.UpdateMessageStatusResponses[keyof T.UpdateMessageStatusResponses]>({
      method: "PUT",
      path: buildPath("/conversations/messages/{messageId}/status", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Add message attachments */
  async addMessageAttachments(params: T.AddMessageAttachmentsData['path'] & T.AddMessageAttachmentsData['body']): Promise<void> {
    return this.transport.request<void>({
      method: "PUT",
      path: buildPath("/conversations/messages/{messageId}/attachments", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Get Recording by Message ID */
  async getMessageRecording(params: T.GetMessageRecordingData['path']): Promise<void> {
    return this.transport.request<void>({
      method: "GET",
      path: buildPath("/conversations/messages/{messageId}/locations/{locationId}/recording", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** Get transcription by Message ID */
  async getMessageTranscription(params: T.GetMessageTranscriptionData['path']): Promise<T.GetMessageTranscriptionResponses[keyof T.GetMessageTranscriptionResponses]> {
    return this.transport.request<T.GetMessageTranscriptionResponses[keyof T.GetMessageTranscriptionResponses]>({
      method: "GET",
      path: buildPath("/conversations/locations/{locationId}/messages/{messageId}/transcription", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** Download transcription by Message ID */
  async downloadMessageTranscription(params: T.DownloadMessageTranscriptionData['path']): Promise<void> {
    return this.transport.request<void>({
      method: "GET",
      path: buildPath("/conversations/locations/{locationId}/messages/{messageId}/transcription/download", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** Agent/Ai-Bot is typing a message indicator for live chat */
  async liveChatAgentTyping(params: T.LiveChatAgentTypingData['body']): Promise<T.LiveChatAgentTypingResponses[keyof T.LiveChatAgentTypingResponses]> {
    return this.transport.request<T.LiveChatAgentTypingResponses[keyof T.LiveChatAgentTypingResponses]>({
      method: "POST",
      path: "/conversations/providers/live-chat/typing",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Create Conversation */
  async createConversation(params: T.CreateConversationData['body']): Promise<T.CreateConversationResponses[keyof T.CreateConversationResponses]> {
    return this.transport.request<T.CreateConversationResponses[keyof T.CreateConversationResponses]>({
      method: "POST",
      path: "/conversations/",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }
}
