// AUTO-GENERATED by scripts/generate-resources.ts — do not edit directly.
// Re-run `npm run generate` after updating the specs submodule.
import type { HttpTransport } from '../../http/transport.js';
import { buildPath } from '../shared/build-path.js';
import type * as T from './generated/types.gen.js';

export class SaasApiResource {
  constructor(private readonly transport: HttpTransport) {}

  /** Get locations by stripeId with companyId */
  async locationsDeprecated(params: T.LocationsDeprecatedData['query']): Promise<T.LocationsDeprecatedResponses[keyof T.LocationsDeprecatedResponses]> {
    return this.transport.request<T.LocationsDeprecatedResponses[keyof T.LocationsDeprecatedResponses]>({
      method: "GET",
      path: "/saas-api/public-api/locations",
      securityScheme: "Agency-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "customerId": (params as unknown as Record<string, any>)["customerId"],
        "subscriptionId": (params as unknown as Record<string, any>)["subscriptionId"],
        "companyId": (params as unknown as Record<string, any>)["companyId"],
      },
    });
  }

  /** Update SaaS subscription */
  async updateSaasSubscriptionDeprecated(params: T.UpdateSaasSubscriptionDeprecatedData['path'] & T.UpdateSaasSubscriptionDeprecatedData['body']): Promise<T.UpdateSaasSubscriptionDeprecatedResponses[keyof T.UpdateSaasSubscriptionDeprecatedResponses]> {
    return this.transport.request<T.UpdateSaasSubscriptionDeprecatedResponses[keyof T.UpdateSaasSubscriptionDeprecatedResponses]>({
      method: "PUT",
      path: buildPath("/saas-api/public-api/update-saas-subscription/{locationId}", params as unknown as Record<string, unknown>),
      securityScheme: "Agency-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Disable SaaS for locations */
  async bulkDisableSaasDeprecated(params: T.BulkDisableSaasDeprecatedData['path'] & T.BulkDisableSaasDeprecatedData['body']): Promise<T.BulkDisableSaasDeprecatedResponses[keyof T.BulkDisableSaasDeprecatedResponses]> {
    return this.transport.request<T.BulkDisableSaasDeprecatedResponses[keyof T.BulkDisableSaasDeprecatedResponses]>({
      method: "POST",
      path: buildPath("/saas-api/public-api/bulk-disable-saas/{companyId}", params as unknown as Record<string, unknown>),
      securityScheme: "Agency-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Enable SaaS for Sub-Account (Formerly Location) */
  async enableSaasLocationDeprecated(params: T.EnableSaasLocationDeprecatedData['path'] & T.EnableSaasLocationDeprecatedData['body']): Promise<T.EnableSaasLocationDeprecatedResponses[keyof T.EnableSaasLocationDeprecatedResponses]> {
    return this.transport.request<T.EnableSaasLocationDeprecatedResponses[keyof T.EnableSaasLocationDeprecatedResponses]>({
      method: "POST",
      path: buildPath("/saas-api/public-api/enable-saas/{locationId}", params as unknown as Record<string, unknown>),
      securityScheme: "Agency-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Pause location */
  async pauseLocationDeprecated(params: T.PauseLocationDeprecatedData['path'] & T.PauseLocationDeprecatedData['body']): Promise<T.PauseLocationDeprecatedResponses[keyof T.PauseLocationDeprecatedResponses]> {
    return this.transport.request<T.PauseLocationDeprecatedResponses[keyof T.PauseLocationDeprecatedResponses]>({
      method: "POST",
      path: buildPath("/saas-api/public-api/pause/{locationId}", params as unknown as Record<string, unknown>),
      securityScheme: "Agency-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Update Rebilling */
  async updateRebillingDeprecated(params: T.UpdateRebillingDeprecatedData['path'] & T.UpdateRebillingDeprecatedData['body']): Promise<T.UpdateRebillingDeprecatedResponses[keyof T.UpdateRebillingDeprecatedResponses]> {
    return this.transport.request<T.UpdateRebillingDeprecatedResponses[keyof T.UpdateRebillingDeprecatedResponses]>({
      method: "POST",
      path: buildPath("/saas-api/public-api/update-rebilling/{companyId}", params as unknown as Record<string, unknown>),
      securityScheme: "Agency-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Get Agency Plans */
  async getAgencyPlansDeprecated(params: T.GetAgencyPlansDeprecatedData['path']): Promise<T.GetAgencyPlansDeprecatedResponses[keyof T.GetAgencyPlansDeprecatedResponses]> {
    return this.transport.request<T.GetAgencyPlansDeprecatedResponses[keyof T.GetAgencyPlansDeprecatedResponses]>({
      method: "GET",
      path: buildPath("/saas-api/public-api/agency-plans/{companyId}", params as unknown as Record<string, unknown>),
      securityScheme: "Agency-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** Get Location Subscription Details */
  async getLocationSubscriptionDeprecated(params: T.GetLocationSubscriptionDeprecatedData['path'] & T.GetLocationSubscriptionDeprecatedData['query']): Promise<T.GetLocationSubscriptionDeprecatedResponses[keyof T.GetLocationSubscriptionDeprecatedResponses]> {
    return this.transport.request<T.GetLocationSubscriptionDeprecatedResponses[keyof T.GetLocationSubscriptionDeprecatedResponses]>({
      method: "GET",
      path: buildPath("/saas-api/public-api/get-saas-subscription/{locationId}", params as unknown as Record<string, unknown>),
      securityScheme: "Agency-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "companyId": (params as unknown as Record<string, any>)["companyId"],
      },
    });
  }

  /** Bulk Enable SaaS */
  async bulkEnableSaasDeprecated(params: T.BulkEnableSaasDeprecatedData['path'] & T.BulkEnableSaasDeprecatedData['body']): Promise<T.BulkEnableSaasDeprecatedResponses[keyof T.BulkEnableSaasDeprecatedResponses]> {
    return this.transport.request<T.BulkEnableSaasDeprecatedResponses[keyof T.BulkEnableSaasDeprecatedResponses]>({
      method: "POST",
      path: buildPath("/saas-api/public-api/bulk-enable-saas/{companyId}", params as unknown as Record<string, unknown>),
      securityScheme: "Agency-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Get SaaS Locations */
  async getSaasLocationsDeprecated(params: T.GetSaasLocationsDeprecatedData['path'] & T.GetSaasLocationsDeprecatedData['query']): Promise<T.GetSaasLocationsDeprecatedResponses[keyof T.GetSaasLocationsDeprecatedResponses]> {
    return this.transport.request<T.GetSaasLocationsDeprecatedResponses[keyof T.GetSaasLocationsDeprecatedResponses]>({
      method: "GET",
      path: buildPath("/saas-api/public-api/saas-locations/{companyId}", params as unknown as Record<string, unknown>),
      securityScheme: "Agency-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "page": (params as unknown as Record<string, any>)["page"],
      },
    });
  }

  /** Get SaaS Plan */
  async getSaasPlanDeprecated(params: T.GetSaasPlanDeprecatedData['path'] & T.GetSaasPlanDeprecatedData['query']): Promise<T.GetSaasPlanDeprecatedResponses[keyof T.GetSaasPlanDeprecatedResponses]> {
    return this.transport.request<T.GetSaasPlanDeprecatedResponses[keyof T.GetSaasPlanDeprecatedResponses]>({
      method: "GET",
      path: buildPath("/saas-api/public-api/saas-plan/{planId}", params as unknown as Record<string, unknown>),
      securityScheme: "Agency-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "companyId": (params as unknown as Record<string, any>)["companyId"],
      },
    });
  }

  /** Get locations by stripeId with companyId */
  async locations(params: T.LocationsData['query']): Promise<void> {
    return this.transport.request<void>({
      method: "GET",
      path: "/saas/locations",
      securityScheme: "Agency-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "customerId": (params as unknown as Record<string, any>)["customerId"],
        "subscriptionId": (params as unknown as Record<string, any>)["subscriptionId"],
        "companyId": (params as unknown as Record<string, any>)["companyId"],
      },
    });
  }

  /** Update SaaS subscription */
  async generatePaymentLink(params: T.GeneratePaymentLinkData['path'] & T.GeneratePaymentLinkData['body']): Promise<void> {
    return this.transport.request<void>({
      method: "PUT",
      path: buildPath("/saas/update-saas-subscription/{locationId}", params as unknown as Record<string, unknown>),
      securityScheme: "Agency-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Disable SaaS for locations */
  async bulkDisableSaas(params: T.BulkDisableSaasData['path'] & T.BulkDisableSaasData['body']): Promise<void> {
    return this.transport.request<void>({
      method: "POST",
      path: buildPath("/saas/bulk-disable-saas/{companyId}", params as unknown as Record<string, unknown>),
      securityScheme: "Agency-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Enable SaaS for Sub-Account (Formerly Location) */
  async enableSaasLocation(params: T.EnableSaasLocationData['path'] & T.EnableSaasLocationData['body']): Promise<void> {
    return this.transport.request<void>({
      method: "POST",
      path: buildPath("/saas/enable-saas/{locationId}", params as unknown as Record<string, unknown>),
      securityScheme: "Agency-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Pause location */
  async pauseLocation(params: T.PauseLocationData['path'] & T.PauseLocationData['body']): Promise<void> {
    return this.transport.request<void>({
      method: "POST",
      path: buildPath("/saas/pause/{locationId}", params as unknown as Record<string, unknown>),
      securityScheme: "Agency-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Update Rebilling */
  async updateRebilling(params: T.UpdateRebillingData['path'] & T.UpdateRebillingData['body']): Promise<void> {
    return this.transport.request<void>({
      method: "POST",
      path: buildPath("/saas/update-rebilling/{companyId}", params as unknown as Record<string, unknown>),
      securityScheme: "Agency-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Get Agency Plans */
  async getAgencyPlans(params: T.GetAgencyPlansData['path']): Promise<void> {
    return this.transport.request<void>({
      method: "GET",
      path: buildPath("/saas/agency-plans/{companyId}", params as unknown as Record<string, unknown>),
      securityScheme: "Agency-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** Get Location Subscription Details */
  async getLocationSubscription(params: T.GetLocationSubscriptionData['path'] & T.GetLocationSubscriptionData['query']): Promise<void> {
    return this.transport.request<void>({
      method: "GET",
      path: buildPath("/saas/get-saas-subscription/{locationId}", params as unknown as Record<string, unknown>),
      securityScheme: "Agency-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "companyId": (params as unknown as Record<string, any>)["companyId"],
      },
    });
  }

  /** Bulk Enable SaaS */
  async bulkEnableSaas(params: T.BulkEnableSaasData['path'] & T.BulkEnableSaasData['body']): Promise<void> {
    return this.transport.request<void>({
      method: "POST",
      path: buildPath("/saas/bulk-enable-saas/{companyId}", params as unknown as Record<string, unknown>),
      securityScheme: "Agency-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Get SaaS Locations */
  async getSaasLocations(params: T.GetSaasLocationsData['path'] & T.GetSaasLocationsData['query']): Promise<void> {
    return this.transport.request<void>({
      method: "GET",
      path: buildPath("/saas/saas-locations/{companyId}", params as unknown as Record<string, unknown>),
      securityScheme: "Agency-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "page": (params as unknown as Record<string, any>)["page"],
      },
    });
  }

  /** Get SaaS Plan */
  async getSaasPlan(params: T.GetSaasPlanData['path'] & T.GetSaasPlanData['query']): Promise<void> {
    return this.transport.request<void>({
      method: "GET",
      path: buildPath("/saas/saas-plan/{planId}", params as unknown as Record<string, unknown>),
      securityScheme: "Agency-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "companyId": (params as unknown as Record<string, any>)["companyId"],
      },
    });
  }
}
