// AUTO-GENERATED by scripts/generate-resources.ts — do not edit directly.
// Re-run `npm run generate` after updating the specs submodule.
import type { HttpTransport } from '../../http/transport.js';
import { buildPath } from '../shared/build-path.js';
import type * as T from './generated/types.gen.js';

export class KnowledgeBaseResource {
  constructor(private readonly transport: HttpTransport) {}

  /** Get all FAQs by knowledge base with pagination support */
  async list(params: T.ListData['query']): Promise<T.ListResponses[keyof T.ListResponses]> {
    return this.transport.request<T.ListResponses[keyof T.ListResponses]>({
      method: "GET",
      path: "/knowledge-bases/faqs",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "knowledgeBaseId": (params as unknown as Record<string, any>)["knowledgeBaseId"],
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "limit": (params as unknown as Record<string, any>)["limit"],
        "lastFaqId": (params as unknown as Record<string, any>)["lastFaqId"],
      },
    });
  }

  /** Create a new FAQ inside knowledge base */
  async create(params: T.CreateData['body']): Promise<T.CreateResponses[keyof T.CreateResponses]> {
    return this.transport.request<T.CreateResponses[keyof T.CreateResponses]>({
      method: "POST",
      path: "/knowledge-bases/faqs",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Update an existing knowledge base FAQ */
  async update(params: T.UpdateData['path'] & T.UpdateData['body']): Promise<T.UpdateResponses[keyof T.UpdateResponses]> {
    return this.transport.request<T.UpdateResponses[keyof T.UpdateResponses]>({
      method: "PUT",
      path: buildPath("/knowledge-bases/faqs/{id}", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Delete an existing knowledge base FAQ */
  async delete(params: T.DeleteData['path']): Promise<T.DeleteResponses[keyof T.DeleteResponses]> {
    return this.transport.request<T.DeleteResponses[keyof T.DeleteResponses]>({
      method: "DELETE",
      path: buildPath("/knowledge-bases/faqs/{id}", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** Get all trained page links by knowledge base */
  async getAllWebsiteUrlsDataByKnowledgeBase(params: T.GetAllWebsiteUrlsDataByKnowledgeBaseData['query']): Promise<T.GetAllWebsiteUrlsDataByKnowledgeBaseResponses[keyof T.GetAllWebsiteUrlsDataByKnowledgeBaseResponses]> {
    return this.transport.request<T.GetAllWebsiteUrlsDataByKnowledgeBaseResponses[keyof T.GetAllWebsiteUrlsDataByKnowledgeBaseResponses]>({
      method: "GET",
      path: "/knowledge-bases/crawler",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "knowledgeBaseId": (params as unknown as Record<string, any>)["knowledgeBaseId"],
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "page": (params as unknown as Record<string, any>)["page"],
        "pageLength": (params as unknown as Record<string, any>)["pageLength"],
        "query": (params as unknown as Record<string, any>)["query"],
      },
    });
  }

  /** Start crawling and discover pages for training */
  async discoverWebsite(params: T.DiscoverWebsiteData['body']): Promise<T.DiscoverWebsiteResponses[keyof T.DiscoverWebsiteResponses]> {
    return this.transport.request<T.DiscoverWebsiteResponses[keyof T.DiscoverWebsiteResponses]>({
      method: "POST",
      path: "/knowledge-bases/crawler",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Delete trained pages */
  async deleteTrainedUrlsForKnowledgeBase(params: T.DeleteTrainedUrlsForKnowledgeBaseData['body']): Promise<T.DeleteTrainedUrlsForKnowledgeBaseResponses[keyof T.DeleteTrainedUrlsForKnowledgeBaseResponses]> {
    return this.transport.request<T.DeleteTrainedUrlsForKnowledgeBaseResponses[keyof T.DeleteTrainedUrlsForKnowledgeBaseResponses]>({
      method: "DELETE",
      path: "/knowledge-bases/crawler",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Get crawling status for the latest operation */
  async getCrawlingStatusForLatestOperation(params: T.GetCrawlingStatusForLatestOperationData['query']): Promise<T.GetCrawlingStatusForLatestOperationResponses[keyof T.GetCrawlingStatusForLatestOperationResponses]> {
    return this.transport.request<T.GetCrawlingStatusForLatestOperationResponses[keyof T.GetCrawlingStatusForLatestOperationResponses]>({
      method: "GET",
      path: "/knowledge-bases/crawler/status",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "operationId": (params as unknown as Record<string, any>)["operationId"],
        "knowledgeBaseId": (params as unknown as Record<string, any>)["knowledgeBaseId"],
      },
    });
  }

  /** Train discovered website pages and ingest into the knowledge base */
  async trainDiscoveredUrls(params: T.TrainDiscoveredUrlsData['body']): Promise<T.TrainDiscoveredUrlsResponses[keyof T.TrainDiscoveredUrlsResponses]> {
    return this.transport.request<T.TrainDiscoveredUrlsResponses[keyof T.TrainDiscoveredUrlsResponses]>({
      method: "POST",
      path: "/knowledge-bases/crawler/train",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Get knowledge base by ID */
  async getKnowledgeBaseById(params: T.GetKnowledgeBaseByIdData['path']): Promise<T.GetKnowledgeBaseByIdResponses[keyof T.GetKnowledgeBaseByIdResponses]> {
    return this.transport.request<T.GetKnowledgeBaseByIdResponses[keyof T.GetKnowledgeBaseByIdResponses]>({
      method: "GET",
      path: buildPath("/knowledge-bases/{knowledgeBaseId}", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** Delete a knowledge base */
  async deleteKnowledgeBase(params: T.DeleteKnowledgeBaseData['path']): Promise<T.DeleteKnowledgeBaseResponses[keyof T.DeleteKnowledgeBaseResponses]> {
    return this.transport.request<T.DeleteKnowledgeBaseResponses[keyof T.DeleteKnowledgeBaseResponses]>({
      method: "DELETE",
      path: buildPath("/knowledge-bases/{knowledgeBaseId}", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** Update a knowledge base */
  async updateKnowledgeBase(params: T.UpdateKnowledgeBaseData['path'] & T.UpdateKnowledgeBaseData['body']): Promise<T.UpdateKnowledgeBaseResponses[keyof T.UpdateKnowledgeBaseResponses]> {
    return this.transport.request<T.UpdateKnowledgeBaseResponses[keyof T.UpdateKnowledgeBaseResponses]>({
      method: "PUT",
      path: buildPath("/knowledge-bases/{id}", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Get all knowledge bases for a location by location Id (paginated) */
  async listAllKnowledgeBasesPaginated(params: T.ListAllKnowledgeBasesPaginatedData['query']): Promise<T.ListAllKnowledgeBasesPaginatedResponses[keyof T.ListAllKnowledgeBasesPaginatedResponses]> {
    return this.transport.request<T.ListAllKnowledgeBasesPaginatedResponses[keyof T.ListAllKnowledgeBasesPaginatedResponses]>({
      method: "GET",
      path: "/knowledge-bases/",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "query": (params as unknown as Record<string, any>)["query"],
        "limit": (params as unknown as Record<string, any>)["limit"],
        "lastKnowledgeBaseId": (params as unknown as Record<string, any>)["lastKnowledgeBaseId"],
      },
    });
  }

  /** Create a new knowledge base (max 15 knowledge bases per location) */
  async createKnowledgeBase(params: T.CreateKnowledgeBaseData['body']): Promise<T.CreateKnowledgeBaseResponses[keyof T.CreateKnowledgeBaseResponses]> {
    return this.transport.request<T.CreateKnowledgeBaseResponses[keyof T.CreateKnowledgeBaseResponses]>({
      method: "POST",
      path: "/knowledge-bases/",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }
}
