// AUTO-GENERATED by scripts/generate-resources.ts — do not edit directly.
// Re-run `npm run generate` after updating the specs submodule.
import type { HttpTransport } from '../../http/transport.js';
import { buildPath } from '../shared/build-path.js';
import type * as T from './generated/types.gen.js';

export class SnapshotsResource {
  constructor(private readonly transport: HttpTransport) {}

  /** Get Snapshots */
  async getCustomSnapshots(params: T.GetCustomSnapshotsData['query']): Promise<T.GetCustomSnapshotsResponses[keyof T.GetCustomSnapshotsResponses]> {
    return this.transport.request<T.GetCustomSnapshotsResponses[keyof T.GetCustomSnapshotsResponses]>({
      method: "GET",
      path: "/snapshots/",
      securityScheme: "Agency-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "companyId": (params as unknown as Record<string, any>)["companyId"],
      },
    });
  }

  /** Create Snapshot Share Link */
  async createSnapshotShareLink(params: T.CreateSnapshotShareLinkData['query'] & T.CreateSnapshotShareLinkData['body']): Promise<T.CreateSnapshotShareLinkResponses[keyof T.CreateSnapshotShareLinkResponses]> {
    return this.transport.request<T.CreateSnapshotShareLinkResponses[keyof T.CreateSnapshotShareLinkResponses]>({
      method: "POST",
      path: "/snapshots/share/link",
      securityScheme: "Agency-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "companyId": (params as unknown as Record<string, any>)["companyId"],
      },
      body: params,
    });
  }

  /** Get Snapshot Push between Dates */
  async getSnapshotPush(params: T.GetSnapshotPushData['path'] & T.GetSnapshotPushData['query']): Promise<T.GetSnapshotPushResponses[keyof T.GetSnapshotPushResponses]> {
    return this.transport.request<T.GetSnapshotPushResponses[keyof T.GetSnapshotPushResponses]>({
      method: "GET",
      path: buildPath("/snapshots/snapshot-status/{snapshotId}", params as unknown as Record<string, unknown>),
      securityScheme: "Agency-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "companyId": (params as unknown as Record<string, any>)["companyId"],
        "from": (params as unknown as Record<string, any>)["from"],
        "to": (params as unknown as Record<string, any>)["to"],
        "lastDoc": (params as unknown as Record<string, any>)["lastDoc"],
        "limit": (params as unknown as Record<string, any>)["limit"],
      },
    });
  }

  /** Get Last Snapshot Push */
  async getLatestSnapshotPush(params: T.GetLatestSnapshotPushData['path'] & T.GetLatestSnapshotPushData['query']): Promise<T.GetLatestSnapshotPushResponses[keyof T.GetLatestSnapshotPushResponses]> {
    return this.transport.request<T.GetLatestSnapshotPushResponses[keyof T.GetLatestSnapshotPushResponses]>({
      method: "GET",
      path: buildPath("/snapshots/snapshot-status/{snapshotId}/location/{locationId}", params as unknown as Record<string, unknown>),
      securityScheme: "Agency-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "companyId": (params as unknown as Record<string, any>)["companyId"],
      },
    });
  }
}
