// AUTO-GENERATED by scripts/generate-resources.ts — do not edit directly.
// Re-run `npm run generate` after updating the specs submodule.
import type { HttpTransport } from '../../http/transport.js';
import { buildPath } from '../shared/build-path.js';
import type * as T from './generated/types.gen.js';

export class FunnelsResource {
  constructor(private readonly transport: HttpTransport) {}

  /** Create Redirect */
  async createRedirect(params: T.CreateRedirectData['body']): Promise<T.CreateRedirectResponses[keyof T.CreateRedirectResponses]> {
    return this.transport.request<T.CreateRedirectResponses[keyof T.CreateRedirectResponses]>({
      method: "POST",
      path: "/funnels/lookup/redirect",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Update Redirect By Id */
  async updateRedirectById(params: T.UpdateRedirectByIdData['path'] & T.UpdateRedirectByIdData['body']): Promise<T.UpdateRedirectByIdResponses[keyof T.UpdateRedirectByIdResponses]> {
    return this.transport.request<T.UpdateRedirectByIdResponses[keyof T.UpdateRedirectByIdResponses]>({
      method: "PATCH",
      path: buildPath("/funnels/lookup/redirect/{id}", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Delete Redirect By Id */
  async deleteRedirectById(params: T.DeleteRedirectByIdData['path'] & T.DeleteRedirectByIdData['query']): Promise<T.DeleteRedirectByIdResponses[keyof T.DeleteRedirectByIdResponses]> {
    return this.transport.request<T.DeleteRedirectByIdResponses[keyof T.DeleteRedirectByIdResponses]>({
      method: "DELETE",
      path: buildPath("/funnels/lookup/redirect/{id}", params as unknown as Record<string, unknown>),
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
      },
    });
  }

  /** Fetch List of Redirects */
  async fetchRedirectsList(params: T.FetchRedirectsListData['query']): Promise<T.FetchRedirectsListResponses[keyof T.FetchRedirectsListResponses]> {
    return this.transport.request<T.FetchRedirectsListResponses[keyof T.FetchRedirectsListResponses]>({
      method: "GET",
      path: "/funnels/lookup/redirect/list",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "limit": (params as unknown as Record<string, any>)["limit"],
        "offset": (params as unknown as Record<string, any>)["offset"],
        "search": (params as unknown as Record<string, any>)["search"],
      },
    });
  }

  /** Fetch List of Funnels */
  async getFunnels(params: T.GetFunnelsData['query']): Promise<T.GetFunnelsResponses[keyof T.GetFunnelsResponses]> {
    return this.transport.request<T.GetFunnelsResponses[keyof T.GetFunnelsResponses]>({
      method: "GET",
      path: "/funnels/funnel/list",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "type": (params as unknown as Record<string, any>)["type"],
        "category": (params as unknown as Record<string, any>)["category"],
        "offset": (params as unknown as Record<string, any>)["offset"],
        "limit": (params as unknown as Record<string, any>)["limit"],
        "parentId": (params as unknown as Record<string, any>)["parentId"],
        "name": (params as unknown as Record<string, any>)["name"],
      },
    });
  }

  /** Fetch list of funnel pages */
  async getPagesByFunnelId(params: T.GetPagesByFunnelIdData['query']): Promise<T.GetPagesByFunnelIdResponses[keyof T.GetPagesByFunnelIdResponses]> {
    return this.transport.request<T.GetPagesByFunnelIdResponses[keyof T.GetPagesByFunnelIdResponses]>({
      method: "GET",
      path: "/funnels/page",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "funnelId": (params as unknown as Record<string, any>)["funnelId"],
        "name": (params as unknown as Record<string, any>)["name"],
        "limit": (params as unknown as Record<string, any>)["limit"],
        "offset": (params as unknown as Record<string, any>)["offset"],
      },
    });
  }

  /** Fetch count of funnel pages */
  async getPagesCountByFunnelId(params: T.GetPagesCountByFunnelIdData['query']): Promise<T.GetPagesCountByFunnelIdResponses[keyof T.GetPagesCountByFunnelIdResponses]> {
    return this.transport.request<T.GetPagesCountByFunnelIdResponses[keyof T.GetPagesCountByFunnelIdResponses]>({
      method: "GET",
      path: "/funnels/page/count",
      securityScheme: "Location-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "funnelId": (params as unknown as Record<string, any>)["funnelId"],
        "name": (params as unknown as Record<string, any>)["name"],
      },
    });
  }
}
