// AUTO-GENERATED by scripts/generate-resources.ts — do not edit directly.
// Re-run `npm run generate` after updating the specs submodule.
import type { HttpTransport } from '../../http/transport.js';
import type * as T from './generated/types.gen.js';

export class FormsResource {
  constructor(private readonly transport: HttpTransport) {}

  /** Get Forms Submissions */
  async getFormsSubmissions(params: T.GetFormsSubmissionsData['query']): Promise<T.GetFormsSubmissionsResponses[keyof T.GetFormsSubmissionsResponses]> {
    return this.transport.request<T.GetFormsSubmissionsResponses[keyof T.GetFormsSubmissionsResponses]>({
      method: "GET",
      path: "/forms/submissions",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "page": (params as unknown as Record<string, any>)["page"],
        "limit": (params as unknown as Record<string, any>)["limit"],
        "formId": (params as unknown as Record<string, any>)["formId"],
        "q": (params as unknown as Record<string, any>)["q"],
        "startAt": (params as unknown as Record<string, any>)["startAt"],
        "endAt": (params as unknown as Record<string, any>)["endAt"],
      },
    });
  }

  /** Upload files to custom fields */
  async uploadToCustomFields(params: T.UploadToCustomFieldsData['query']): Promise<void> {
    return this.transport.request<void>({
      method: "POST",
      path: "/forms/upload-custom-files",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "contactId": (params as unknown as Record<string, any>)["contactId"],
        "locationId": (params as unknown as Record<string, any>)["locationId"],
      },
    });
  }

  /** Get Forms */
  async getForms(params: T.GetFormsData['query']): Promise<T.GetFormsResponses[keyof T.GetFormsResponses]> {
    return this.transport.request<T.GetFormsResponses[keyof T.GetFormsResponses]>({
      method: "GET",
      path: "/forms/",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "skip": (params as unknown as Record<string, any>)["skip"],
        "limit": (params as unknown as Record<string, any>)["limit"],
        "type": (params as unknown as Record<string, any>)["type"],
      },
    });
  }
}
