// AUTO-GENERATED by scripts/generate-resources.ts — do not edit directly.
// Re-run `npm run generate` after updating the specs submodule.
import type { HttpTransport } from '../../http/transport.js';
import { buildPath } from '../shared/build-path.js';
import type * as T from './generated/types.gen.js';

export class AdManagerResource {
  constructor(private readonly transport: HttpTransport) {}

  /** Get reporting data */
  async fbGetReporting(params: T.FbGetReportingData['query']): Promise<void> {
    return this.transport.request<void>({
      method: "GET",
      path: "/ad-publishing/facebook/reporting",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "groupBy": (params as unknown as Record<string, any>)["groupBy"],
        "startDate": (params as unknown as Record<string, any>)["startDate"],
        "endDate": (params as unknown as Record<string, any>)["endDate"],
        "type": (params as unknown as Record<string, any>)["type"],
        "fields": (params as unknown as Record<string, any>)["fields"],
      },
    });
  }

  /** Get campaign reporting */
  async fbGetCampaignReporting(params: T.FbGetCampaignReportingData['path'] & T.FbGetCampaignReportingData['query']): Promise<void> {
    return this.transport.request<void>({
      method: "GET",
      path: buildPath("/ad-publishing/facebook/reporting/campaign/{campaignId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "startDate": (params as unknown as Record<string, any>)["startDate"],
        "endDate": (params as unknown as Record<string, any>)["endDate"],
      },
    });
  }

  /** Get reporting list */
  async fbGetReportingList(params: T.FbGetReportingListData['query']): Promise<void> {
    return this.transport.request<void>({
      method: "GET",
      path: "/ad-publishing/facebook/reporting/list",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "listType": (params as unknown as Record<string, any>)["listType"],
        "startDate": (params as unknown as Record<string, any>)["startDate"],
        "endDate": (params as unknown as Record<string, any>)["endDate"],
        "campaignId": (params as unknown as Record<string, any>)["campaignId"],
        "type": (params as unknown as Record<string, any>)["type"],
      },
    });
  }

  /** Get current Facebook user */
  async fbGetCurrentUser(params: T.FbGetCurrentUserData['query']): Promise<void> {
    return this.transport.request<void>({
      method: "GET",
      path: "/ad-publishing/facebook/me",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
      },
    });
  }

  /** Get Facebook pages */
  async fbGetPages(params: T.FbGetPagesData['query']): Promise<void> {
    return this.transport.request<void>({
      method: "GET",
      path: "/ad-publishing/facebook/pages",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "fetchExisting": (params as unknown as Record<string, any>)["fetchExisting"],
      },
    });
  }

  /** Get Instagram accounts for page */
  async fbGetInstagramAccounts(params: T.FbGetInstagramAccountsData['path'] & T.FbGetInstagramAccountsData['query']): Promise<void> {
    return this.transport.request<void>({
      method: "GET",
      path: buildPath("/ad-publishing/facebook/page/{pageId}/instagram", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "type": (params as unknown as Record<string, any>)["type"],
      },
    });
  }

  /** Get page lead forms */
  async fbGetPageLeadForms(params: T.FbGetPageLeadFormsData['path'] & T.FbGetPageLeadFormsData['query']): Promise<void> {
    return this.transport.request<void>({
      method: "GET",
      path: buildPath("/ad-publishing/facebook/page/{pageId}/forms", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
      },
    });
  }

  /** Create page lead form */
  async fbCreatePageLeadForm(params: T.FbCreatePageLeadFormData['path'] & T.FbCreatePageLeadFormData['body']): Promise<void> {
    return this.transport.request<void>({
      method: "POST",
      path: buildPath("/ad-publishing/facebook/page/{pageId}/forms", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Get ad accounts */
  async fbGetAdAccounts(params: T.FbGetAdAccountsData['query']): Promise<void> {
    return this.transport.request<void>({
      method: "GET",
      path: "/ad-publishing/facebook/ad-accounts",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "type": (params as unknown as Record<string, any>)["type"],
        "next": (params as unknown as Record<string, any>)["next"],
        "fetchAll": (params as unknown as Record<string, any>)["fetchAll"],
        "limit": (params as unknown as Record<string, any>)["limit"],
      },
    });
  }

  /** Get ad account details */
  async fbGetAdAccount(params: T.FbGetAdAccountData['path'] & T.FbGetAdAccountData['query']): Promise<void> {
    return this.transport.request<void>({
      method: "GET",
      path: buildPath("/ad-publishing/facebook/ad-accounts/{adAccountId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
      },
    });
  }

  /** Delete ad account */
  async fbDeleteAdAccount(params: T.FbDeleteAdAccountData['path'] & T.FbDeleteAdAccountData['body']): Promise<void> {
    return this.transport.request<void>({
      method: "DELETE",
      path: buildPath("/ad-publishing/facebook/ad-accounts/{adAccountId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Get conversation forms */
  async fbGetConversationForms(params: T.FbGetConversationFormsData['query']): Promise<void> {
    return this.transport.request<void>({
      method: "GET",
      path: "/ad-publishing/facebook/conversation-forms",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
      },
    });
  }

  /** Create conversation form */
  async fbCreateConversationForm(params: T.FbCreateConversationFormData['body']): Promise<void> {
    return this.transport.request<void>({
      method: "POST",
      path: "/ad-publishing/facebook/conversation-forms",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Get Facebook integration */
  async fbGetIntegration(params: T.FbGetIntegrationData['query']): Promise<void> {
    return this.transport.request<void>({
      method: "GET",
      path: "/ad-publishing/facebook/integration",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
      },
    });
  }

  /** Create Facebook integration */
  async fbCreateIntegration(params: T.FbCreateIntegrationData['body']): Promise<void> {
    return this.transport.request<void>({
      method: "POST",
      path: "/ad-publishing/facebook/integration",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Delete Facebook integration */
  async fbDeleteIntegration(params: T.FbDeleteIntegrationData['body']): Promise<void> {
    return this.transport.request<void>({
      method: "DELETE",
      path: "/ad-publishing/facebook/integration",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Search targeting options */
  async fbSearchTargeting(params: T.FbSearchTargetingData['query']): Promise<void> {
    return this.transport.request<void>({
      method: "GET",
      path: "/ad-publishing/facebook/targeting/search",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "type": (params as unknown as Record<string, any>)["type"],
        "query": (params as unknown as Record<string, any>)["query"],
        "searchType": (params as unknown as Record<string, any>)["searchType"],
      },
    });
  }

  /** Publish campaign */
  async fbPublishCampaign(params: T.FbPublishCampaignData['path'] & T.FbPublishCampaignData['body']): Promise<void> {
    return this.transport.request<void>({
      method: "POST",
      path: buildPath("/ad-publishing/facebook/campaigns/{campaignId}/publish", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Delete page connection */
  async fbDeletePage(params: T.FbDeletePageData['query']): Promise<void> {
    return this.transport.request<void>({
      method: "DELETE",
      path: "/ad-publishing/facebook/page",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "pageId": (params as unknown as Record<string, any>)["pageId"],
      },
    });
  }

  /** Get conversion pixels */
  async fbGetPixels(params: T.FbGetPixelsData['query']): Promise<void> {
    return this.transport.request<void>({
      method: "GET",
      path: "/ad-publishing/facebook/pixels",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "channel": (params as unknown as Record<string, any>)["channel"],
        "pageId": (params as unknown as Record<string, any>)["pageId"],
        "igUserId": (params as unknown as Record<string, any>)["igUserId"],
      },
    });
  }

  /** Upsert conversion pixel */
  async fbUpsertPixel(params: T.FbUpsertPixelData['body']): Promise<void> {
    return this.transport.request<void>({
      method: "PUT",
      path: "/ad-publishing/facebook/pixels",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Get custom audiences */
  async fbGetCustomAudiences(params: T.FbGetCustomAudiencesData['query']): Promise<void> {
    return this.transport.request<void>({
      method: "GET",
      path: "/ad-publishing/facebook/custom-audience",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "type": (params as unknown as Record<string, any>)["type"],
        "source": (params as unknown as Record<string, any>)["source"],
        "adAccountId": (params as unknown as Record<string, any>)["adAccountId"],
      },
    });
  }

  /** Get custom audience by ID */
  async fbGetCustomAudienceById(params: T.FbGetCustomAudienceByIdData['path'] & T.FbGetCustomAudienceByIdData['query']): Promise<void> {
    return this.transport.request<void>({
      method: "GET",
      path: buildPath("/ad-publishing/facebook/custom-audience/{audienceId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
      },
    });
  }

  /** Update custom audience */
  async fbUpdateCustomAudience(params: T.FbUpdateCustomAudienceData['path'] & T.FbUpdateCustomAudienceData['body']): Promise<void> {
    return this.transport.request<void>({
      method: "PUT",
      path: buildPath("/ad-publishing/facebook/custom-audience/{audienceId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Delete custom audience */
  async fbDeleteCustomAudience(params: T.FbDeleteCustomAudienceData['path'] & T.FbDeleteCustomAudienceData['query']): Promise<void> {
    return this.transport.request<void>({
      method: "DELETE",
      path: buildPath("/ad-publishing/facebook/custom-audience/{audienceId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
      },
    });
  }

  /** Add custom audience member */
  async fbAddCustomAudienceMember(params: T.FbAddCustomAudienceMemberData['path'] & T.FbAddCustomAudienceMemberData['body']): Promise<void> {
    return this.transport.request<void>({
      method: "PUT",
      path: buildPath("/ad-publishing/facebook/custom-audience/{audienceId}/member", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Remove custom audience member */
  async fbRemoveCustomAudienceMember(params: T.FbRemoveCustomAudienceMemberData['path'] & T.FbRemoveCustomAudienceMemberData['body']): Promise<void> {
    return this.transport.request<void>({
      method: "DELETE",
      path: buildPath("/ad-publishing/facebook/custom-audience/{audienceId}/member", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Batch update audience members */
  async fbBatchUpdateAudienceMembers(params: T.FbBatchUpdateAudienceMembersData['path'] & T.FbBatchUpdateAudienceMembersData['body']): Promise<void> {
    return this.transport.request<void>({
      method: "PUT",
      path: buildPath("/ad-publishing/facebook/custom-audience/{audienceId}/member/batch", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Set default page */
  async fbSetDefaultPage(params: T.FbSetDefaultPageData['query'] & T.FbSetDefaultPageData['body']): Promise<void> {
    return this.transport.request<void>({
      method: "PUT",
      path: "/ad-publishing/facebook/page/default",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
      },
      body: params,
    });
  }

  /** Get lead form by ID */
  async fbGetLeadForm(params: T.FbGetLeadFormData['path'] & T.FbGetLeadFormData['query']): Promise<void> {
    return this.transport.request<void>({
      method: "GET",
      path: buildPath("/ad-publishing/facebook/lead-form/{leadFormId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
      },
    });
  }

  /** Get campaign with linked entities */
  async fbGetCampaign(params: T.FbGetCampaignData['path'] & T.FbGetCampaignData['query']): Promise<void> {
    return this.transport.request<void>({
      method: "GET",
      path: buildPath("/ad-publishing/facebook/campaign/{campaignId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "fields": (params as unknown as Record<string, any>)["fields"],
        "source": (params as unknown as Record<string, any>)["source"],
      },
    });
  }

  /** Get entities */
  async fbGetEntity(params: T.FbGetEntityData['query']): Promise<void> {
    return this.transport.request<void>({
      method: "GET",
      path: "/ad-publishing/facebook/entity",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "type": (params as unknown as Record<string, any>)["type"],
        "next": (params as unknown as Record<string, any>)["next"],
        "fetchAll": (params as unknown as Record<string, any>)["fetchAll"],
        "campaignId": (params as unknown as Record<string, any>)["campaignId"],
        "adSetId": (params as unknown as Record<string, any>)["adSetId"],
        "entityType": (params as unknown as Record<string, any>)["entityType"],
        "searchId": (params as unknown as Record<string, any>)["searchId"],
        "selectedAdAccountId": (params as unknown as Record<string, any>)["selectedAdAccountId"],
      },
    });
  }

  /** Upsert campaign */
  async fbUpsertCampaign(params: T.FbUpsertCampaignData['body']): Promise<void> {
    return this.transport.request<void>({
      method: "PUT",
      path: "/ad-publishing/facebook/campaigns",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Upsert adset */
  async fbUpsertAdset(params: T.FbUpsertAdsetData['body']): Promise<void> {
    return this.transport.request<void>({
      method: "PUT",
      path: "/ad-publishing/facebook/adsets",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Upsert ad */
  async fbUpsertAd(params: T.FbUpsertAdData['body']): Promise<void> {
    return this.transport.request<void>({
      method: "PUT",
      path: "/ad-publishing/facebook/ads-v2",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Pause campaign */
  async fbPauseCampaign(params: T.FbPauseCampaignData['path'] & T.FbPauseCampaignData['body']): Promise<void> {
    return this.transport.request<void>({
      method: "POST",
      path: buildPath("/ad-publishing/facebook/campaigns/{campaignId}/pause", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Resume campaign */
  async fbResumeCampaign(params: T.FbResumeCampaignData['path'] & T.FbResumeCampaignData['body']): Promise<void> {
    return this.transport.request<void>({
      method: "POST",
      path: buildPath("/ad-publishing/facebook/campaigns/{campaignId}/resume", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Duplicate campaign */
  async fbDuplicateCampaign(params: T.FbDuplicateCampaignData['path'] & T.FbDuplicateCampaignData['body']): Promise<void> {
    return this.transport.request<void>({
      method: "POST",
      path: buildPath("/ad-publishing/facebook/campaigns/{campaignId}/duplicate", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Delete campaign */
  async fbDeleteCampaign(params: T.FbDeleteCampaignData['path'] & T.FbDeleteCampaignData['body']): Promise<void> {
    return this.transport.request<void>({
      method: "DELETE",
      path: buildPath("/ad-publishing/facebook/campaigns/{campaignId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Pause ad set */
  async fbPauseAdset(params: T.FbPauseAdsetData['path'] & T.FbPauseAdsetData['body']): Promise<void> {
    return this.transport.request<void>({
      method: "POST",
      path: buildPath("/ad-publishing/facebook/adsets/{adsetId}/pause", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Resume ad set */
  async fbResumeAdset(params: T.FbResumeAdsetData['path'] & T.FbResumeAdsetData['body']): Promise<void> {
    return this.transport.request<void>({
      method: "POST",
      path: buildPath("/ad-publishing/facebook/adsets/{adsetId}/resume", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Duplicate ad set */
  async fbDuplicateAdset(params: T.FbDuplicateAdsetData['path']): Promise<void> {
    return this.transport.request<void>({
      method: "POST",
      path: buildPath("/ad-publishing/facebook/adsets/{adsetId}/duplicate", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** Delete ad set */
  async fbDeleteAdset(params: T.FbDeleteAdsetData['path'] & T.FbDeleteAdsetData['body']): Promise<void> {
    return this.transport.request<void>({
      method: "DELETE",
      path: buildPath("/ad-publishing/facebook/adsets/{adsetId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Pause ad */
  async fbPauseAd(params: T.FbPauseAdData['path'] & T.FbPauseAdData['body']): Promise<void> {
    return this.transport.request<void>({
      method: "POST",
      path: buildPath("/ad-publishing/facebook/ads/{adId}/pause", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Resume ad */
  async fbResumeAd(params: T.FbResumeAdData['path'] & T.FbResumeAdData['body']): Promise<void> {
    return this.transport.request<void>({
      method: "POST",
      path: buildPath("/ad-publishing/facebook/ads/{adId}/resume", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Duplicate ad */
  async fbDuplicateAd(params: T.FbDuplicateAdData['path']): Promise<void> {
    return this.transport.request<void>({
      method: "POST",
      path: buildPath("/ad-publishing/facebook/ads/{adId}/duplicate", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** Delete ad */
  async fbDeleteAd(params: T.FbDeleteAdData['path'] & T.FbDeleteAdData['body']): Promise<void> {
    return this.transport.request<void>({
      method: "DELETE",
      path: buildPath("/ad-publishing/facebook/ads/{adId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Get reporting data */
  async googleGetReporting(params: T.GoogleGetReportingData['query']): Promise<void> {
    return this.transport.request<void>({
      method: "GET",
      path: "/ad-publishing/google/reporting",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "groupBy": (params as unknown as Record<string, any>)["groupBy"],
        "startDate": (params as unknown as Record<string, any>)["startDate"],
        "endDate": (params as unknown as Record<string, any>)["endDate"],
        "type": (params as unknown as Record<string, any>)["type"],
        "fields": (params as unknown as Record<string, any>)["fields"],
      },
    });
  }

  /** Get reporting list */
  async googleGetReportingList(params: T.GoogleGetReportingListData['query']): Promise<void> {
    return this.transport.request<void>({
      method: "GET",
      path: "/ad-publishing/google/reporting/list",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "listType": (params as unknown as Record<string, any>)["listType"],
        "startDate": (params as unknown as Record<string, any>)["startDate"],
        "endDate": (params as unknown as Record<string, any>)["endDate"],
        "campaignId": (params as unknown as Record<string, any>)["campaignId"],
        "type": (params as unknown as Record<string, any>)["type"],
      },
    });
  }

  /** Get campaign reporting */
  async googleGetCampaignReporting(params: T.GoogleGetCampaignReportingData['path'] & T.GoogleGetCampaignReportingData['query']): Promise<void> {
    return this.transport.request<void>({
      method: "GET",
      path: buildPath("/ad-publishing/google/reporting/campaign/{campaignId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "startDate": (params as unknown as Record<string, any>)["startDate"],
        "endDate": (params as unknown as Record<string, any>)["endDate"],
      },
    });
  }

  /** Get conversions */
  async googleGetConversions(params: T.GoogleGetConversionsData['query']): Promise<void> {
    return this.transport.request<void>({
      method: "GET",
      path: "/ad-publishing/google/conversions",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "type": (params as unknown as Record<string, any>)["type"],
        "conversionType": (params as unknown as Record<string, any>)["conversionType"],
        "category": (params as unknown as Record<string, any>)["category"],
        "startDate": (params as unknown as Record<string, any>)["startDate"],
        "endDate": (params as unknown as Record<string, any>)["endDate"],
      },
    });
  }

  /** Upsert conversion */
  async googleUpsertConversion(params: T.GoogleUpsertConversionData['body']): Promise<void> {
    return this.transport.request<void>({
      method: "PUT",
      path: "/ad-publishing/google/conversions",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Get conversion by ID */
  async googleGetConversionById(params: T.GoogleGetConversionByIdData['path'] & T.GoogleGetConversionByIdData['query']): Promise<void> {
    return this.transport.request<void>({
      method: "GET",
      path: buildPath("/ad-publishing/google/conversions/{conversionId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
      },
    });
  }

  /** Delete conversion */
  async googleDeleteConversion(params: T.GoogleDeleteConversionData['path'] & T.GoogleDeleteConversionData['query']): Promise<void> {
    return this.transport.request<void>({
      method: "DELETE",
      path: buildPath("/ad-publishing/google/conversions/{conversionId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
      },
    });
  }

  /** Get Google integration */
  async googleGetIntegration(params: T.GoogleGetIntegrationData['query']): Promise<void> {
    return this.transport.request<void>({
      method: "GET",
      path: "/ad-publishing/google/integration",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
      },
    });
  }

  /** Create Google integration */
  async googleCreateIntegration(params: T.GoogleCreateIntegrationData['body']): Promise<void> {
    return this.transport.request<void>({
      method: "POST",
      path: "/ad-publishing/google/integration",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Get current Google user */
  async googleGetCurrentUser(params: T.GoogleGetCurrentUserData['query']): Promise<void> {
    return this.transport.request<void>({
      method: "GET",
      path: "/ad-publishing/google/me",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
      },
    });
  }

  /** Get Google ad accounts */
  async googleGetAdAccounts(params: T.GoogleGetAdAccountsData['query']): Promise<void> {
    return this.transport.request<void>({
      method: "GET",
      path: "/ad-publishing/google/ad-accounts",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "type": (params as unknown as Record<string, any>)["type"],
      },
    });
  }

  /** Get ad account details */
  async googleGetAdAccountDetails(params: T.GoogleGetAdAccountDetailsData['path'] & T.GoogleGetAdAccountDetailsData['query']): Promise<void> {
    return this.transport.request<void>({
      method: "GET",
      path: buildPath("/ad-publishing/google/ad-accounts/{adAccountId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
      },
    });
  }

  /** Delete ad account */
  async googleDeleteAdAccount(params: T.GoogleDeleteAdAccountData['path'] & T.GoogleDeleteAdAccountData['body']): Promise<void> {
    return this.transport.request<void>({
      method: "DELETE",
      path: buildPath("/ad-publishing/google/ad-accounts/{adAccountId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Publish ad */
  async googlePublishAd(params: T.GooglePublishAdData['path']): Promise<void> {
    return this.transport.request<void>({
      method: "POST",
      path: buildPath("/ad-publishing/google/ads/{adId}/publish", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** Search targeting options */
  async googleSearchTargeting(params: T.GoogleSearchTargetingData['query']): Promise<void> {
    return this.transport.request<void>({
      method: "GET",
      path: "/ad-publishing/google/targeting/search",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "type": (params as unknown as Record<string, any>)["type"],
        "query": (params as unknown as Record<string, any>)["query"],
        "locationId": (params as unknown as Record<string, any>)["locationId"],
      },
    });
  }

  /** Get keyword ideas */
  async googleGetKeywordIdeas(params: T.GoogleGetKeywordIdeasData['query'] & T.GoogleGetKeywordIdeasData['body']): Promise<void> {
    return this.transport.request<void>({
      method: "POST",
      path: "/ad-publishing/google/keyword-ideas",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
      },
      body: params,
    });
  }

  /** Get assets */
  async googleGetAssets(params: T.GoogleGetAssetsData['query']): Promise<void> {
    return this.transport.request<void>({
      method: "GET",
      path: "/ad-publishing/google/assets",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "type": (params as unknown as Record<string, any>)["type"],
        "id": (params as unknown as Record<string, any>)["id"],
        "advertiserOnly": (params as unknown as Record<string, any>)["advertiserOnly"],
      },
    });
  }

  /** Upsert assets */
  async googleUpsertAssets(params: T.GoogleUpsertAssetsData['body']): Promise<void> {
    return this.transport.request<void>({
      method: "POST",
      path: "/ad-publishing/google/assets",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Get entities */
  async googleGetEntity(params: T.GoogleGetEntityData['query']): Promise<void> {
    return this.transport.request<void>({
      method: "GET",
      path: "/ad-publishing/google/entity",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "type": (params as unknown as Record<string, any>)["type"],
        "campaignId": (params as unknown as Record<string, any>)["campaignId"],
        "adGroupId": (params as unknown as Record<string, any>)["adGroupId"],
        "entityType": (params as unknown as Record<string, any>)["entityType"],
        "searchId": (params as unknown as Record<string, any>)["searchId"],
        "startDate": (params as unknown as Record<string, any>)["startDate"],
        "endDate": (params as unknown as Record<string, any>)["endDate"],
        "selectedAdAccountId": (params as unknown as Record<string, any>)["selectedAdAccountId"],
      },
    });
  }

  /** Get target interests */
  async googleGetTargetInterests(params: T.GoogleGetTargetInterestsData['query']): Promise<void> {
    return this.transport.request<void>({
      method: "GET",
      path: "/ad-publishing/google/target-interests",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "type": (params as unknown as Record<string, any>)["type"],
        "advertisingChannelType": (params as unknown as Record<string, any>)["advertisingChannelType"],
      },
    });
  }

  /** Get segments */
  async googleGetSegments(params: T.GoogleGetSegmentsData['query']): Promise<void> {
    return this.transport.request<void>({
      method: "GET",
      path: "/ad-publishing/google/segments",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "type": (params as unknown as Record<string, any>)["type"],
      },
    });
  }

  /** Upsert segment */
  async googleUpsertSegment(params: T.GoogleUpsertSegmentData['query'] & T.GoogleUpsertSegmentData['body']): Promise<void> {
    return this.transport.request<void>({
      method: "PUT",
      path: "/ad-publishing/google/segments",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "type": (params as unknown as Record<string, any>)["type"],
      },
      body: params,
    });
  }

  /** Get segment by ID */
  async googleGetSegmentById(params: T.GoogleGetSegmentByIdData['path'] & T.GoogleGetSegmentByIdData['query']): Promise<void> {
    return this.transport.request<void>({
      method: "GET",
      path: buildPath("/ad-publishing/google/segments/{segmentId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "type": (params as unknown as Record<string, any>)["type"],
      },
    });
  }

  /** Delete segment */
  async googleDeleteSegment(params: T.GoogleDeleteSegmentData['path'] & T.GoogleDeleteSegmentData['query']): Promise<void> {
    return this.transport.request<void>({
      method: "DELETE",
      path: buildPath("/ad-publishing/google/segments/{segmentId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "type": (params as unknown as Record<string, any>)["type"],
      },
    });
  }

  /** Create offline user list job */
  async googleCreateOfflineUserListJob(params: T.GoogleCreateOfflineUserListJobData['body']): Promise<void> {
    return this.transport.request<void>({
      method: "POST",
      path: "/ad-publishing/google/segments/offline-user-list-job",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Get audiences */
  async googleGetAudiences(params: T.GoogleGetAudiencesData['query']): Promise<void> {
    return this.transport.request<void>({
      method: "GET",
      path: "/ad-publishing/google/audiences",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
      },
    });
  }

  /** Upsert audience */
  async googleUpsertAudience(params: T.GoogleUpsertAudienceData['body']): Promise<void> {
    return this.transport.request<void>({
      method: "PUT",
      path: "/ad-publishing/google/audiences",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Get audience by ID */
  async googleGetAudienceById(params: T.GoogleGetAudienceByIdData['path'] & T.GoogleGetAudienceByIdData['query']): Promise<void> {
    return this.transport.request<void>({
      method: "GET",
      path: buildPath("/ad-publishing/google/audiences/{audienceId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
      },
    });
  }

  /** Upsert Google campaign */
  async googleUpsertCampaign(params: T.GoogleUpsertCampaignData['body']): Promise<void> {
    return this.transport.request<void>({
      method: "PUT",
      path: "/ad-publishing/google/ads",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Get Google campaign by ID */
  async googleGetCampaignById(params: T.GoogleGetCampaignByIdData['path'] & T.GoogleGetCampaignByIdData['query']): Promise<void> {
    return this.transport.request<void>({
      method: "GET",
      path: buildPath("/ad-publishing/google/ads/{adId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
      },
    });
  }

  /** Get conversion goals */
  async googleGetConversionGoals(params: T.GoogleGetConversionGoalsData['query']): Promise<void> {
    return this.transport.request<void>({
      method: "GET",
      path: "/ad-publishing/google/conversion-goals",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
      },
    });
  }

  /** Get LinkedIn integration */
  async liGetIntegration(params: T.LiGetIntegrationData['query']): Promise<void> {
    return this.transport.request<void>({
      method: "GET",
      path: "/ad-publishing/linkedin/integration",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
      },
    });
  }

  /** Create LinkedIn integration */
  async liCreateIntegration(params: T.LiCreateIntegrationData['body']): Promise<void> {
    return this.transport.request<void>({
      method: "POST",
      path: "/ad-publishing/linkedin/integration",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Get LinkedIn ad accounts */
  async liGetAdAccounts(params: T.LiGetAdAccountsData['query']): Promise<void> {
    return this.transport.request<void>({
      method: "GET",
      path: "/ad-publishing/linkedin/ad-accounts",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
      },
    });
  }

  /** Get ad account details */
  async liGetAdAccountDetails(params: T.LiGetAdAccountDetailsData['query']): Promise<void> {
    return this.transport.request<void>({
      method: "GET",
      path: "/ad-publishing/linkedin/ad-account",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "adAccountId": (params as unknown as Record<string, any>)["adAccountId"],
      },
    });
  }

  /** Delete ad account */
  async liDeleteAdAccount(params: T.LiDeleteAdAccountData['query']): Promise<void> {
    return this.transport.request<void>({
      method: "DELETE",
      path: "/ad-publishing/linkedin/ad-account",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "adAccountId": (params as unknown as Record<string, any>)["adAccountId"],
      },
    });
  }

  /** Get current LinkedIn user */
  async liGetCurrentUser(params: T.LiGetCurrentUserData['query']): Promise<void> {
    return this.transport.request<void>({
      method: "GET",
      path: "/ad-publishing/linkedin/me",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
      },
    });
  }

  /** Get ad campaign group */
  async liGetCampaignGroup(params: T.LiGetCampaignGroupData['path'] & T.LiGetCampaignGroupData['query']): Promise<void> {
    return this.transport.request<void>({
      method: "GET",
      path: buildPath("/ad-publishing/linkedin/ads/{adId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
      },
    });
  }

  /** Publish ad campaign group */
  async liPublishCampaignGroup(params: T.LiPublishCampaignGroupData['path'] & T.LiPublishCampaignGroupData['body']): Promise<void> {
    return this.transport.request<void>({
      method: "POST",
      path: buildPath("/ad-publishing/linkedin/ads/{adId}/publish", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Upsert ad campaign group */
  async liUpsertCampaignGroup(params: T.LiUpsertCampaignGroupData['body']): Promise<void> {
    return this.transport.request<void>({
      method: "PUT",
      path: "/ad-publishing/linkedin/ads",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Search targeting options */
  async liSearchTargeting(params: T.LiSearchTargetingData['query']): Promise<void> {
    return this.transport.request<void>({
      method: "GET",
      path: "/ad-publishing/linkedin/targeting/search",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "facet": (params as unknown as Record<string, any>)["facet"],
        "query": (params as unknown as Record<string, any>)["query"],
        "q": (params as unknown as Record<string, any>)["q"],
      },
    });
  }

  /** Get lead forms */
  async liGetLeadForms(params: T.LiGetLeadFormsData['path'] & T.LiGetLeadFormsData['query']): Promise<void> {
    return this.transport.request<void>({
      method: "GET",
      path: buildPath("/ad-publishing/linkedin/{accountId}/forms", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
      },
    });
  }

  /** Create lead form */
  async liCreateLeadForm(params: T.LiCreateLeadFormData['query'] & T.LiCreateLeadFormData['body']): Promise<void> {
    return this.transport.request<void>({
      method: "POST",
      path: "/ad-publishing/linkedin/{accountId}/form",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
      },
      body: params,
    });
  }

  /** Update ad status */
  async liUpdateAdStatus(params: T.LiUpdateAdStatusData['path'] & T.LiUpdateAdStatusData['query'] & T.LiUpdateAdStatusData['body']): Promise<void> {
    return this.transport.request<void>({
      method: "PATCH",
      path: buildPath("/ad-publishing/linkedin/{adId}/status", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
      },
      body: params,
    });
  }

  /** Get ad analytics */
  async liGetAdAnalytics(params: T.LiGetAdAnalyticsData['query']): Promise<void> {
    return this.transport.request<void>({
      method: "GET",
      path: "/ad-publishing/linkedin/reporting",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "pivot": (params as unknown as Record<string, any>)["pivot"],
        "groupBy": (params as unknown as Record<string, any>)["groupBy"],
        "startDate": (params as unknown as Record<string, any>)["startDate"],
        "endDate": (params as unknown as Record<string, any>)["endDate"],
        "entityUrns": (params as unknown as Record<string, any>)["entityUrns"],
        "fields": (params as unknown as Record<string, any>)["fields"],
      },
    });
  }

  /** Get reporting list */
  async liGetReportingList(params: T.LiGetReportingListData['query']): Promise<void> {
    return this.transport.request<void>({
      method: "GET",
      path: "/ad-publishing/linkedin/reporting/list",
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "listType": (params as unknown as Record<string, any>)["listType"],
        "campaignId": (params as unknown as Record<string, any>)["campaignId"],
        "campaignGroupId": (params as unknown as Record<string, any>)["campaignGroupId"],
        "startDate": (params as unknown as Record<string, any>)["startDate"],
        "endDate": (params as unknown as Record<string, any>)["endDate"],
        "fields": (params as unknown as Record<string, any>)["fields"],
      },
    });
  }

  /** Get campaign group reporting */
  async liGetCampaignGroupReporting(params: T.LiGetCampaignGroupReportingData['path'] & T.LiGetCampaignGroupReportingData['query']): Promise<void> {
    return this.transport.request<void>({
      method: "GET",
      path: buildPath("/ad-publishing/linkedin/reporting/campaign-group/{campaignGroupId}", params as unknown as Record<string, unknown>),
      securityScheme: "bearer",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "startDate": (params as unknown as Record<string, any>)["startDate"],
        "endDate": (params as unknown as Record<string, any>)["endDate"],
        "fields": (params as unknown as Record<string, any>)["fields"],
        "campaignGroupId": (params as unknown as Record<string, any>)["campaignGroupId"],
      },
    });
  }
}
