// AUTO-GENERATED by scripts/generate-resources.ts — do not edit directly.
// Re-run `npm run generate` after updating the specs submodule.
import type { HttpTransport } from '../../http/transport.js';
import { buildPath } from '../shared/build-path.js';
import type * as T from './generated/types.gen.js';

export class CustomMenusResource {
  constructor(private readonly transport: HttpTransport) {}

  /** Get Custom Menu Link */
  async getCustomMenuById(params: T.GetCustomMenuByIdData['path']): Promise<T.GetCustomMenuByIdResponses[keyof T.GetCustomMenuByIdResponses]> {
    return this.transport.request<T.GetCustomMenuByIdResponses[keyof T.GetCustomMenuByIdResponses]>({
      method: "GET",
      path: buildPath("/custom-menus/{customMenuId}", params as unknown as Record<string, unknown>),
      securityScheme: "Agency-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** Update Custom Menu Link */
  async updateCustomMenu(params: T.UpdateCustomMenuData['path'] & T.UpdateCustomMenuData['body']): Promise<T.UpdateCustomMenuResponses[keyof T.UpdateCustomMenuResponses]> {
    return this.transport.request<T.UpdateCustomMenuResponses[keyof T.UpdateCustomMenuResponses]>({
      method: "PUT",
      path: buildPath("/custom-menus/{customMenuId}", params as unknown as Record<string, unknown>),
      securityScheme: "Agency-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }

  /** Delete Custom Menu Link */
  async deleteCustomMenu(params: T.DeleteCustomMenuData['path']): Promise<T.DeleteCustomMenuResponses[keyof T.DeleteCustomMenuResponses]> {
    return this.transport.request<T.DeleteCustomMenuResponses[keyof T.DeleteCustomMenuResponses]>({
      method: "DELETE",
      path: buildPath("/custom-menus/{customMenuId}", params as unknown as Record<string, unknown>),
      securityScheme: "Agency-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }

  /** Get Custom Menu Links */
  async getCustomMenus(params: T.GetCustomMenusData['query']): Promise<T.GetCustomMenusResponses[keyof T.GetCustomMenusResponses]> {
    return this.transport.request<T.GetCustomMenusResponses[keyof T.GetCustomMenusResponses]>({
      method: "GET",
      path: "/custom-menus/",
      securityScheme: "Agency-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      query: {
        "locationId": (params as unknown as Record<string, any>)["locationId"],
        "skip": (params as unknown as Record<string, any>)["skip"],
        "limit": (params as unknown as Record<string, any>)["limit"],
        "query": (params as unknown as Record<string, any>)["query"],
        "showOnCompany": (params as unknown as Record<string, any>)["showOnCompany"],
      },
    });
  }

  /** Create Custom Menu Link */
  async createCustomMenu(params: T.CreateCustomMenuData['body']): Promise<T.CreateCustomMenuResponses[keyof T.CreateCustomMenuResponses]> {
    return this.transport.request<T.CreateCustomMenuResponses[keyof T.CreateCustomMenuResponses]>({
      method: "POST",
      path: "/custom-menus/",
      securityScheme: "Agency-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
      body: params,
    });
  }
}
