// AUTO-GENERATED by scripts/generate-resources.ts — do not edit directly.
// Re-run `npm run generate` after updating the specs submodule.
import type { HttpTransport } from '../../http/transport.js';
import { buildPath } from '../shared/build-path.js';
import type * as T from './generated/types.gen.js';

export class CompaniesResource {
  constructor(private readonly transport: HttpTransport) {}

  /** Get Company */
  async getCompany(params: T.GetCompanyData['path']): Promise<T.GetCompanyResponses[keyof T.GetCompanyResponses]> {
    return this.transport.request<T.GetCompanyResponses[keyof T.GetCompanyResponses]>({
      method: "GET",
      path: buildPath("/companies/{companyId}", params as unknown as Record<string, unknown>),
      securityScheme: "Agency-Access",
      locationId: (params as unknown as Record<string, unknown> | undefined)?.locationId as string | undefined,
      companyId: (params as unknown as Record<string, unknown> | undefined)?.companyId as string | undefined,
    });
  }
}
